### ISSUE TITLE
Disable background services that are stopped.

### ISSUE THREAD

**Issue by wwwtyro** [juju-solutions/bundle-canonical-kubernetes#103]
If we're going to [stop services](https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L34-L35), we should disable them as well, so they are not restarted on reboot.

We can use the charmhelpers.core.host.[service_pause](http://bazaar.launchpad.net/~charm-helpers/charm-helpers/devel/view/head:/charmhelpers/core/host.py#L82) function for this.

**Comment by wwwtyro** [comment]
I'm gonna leave this up for now, but I'm not sure this is the correct solution. I'll be starting a discussion to root out what we need to do.

**Comment by chuckbutler** [comment]
No longer relevant, the systemd unit files are under control of snapd, and are removed once they are snap removed.
