### ISSUE TITLE
kube-dns IP is misconfigured

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#105]
I'm having some trouble with kube-dns on a dev deployment, I think due to a misconfigured IP, but I'm not 100% sure.

What I am seeing is that the kube-dns service has been created with an IP of 10.1.98.10:

```
$ kubectl get services --namespace kube-system kube-dns
NAME       CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   10.1.98.10   <none>        53/UDP,53/TCP   5h
```

However, kubelet is configured with `--cluster-dns=10.1.0.10:53`:
```
$ systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-10-20 15:21:42 UTC; 5h 2min ago
     Docs: http://kubernetes.io/docs/admin/kubelet/
 Main PID: 18736 (kubelet)
    Tasks: 16
   Memory: 42.1M
      CPU: 6min 23.582s
   CGroup: /system.slice/kubelet.service
           ├─18736 /usr/local/bin/kubelet --logtostderr=true --v=0 --address=0.0.0.0 --port=10250 --allow-privileged=false --require-kubeconfig --kubeconfig=/srv/kubernetes/config --cluster-domain=cluster.local --cluster-dns=10.1.0.10:53
           └─18820 journalctl -k -f
```

I'm guessing these two IPs should be the same.

The root of this seems to be that the DNS IP is calculated from SDN config in two different ways:

* In one case, we use the `'cidr'` key: https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L160
* In the other case, we use the `'subnet'` key: https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L549

See [this commit](https://github.com/juju-solutions/kubernetes/commit/5232b31ab0a335ba16a5f737974d74d936e7e51d) for a speculative fix that brings these two cases in line.

**Comment by mbruzek** [comment]
I spoke wiht @Cynerva on this problem. Great find by the way! Please test your commit and make any additional changes necessary to the comments and or code to make it clear what is going on. This may clean up some e2e test results too. 

@wwwtyro If you can think of a different way to generate the DNS please let us know.

**Comment by Cynerva** [comment]
Thanks Matt for having a look.

Sadly, that commit wasn't enough on its own - there's a second problem I'm hitting as well, which is that the pods/containers aren't being configured to use the cluster DNS that we pass into kubelet. I'm looking into that as well.

**Comment by Cynerva** [comment]
Fix merged, closing
