### ISSUE TITLE
kube-dns does not need port

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#107]
@Cynerva found that we may not need the dns port in the current code. We should look at removing port from the relation if is not needed or used.

**Comment by Cynerva** [comment]
@mbruzek Thanks for opening this, sorry I didn't get to it!

For context, this is a follow-up to https://github.com/juju-solutions/kubernetes/pull/64/files#diff-bdfd6f6b79f7f3171e9f0167164a7c98L164 where we removed the DNS port from --cluster-dns on the worker.

It doesn't look like there is a way to pass in a non-standard port to kubelet. This is a cleanup issue to remove "port" from the kube-dns relation as well.

**Comment by chuckbutler** [comment]
This is no longer valid as we dont use the kube-dns relationship anymore. This has been fully deprecated in favor of the kube-control relation.
