### ISSUE TITLE
Evaluate using the kube-dns binary

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#108]
I found that kubernetes allows us to build a kube-dns binary that presumably could be run via systemd. We may be able to use this instead of the docker container. If we had time to evaluate this binary, it may help us reduce our long startup time waiting for master to come up and start dns on one of the workers. But @chuckbutler keep me honest here, is there a reason we would not want to run the kube-dns as a systemd process? 

```
_output/dockerized/bin/linux/amd64# ./kube-dns -h
Usage of ./kube-dns:
      --alsologtostderr value          log to standard error as well as files
      --dns-port int                   port on which to serve DNS requests. (default 53)
      --domain value                   domain under which to create names (default "cluster.local.")
      --federations value              a comma separated list of the federation names and their corresponding domain names to which this cluster belongs. Example: "myfederation1=example.com,myfederation2=example2.com,myfederation3=example.com"
      --healthz-port int               port on which to serve a kube-dns HTTP readiness probe. (default 8081)
      --kube-master-url value          URL to reach kubernetes master. Env variables in this flag will be expanded.
      --kubecfg-file string            Location of kubecfg file for access to kubernetes master service; --kube-master-url overrides the URL part of this; if neither this nor --kube-master-url are provided, defaults to service account tokens
      --log-backtrace-at value         when logging hits line file:N, emit a stack trace (default :0)
      --log-dir value                  If non-empty, write log files in this directory
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
      --logtostderr value              log to standard error instead of files (default true)
      --stderrthreshold value          logs at or above this threshold go to stderr (default 2)
  -v, --v value                        log level for V logs
      --version[=true]                 Print version information and quit
      --vmodule value                  comma-separated list of pattern=N settings for file-filtered logging
```

We should revisit using the kube-dns binary as time allows unless there is a good reason not to.

**Comment by chuckbutler** [comment]
when we did early work, there was no clear indicator the kube-dns service was functional, and the kubernetes service listing

`kubectl cluster-info` didn't successfully register the DNS as being available until the pod was started. I'm unclear on how we can leverage the binary outside of the POD format kubernetes is expecting, but i am +1 to having it live on as part of the master services instead of being deployed into the cluster which creates additional overhead that we need to test for.

**Comment by rimusz** [comment]
kube-dns via binary would be a good option, if that of course works reliably

**Comment by chuckbutler** [comment]
Seems related to this:

https://github.com/kubernetes/kubernetes/issues/32749

its more than just kube-dns, there's also a dns-masq pod we haven't acknowledged as part of this addon. I still feel that its a brick wall as the integration path here is unclear and undocumented. It'll require some hacking to make this work.

Either super low priority, or close this out as not an objective.

**Comment by mbruzek** [comment]
I think we have proven that we can operate a cluster with the dns in a container rather than using this binary.
