### ISSUE TITLE
Make easyrsa robust and scalable

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/bundle-canonical-kubernetes#114]
Currently, if you add-unit to easyrsa it doesn't distribute a unique CA among nodes, but generates a unique one per unit. there should be a shared CA authority so that any could generate the certificates.

**Comment by mbruzek** [comment]
@marcoceppi Not sure how we would implement that. On our last tls peers charm the Juju leader would be nominated the Certificate Authority. By scaling up or down the leader changed and the new leader did not have the database of certificates from the previous leader so this caused problems. 

We need more details of the user story we need to support here and then try to translate that into operations that is possible with EasyRSA software.

**Comment by chuckbutler** [comment]
Matt has a good point here. 

As I understand it, you could reasonably sync the PKI using a peering relationship or leader-settings, and coordinate any non-leader via those channels. However it's not going to fully resolve the questions about how to best handle the leader re-election phase.

Additionally, is there ever a point in time where a unit will request a certificate and the units have not undergone a leader election? (we only need a guarantee that there IS a leader, not who is that leader)

I think that this denotes that the current PKI model is kind of somewhat broken without a notion of shared storage or a direct-sync service being installed on each unit (similar to syncthing, that "just does it" and is fault tolerant.)

**Comment by tvansteenburgh** [comment]
We likely won't make any improvements to the scalability of EasyRSA now that we offer Vault as an alternative (https://www.ubuntu.com/kubernetes/docs/using-vault).
