### ISSUE TITLE
The kubernetes-master and kubernetes-worker README.md files need to be refreshed.

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#116]
I noticed that the README.md files on both charms are not current with the code. We need to update those with the current code/features and add sections on how to enable/disable features.

We should be able to copy from the CDK README.md in many cases. But add in the charm specific features or configuration.

**Comment by Cynerva** [comment]
This is a duplicate of #99. I'mma copy the labels / assignees over and close this one out.
