### ISSUE TITLE
Make resource names unique for supporting charm resources.

### ISSUE THREAD

**Issue by wwwtyro** [juju-solutions/bundle-canonical-kubernetes#119]
We can't deploy the bundle with resources because there's no way to differentiate between e.g.,

https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-master/metadata.yaml#L35

and 

https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-worker/metadata.yaml#L23

- [ ] Make these unique so that there isn't a conflict. 
- [ ] Check for other conflicts.

**Comment by mbruzek** [comment]
@wwwtyro I don't know that bundles support resources at this time. When they do I would expect them to use a key for the charm name and the keys would be subordinate to the charm name which would sufficiently differentiate the resources.

I could envision many charms with the same resource name, but actually needing different resources.  An nginx charm may use the "nginx" resource, and a third party isv charm that __uses__ an nginx layer but has a completely different name could also use an "nginx" resource. 

We should get the core team to weigh in on resources in bundles to make sure my assumptions are correct. In any case I don't expect bundles to support resources any time soon.

**Comment by wwwtyro** [comment]
@mbruzek Thanks, I'll close this for now, then. :+1:
