### ISSUE TITLE
update bundle readme

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#128]
`juju add-unit kubernetes-worker --constraints "cpu-cores=8 mem=32G"` is incorrect.

It should be there:
```
juju set-constraints kubernetes-worker mem=32G cores=8
juju add-unit kubernetes-worker -n1
```

the same for https://github.com/juju-solutions/bundle-kubernetes-core too

**Comment by chuckbutler** [comment]
Good find, thanks for filing this
