### ISSUE TITLE
Point to existing ElasticSearch instance

### ISSUE THREAD

**Issue by gerred** [juju-solutions/bundle-canonical-kubernetes#131]
Since this may be integrated into environments with existing infrastructure, it'd be nice to be able to point at an existing ElasticSearch URL. In this instance, I'm thinking of an existing AWS ElasticSearch instance. This would still be powered by a URL.

I'm not quite sure the best way to approach this (if everyone even thinks its a good idea!), but I'm happy to submit a PR if pointed in the right direction.

**Comment by marcoceppi** [comment]
This is a great idea. We typically do this via a proxy charm which acts
like a virtual charm, you feed it configuration, it passes it along via the
interface.

**Comment by gerred** [comment]
That makes sense. How would that affect the bundle.yaml?

I'll make a proxy charm, but obviously we want to select either the elasticsearch or elasticsearch-proxy charm depending on what your configuration settings are. I'm not sure how to do that, is there an example of selecting a different charm based on a config setting?

If I have a client interface, it should look the same everywhere else.

**Comment by marcoceppi** [comment]
In the same vein, there's a community effort underway to revamp the elastic stack to 5.0
 Adding in proxy charms for things like elasticsearch fits well into that effort.

Would you expect to run Kibana on ec2 or just do beats -> external elasticsearch?

**Comment by gerred** [comment]
Oh, nice! I'll look at that effort. I'd probably expect beats -> external elasticsearch as well, since they provide a Kibana instance for you to work with. However, I wouldn't expect this in all cases (if you're using some other hosted elasticsearch provider w/o an interface). Despite that, both beats could still directly go to the ES instance right?

**Comment by marcoceppi** [comment]
It would end up being a different bundle. Taking something like Kubernetes Core or Canonical Kubernetes and replacing the bits you need to. 

Bundles are opinionated starting points. Creating a new one with some tweaks for your topology and publishing that is expected

**Comment by marcoceppi** [comment]
Absolutely, the point of a proxy charm is to avoid having to modify charms when an existing communication channel exists. elasticsearch-proxy, or external-elasticsearch is like Oracle MySQL and Percona or MariaDB. It's still a MySQL just a different flavor.

@chuckbutler led the first meeting for elastic a few days ago. He should have the pointers and we'll have another meet up the first week of December.

**Comment by gerred** [comment]
Awesome. Do you think this is worth still an open issue, or taking over to the elasticsearch repo?

**Comment by marcoceppi** [comment]
I think it's fine to keep open here for now. The elastic stack is under so
much flux I'd hate for it to be lost in the shuffle.

**Comment by chuckbutler** [comment]
@gerred actually, this depends largely on how many units / volume of data you're planning on routing to Elasticsearch with the beats. If you have > 15 units, with any sizeable volume of workloads running I would highly recommend looking into buffering your beats output with Logstash.

You'll see in the coming iterations as the elastic stack 5.0 upgrade completes that logstash makes a cameo in the bundle. It's to mitigate installations which were originally intended for small-clusters, that are now likely to be large-spanning workload farms with many kubernetes-worker groups/pools.
