### ISSUE TITLE
[Track] UpdateAddonsTactic not compatible with charm-tools/master

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#132]
`UpdateAddonsTactic` introduced in https://github.com/juju-solutions/kubernetes/pull/84 gives an exception when running `charm build` with the [charm-tools master branch](https://github.com/juju/charm-tools/tree/master).

Method signatures in charm-tools differ between [master/tactics.py](https://github.com/juju/charm-tools/blob/master/charmtools/build/tactics.py) and [2.1/tactics.py](https://github.com/juju/charm-tools/blob/2.1/charmtools/build/tactics.py). Our tactic supports the 2.1 line.

No idea what's going on with charm-tools versioning or what the master branch represents.

**Comment by chuckbutler** [comment]
@marcoceppi Can you add some insight here as to what we should be tracking for that tactic?

**Comment by Cynerva** [comment]
Closing, UpdateAddonsTactic is no more.
