### ISSUE TITLE
Port forwarding is broken due to missing socat package

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#135]
The `socat` package appears to be required on the kubernetes-master charm.

```
E1117 15:48:41.963192   46813 portforward.go:329] an error occurred forwarding 49400 -> 44134: error forwarding port 44134 to pod tiller-deploy-2241983194-k4tdu_kube-system, uid : unable to do port forwarding: socat not found.
```

**Comment by gerred** [comment]
kubernetes-worker as well!

It also looks like it breaks through the load balancer as well. I've temporarily exposed the master and am working with it directly, but I get an upgrade request. I've done a lot less looking into that one.

**Comment by chuckbutler** [comment]
@gerred - i'm half tempted to sit down and write an haproxy config for the api-lb and drop that in place of nginx instead of fiddling with the nginx vhost further.

In the interrim i did propose a branch that adds the socat package to both worker and master in a nieve attempt to resolve the issue above. We'll get this shipped in the next release of the charms.

**Comment by marcoceppi** [comment]
@chuckbutler I've got the start of an HAProxy layer that we could colab on

**Comment by chuckbutler** [comment]
Sounds good @marcoceppi. Let's spike on that next week (if you're agreeable) for a day and come up with a suitable haproxy based replacement/migration for the api-lb.  I'm not happy with what's there now that we have empirical evidence of its failure scenario when being used with third party apps.

**Comment by chuckbutler** [comment]
Aside from the off-topic bits about the HAProxy layer replacing the nginx based API-LB, I think this is satisfactorily closed. Please re-open if this is not the case. I'll create an additional issue to track the LoadBalanceer issue.

**Comment by chuckbutler** [comment]
Linked against #148
