### ISSUE TITLE
Keystone authentication

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/bundle-canonical-kubernetes#141]
Keystone Authentication is experimental, test it out see if it's worth integrating with keystone charm

**Comment by chuckbutler** [comment]
This looks dead upstream:

https://github.com/kubernetes/kubernetes/pull/25391
https://github.com/kubernetes/kubernetes/pull/25624

Suggest we close this pending further development upstream

**Comment by tvansteenburgh** [comment]
https://www.ubuntu.com/kubernetes/docs/ldap
