### ISSUE TITLE
Flannel CNI

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/bundle-canonical-kubernetes#142]
Need to migrate flannel to CNI pending the merge of juju-solutions/kubernetes#88

**Comment by axinojolais** [comment]
Hi,

The bundles need an update, the sdn-plugin relation is gone.

Thanks

**Comment by chuckbutler** [comment]
Flannel CNI went out with the last release in 2016, which included the updated and preferred interface `cni`
