### ISSUE TITLE
Some of the tests are excluded in tests.yaml

### ISSUE THREAD

**Issue by seman** [juju-solutions/bundle-canonical-kubernetes#146]
Undo excluding the following charm tests in tests.yaml:
  - filebeat
  - topbeat
  - elasticsearch
  - kibana

**Comment by mbruzek** [comment]
@seman we are talking about removing the elastic stack from the bundle because it is not core Kubernetes components. Is there a reason you need this re-enabled before we remove the stack?

**Comment by mbruzek** [comment]
See #138 for more details. @marcoceppi still has this in progress.

**Comment by seman** [comment]
@mbruzek does the elastic stack include all the charms mentioned?

**Comment by marcoceppi** [comment]
It is all the charms mentioned

**Comment by chuckbutler** [comment]
The addon(s) such as elastic stack have been removed from teh CDK bundle at this time in favor of flavors. This should be addressed in another issue attached to those bundles, at this time - the bundle tests are tuned appropriately.

Please re-open this issue if you disagree
