### ISSUE TITLE
Replace NGINX APILoadBalancer with HAPROXY

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#148]
TBD

**Comment by fire** [comment]
Is there a justification for this?

**Comment by marcoceppi** [comment]
This is for the kubeapi-loadbalancer not for ingress controllers (which are
by default, but could be replaced by the user using kubectl).

Last I checked we couldn't do just TCP proxying with NGiNX which has an
advantage when creating an LB outside of a cloud with LBaaS. So in
OpenStack, VMWare, Bare Metal, and other clouds.

**Comment by chuckbutler** [comment]
This doesn't appear to still be valid. Pinging @marcoceppi and @tvansteenburgh for acceptance to close this bug.

**Comment by tvansteenburgh** [comment]
I'm +1 on closing. If we need to revisit this later we can open a new issue then.

**Comment by hzamani** [comment]
Using TCP proxying for api-loadbalancer will be a step toward supporting RBAC which will address #246 and maybe #205.

For testing this solution I have enabled RBAC in a patched CDK deployment with NGINX replaced with HAPROXY, except ingress that needs to be enabled using kubectl (as noted by @marcoceppi), everything was OK.

Isn't it time to revisit this issue?

**Comment by chuckbutler** [comment]
greetings @hzamani  - we've actually been cycling on an RBAC branch for CDK. 

If you're interested in giving it a go the branch is at https://github.com/juju-solutions/kubernetes/tree/juju-enable-rbac

I'd love to collab on this with you and get you up and running. I don't understand why we would need to replace nginx with haproxy in this case, we've tuned the nginx api-loadbalancer to support the required headers for HTTP2 protocols which negated any need for replacing with HAProxy.

However if there are additional reasons why you would want this it would certainly be good to get some feedback here, and any contributions to enable an haproxy based lb would be welcome.

**Comment by hzamani** [comment]
Thanks @chuckbutler. Cat you provide instructions on deploying/testing this branch? There is a utils.sh file there, but it seems out of date.
