### ISSUE TITLE
Update for 1.5.0 - needs new flag 'anonymous-auth'

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#150]
[ slightly edited snip from the slack channel ]

There’s an important new flag that has to be set in 1.5.0 - `anonymous-auth`
for users of RBAC/ABAC (Role Based Access Control / Auth Based Access Control)

In particular, it needs to pass `--anonymous-auth=false`

I believe there will be a 1.5.1 shortly that either panics if you have anonymous-auth and no ABAC/RBAC, or does something similar

`--anonymous-auth=true` (the default) + `--authorization-mode=AlwaysAllow` (the default) is bad news

It is called out in the release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#action-required-before-upgrading

**Comment by marcoceppi** [comment]
1.5.1 removes this, which is out. We should target 1.5.1
