### ISSUE TITLE
kubernetes-worker : can't specify no_proxy variable 

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#162]
Hi,

The kubernetes-worker charm has 2 config options related to proxying (http_proxy and https_proxy). However, there is no way to instruct the charm to _not_ proxy some domains, which is generally done with the no_proxy environment variable.

Could this please be added ?

Thank you

**Comment by axinojolais** [comment]
This is needed for example to use a docker registry deployed on the k8s cluster.

**Comment by mbruzek** [comment]
We can take a look at our priorities and add this feature to the list. Please provide us with your specific use case (config values) so we can test/verify. 

If you don't want to wait for us to add it to our prioritized list, the code is open source and available here: https://github.com/juju-solutions/kubernetes/tree/master-node-split in the kubernetes/cluster/juju/layers/kubernetes-worker directory. Pull requests would be most welcome and may be faster than waiting on us to get to that feature request.

**Comment by axinojolais** [comment]
My specific use case is that I want to deploy and use an image registry within my kubernetes cluster, and so I would like to avoid having to go through the proxy to fetch images on the kubernetes-worker units, since the registry is actually running on the worker units themselves.

If my private repository is hosted at kubernetes-registry.internal:5000, the option would take the value of "kubernetes-registry.internal".

Does that make sense ?
