### ISSUE TITLE
all charms except elasticsearch are missing nrpe-external-master interface

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#165]
Hi,

If this bundle is to be used in a production setup, each unit must be monitored with specific, service-level checks. This is generally done via an nrpe-external-master interface, and an nrpe subordinate.

Without such a relation, we can only get very basic monitoring of the units (CPU load, memory used, etc) and not service-level checks.

Thanks

**Comment by axinojolais** [comment]
This will also be needed for kubeapi-loadbalancer

**Comment by arosales** [comment]
Canonical Kubernetes (https://jujucharms.com/canonical-kubernetes/) consists of the following charms:
- kubeapi-load-balancer 
- kubernetes-master  
- etcd  
- kubernetes-worker 
- easyrsa 
- flannel

nrpe-external-master relation with basic checks have been merged into:
- [x] flannel
- [x] kubernetes-master  
- [x] kubernetes-worker 
- [x] etcd

nrpe-external-mater relation with basic checks still needed in:
- [ ] kubeapi-load-balancer
- [ ] easyrsa

@axinojolais 
You specifically mentioned kubeapi-load-balancer, but I wanted to confirm easyrsa was also needed.

-thanks,
Antonio

**Comment by Cynerva** [comment]
@arosales They're not in kubernetes-master or kubernetes-worker quite yet, but close.

PR [#40897](https://github.com/kubernetes/kubernetes/pull/40897) (and my follow-up squash, [#41923](https://github.com/kubernetes/kubernetes/pull/41923)) will add the nrpe-external-master relation to kubernetes-master, kubernetes-worker, and kubeapi-load-balancer.

**Comment by chuckbutler** [comment]
Seems to me that generic monitoring is what is expected for the EasyRSA charm. It doesn't run a daemon or anything in particular that needs to be checked on a continual basis, as it's just a handful of bash scripts used to manage PKI.

The apilb, however, could benefit from whatever Nginx checks Nagios knows about. So to be clear, this issue is down to a single nrpe interface integration for the load balancer unit.

**Comment by jacekn** [comment]
@chuckbutler just to clarify - we do have generic systemd service for nginx in place so if nginx goes down nagios will know.
We can of course do better than that and write custom apilb check using check_http to make sure we get sane data from the API
