### ISSUE TITLE
kubernetes layers are embedded in the full kubernetes repository

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#168]
Hi,

Is there a reason the kuebernetes-master, kubernetes-worker and kubeapi-loadbalancer charms (or, to be precise, layers) are embedded in the full kubernetes repository ? Couldn't they be in a separate, standalone repository ?

Cloning 315MB just to hack on a few files that are <1MB isn't a great experience. And I don't see any dependency from one to the other (perhaps resources ? Not sure resources mandate this kind of layout though).

Thanks

**Comment by castrojo** [comment]
The reasoning for this is so that anybody who has the kubernetes repo can deploy on-the-spot with the charms right from the local branch.

@chuckbutler don't we have the source code branches available in the juju-solutions namespace so he could grab the code quicker without pulling down all of k8s?

**Comment by chuckbutler** [comment]
Negative, in the juju-solutions namespace, the principal kubernetes charm layers live in that behemoth of a repository. its an unfortunate side effect of working on the most popular project on Github. it comes with a HUGE repository meta archive (somewhere near 300mb of meta on initial pull).

**Comment by wwwtyro** [comment]
@chuckbutler @castrojo Is using git submodules an option here? If not, this is probably as good as we can do and can close this issue.

**Comment by tvansteenburgh** [comment]
It's likely that we'll move out of kubernetes/kubernetes at some point, at which point this will no longer be relevant. No reason to keep this open in the meantime.
