### ISSUE TITLE
nginx' buffering on kubeapi-loadbalancer is breaking kubectl

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#172]
Hi,

I'm adding a Juju action to create and delete a [docker registry](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry), much like the currently existing "microbot" action. The creation works fine, but the deletion always fails, specifically the deletion of the replicationcontroller.

I found the root cause to be the bufferring of nginx in the kubeapi-loadbalancer unit. More specifically, when the "kubectl delete" action is run against a replicationcontroller, kubectl tries to monitor the "downscaling" of said replicationcontroller using a URL in the form of : 

```
/api/v1/watch/namespaces/default/replicationcontrollers?fieldSelector=metadata.name%3Dkube-registry-v0
```

This "/watch/" URLs streams data, but because nginx buffers said data (presumably until the connection is closed from the client, which it never is because the client doesn't receive  data !), it never reaches the kubectl client. The connection is then closed by nginx, because of the "proxy_read_timeout  90;" config option.

This is fixed by adding the following to the nginx configuration : 
```
proxy_buffering off;
```

However, I am no nginx expert, so I'm not sure if there are other consequences to turning off this buffering.

Thanks

**Comment by chuckbutler** [comment]
@axinojolais I think we're good to enable this at least in the short term. I have a lofty goal of replacing this nginx load balancer with an haproxy based LB for better connectivity support.
