### ISSUE TITLE
bad permissions on ~/.kube/ on kubernetes-worker units

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#173]
Hi,

When the kubernetes-work charm creates ~/.kube/config, it does so as root.
It then [chowns the "config" file to ubuntu:ubuntu](https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L272). 

However, this leaves ~/.kube owned by root:root, which prevents kubectl commands running on the unit from using caching. Example error message (from ```kubectl get po -v=8```) : 
```
I0103 14:51:14.837391    9153 cached_discovery.go:123] failed to write cache to /home/ubuntu/.kube/cache/discovery/10.25.62.147_443/servergroups.json due to mkdir /home/ubuntu/.kube/cache: permission denied
```

This issue is resolved with a simple "chown ubuntu:ubuntu ~/.kube"

Thanks

**Comment by chuckbutler** [comment]
Patch submitted in https://github.com/juju-solutions/kubernetes/pull/96

**Comment by chuckbutler** [comment]
@mbruzek @wwwtyro @Cynerva   Need some eyeballs on this one, should be bite sized though :)

**Comment by chuckbutler** [comment]
Closed, will be released with the next charm cut
