### ISSUE TITLE
doc: update with etcd persistent storage example

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#178]
readme should include an example/url how to set etcd with persistent storage.

In my opinion it should come by default.

**Comment by marcoceppi** [comment]
@castrojo I think this is already documented in the kubernetes.io Pull request, can you make sure and if not update?

**Comment by rimusz** [comment]
hmm, using `juju add-storage etcd/0 data=ebs-ssd,25G` takes that node from etcd cluster away.
`juju ssh etcd/1`:
```
$ etcdctl cluster-health
failed to check the health of member 109a9cd443e2c706 on https://172.31.15.106:2379: Get https://172.31.15.106:2379/health: dial tcp 172.31.15.106:2379: getsockopt: connection refused
member 109a9cd443e2c706 is unreachable: [https://172.31.15.106:2379] are all unreachable
member 3c822eaf8c6e9f15 is healthy: got healthy result from https://172.31.18.177:2379
member d25671fb6480dd67 is healthy: got healthy result from https://172.31.8.46:2379
cluster is healthy
```

**Comment by marcoceppi** [comment]
That shouldn't happen. Is it still out of the cluster?

**Comment by rimusz** [comment]
yup, had to remove it from cluster manually

**Comment by rimusz** [comment]
the worst is, I added another new etcd node, which joined the cluster, but afterwards only 50 from 100 connections to k8s API via `kubectl` worked

**Comment by chuckbutler** [comment]
Was there any indication as to why the node connections were failing? When the storage is requested a few events happen:

1) The block storage volume is mounted in a temporary location and is formatted to ext4
2) The etcd service is halted
3) A copy of the etcd db files (WAL and Data) are moved into path on the block device
4) etcd is spun back up


Nothing in this list should have modified the etcd configuration to where it misbehaves in the cluster after it has joined, that I can tell. Logs are going to be necessary to track down why the unit was failing and potentially we will need to file a bug against upstream or against the etcd charm to better handle whatever is happening.

**Comment by rimusz** [comment]
let me try to reproduce it again

**Comment by rimusz** [comment]
cannot reproduce it this time, attached volume to etcd/0, waited, checked, all fine, cluster is healthy, repeated for etcd/1/2 with success too.
accessing k8s API with kubectl works fine too

**Comment by chuckbutler** [comment]
Ok, There's likely something racey in the etcd charm that caused this, I've got this running in a cycle trying to deploy, format +mount on all 3, to reproduce a failure scenario. If i come up with something in the next hour i'll get it bugged and add it to the roadmap.

Thanks for attempting to reproduce @rimusz

**Comment by chuckbutler** [comment]
I haven't been able to reproduce this in some time. Closing pending further information.
