### ISSUE TITLE
`juju remove-application kubernetes-worker` fails to remove workers

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#179]
running `juju remove-application kubernetes-worker` does not remove instances and flannel relation on AWS.
```
kubernetes-worker/0*          terminated  executing  6        1.2.3.2   80/tcp,443/tcp  (stop)
  flannel/1                   active      idle                1.2.3.2                   Flannel subnet 10.1.8.1/24
kubernetes-worker/1           terminated  executing  7        1.2.3.3    80/tcp,443/tcp  (stop)
  flannel/2                   active      idle                1.2.3.3                    Flannel subnet 10.1.41.1/24
kubernetes-worker/2           terminated  executing  8        1.2.3.4     80/tcp,443/tcp  (stop)
  flannel/3                   active      idle                1.2.3.4                     Flannel subnet 10.1.38.1/24
```

`juju debug-log --include kubernetes-worker/0` does not return anything

**Comment by chuckbutler** [comment]
I've managed to reliably reproduce this issue with juju 2.0.2 on both AWS and GCE despite having successful results earlier in the day.


To reproduce:

```
juju deploy canonical-kubernetes
... wait for convergence ...
juju remove-application kubernetes-worker
```

There will be no indication as to what has failed in the unit logs, and the unit is stuck in (Stop) without ever reaching the (Terminated) state. This yields in an unresponsive model, and the inability to scale worker pools. This seems like it may be related to unit self removal (unverified), and/or something going awry in the machine/unit agent (unverified).

**Comment by chuckbutler** [comment]
This appears to have been patched with:

https://github.com/juju-solutions/charm-flannel/pull/26
https://github.com/juju-solutions/charm-flannel/pull/27

and potentially

https://github.com/juju-solutions/layer-etcd/pull/71


After this weeks publication lets see if we did indeed catch these bugs. I have promising results in early testing of these changes.

**Comment by rimusz** [comment]
flannel now is really causing problems of deleting resources:
```
kubernetes-worker/2       active    executing  8        1.2.3.4  80/tcp,443/tcp  Kubernetes worker running.
  flannel/3               error     idle                1.2.3.4                  hook failed: "stop"
```
Let's hope those fixes above will sort that out

**Comment by chuckbutler** [comment]
The flannel stop bug was resolved with the missing file fix, and restart on reboot. That will ship with our release this thursday/friday. I'm aiming for Thursday so you can test on Friday.

**Comment by chuckbutler** [comment]
@rimusz - as a follow up I've published into the bleeding edge channel with those fixes for both etcd and flannel

juju deploy cs:~containers/bundle/canonical-kubernetes-16

Can you see if this resolves your issues with flannel/etcd?

**Comment by rimusz** [comment]
sure, will check it out

**Comment by rimusz** [comment]
@chuckbutler I get `ERROR cannot resolve charm URL "cs:~containers/bundle/canonical-kubernetes-16": cannot get "/~containers/bundle/canonical-kubernetes-16/meta/any?include=id&include=supported-series&include=published": unauthorized: access denied for user "rmocius"`

**Comment by chuckbutler** [comment]
Ah permissions. My mistake. I didn't check that before handing it over

charm grant ~containers/bundle/canonical-kubernetes-16 --channel=edge everyone

You should be able to resolve/deploy now.

**Comment by rimusz** [comment]
`cs:~containers/xenial/flannel-8 unauthorized: access denied`

**Comment by chuckbutler** [comment]
Bumped permissions on both etcd and flannel, again, sorry about the permissions.

**Comment by wwwtyro** [comment]
@rimusz Any success here?

**Comment by rimusz** [comment]
@wwwtyro will check that tomorrow and let you know

**Comment by chuckbutler** [comment]
No rush on the response, we'll give it some additional testing here, and would like to coordinate the results with your own results as the stakeholder to ensure we've closed this out satisfactorily.
