### ISSUE TITLE
The default ingress controller cannot be tweaked via configmaps

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#186]
Hi,

The ingress controller created by the kubernetes-worker "ingress" config option cannot be tweaked by a configmap. I believe that should be the case.

As far as I understand, you'd only need to call the ```nginx-ingress-controller``` process with the additional argument ```--nginx-configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf```

Specifically, I would use the config map to tweak the ```client_max_body_size``` nginx parameter, which is 1MB by default, preventing e.g. a Docker registry to be fronted by an Ingress object.

Thanks

**Comment by chuckbutler** [comment]
Thanks for filing this @axinojolais. I think we have some usage gaps where we haven't had the requirement of tuning the ingress controller, but this certainly seems like something we should support out of the box. I don't think we'll get to this until next week.

**Comment by jacekn** [comment]
This issue is addressed by https://github.com/juju-solutions/kubernetes/pull/108

**Comment by chuckbutler** [comment]
Landed and resolved as of https://github.com/kubernetes/kubernetes/pull/44500
