### ISSUE TITLE
Parse juju status output for the makefile to determine leader

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#19]
From: #18 

The master is not always node 0. We should come up with a way to find the master unit for any given charm (even if it is some contrived juju run command that parses the result).

**Comment by battlemidget** [comment]
Ive add a function in conjure-up to do this feel free to take it and use it:

https://github.com/ubuntu/conjure-up/blob/master/share/hooklib/common.sh#L55-L75

**Comment by mbruzek** [comment]
We are not doing any leader specific stuff any longer.
