### ISSUE TITLE
Remove built bundles from repo

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#190]
From https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/189:

> restore readme changes that were pushed to the built readme :(

Let's prevent that from happening again by removing build artifacts from the repo.

**Comment by chuckbutler** [comment]
can we remove them and feesibly .gitignore them? is that something we are interested in?

**Comment by Cynerva** [comment]
> can we remove them and feesibly .gitignore them?

Yeah, seems like the way to go. I'm not aware of any reason we couldn't.

> is that something we are interested in?

Less error prone if we do that, I think, so yeah

**Comment by chuckbutler** [comment]
@mbruzek - This is a core change to our bundle repo that will effect our builders. I'd like your feedback on the above as well.

**Comment by wwwtyro** [comment]
Here's a PR with the relevant changes: https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/191

Note that the READMEs will now only live in the charm store. I've moved the bundler README to the top.
