### ISSUE TITLE
InfluxDB is not available on LXD [zesty]

### ISSUE THREAD

**Issue by ChrisMacNaughton** [juju-solutions/bundle-canonical-kubernetes#193]
[debug-20170113115233.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/704203/debug-20170113115233.tar.gz)

**Comment by Cynerva** [comment]
Thanks for the debug logs. Here's the relevant bit I found in kube-apiserver logs:
```
Jan 13 11:20:47 juju-9598ad-5 kube-apiserver[15606]: I0113 11:20:47.740279   15606 log.go:76] Error getting ResourceLocation: no endpoints available for service "monitoring-influxdb"
Jan 13 11:20:47 juju-9598ad-5 kube-apiserver[15606]: I0113 11:20:47.740781   15606 panics.go:76] GET /api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb: (1.18863ms) 503
```

I'm able to reproduce this on both LXD and AWS by running `kubectl proxy` and navigating to `http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb`, where I get the following response:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"monitoring-influxdb\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

I don't see any immediately obvious reason this is occurring, as monitoring-influxdb does have two open endpoints:

```
$ ./kubectl get svc -n kube-system monitoring-influxdb
NAME                  CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
monitoring-influxdb   10.152.183.209   <none>        8083/TCP,8086/TCP   18m

$ ./kubectl get ep -n kube-system monitoring-influxdb
NAME                  ENDPOINTS                       AGE
monitoring-influxdb   10.1.87.5:8086,10.1.87.5:8083   19m
```

Maybe it's expecting one on port 80? Dunno.

**Comment by chuckbutler** [comment]
This is tied directly to https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/298

As the two are linked I'm going to close this one and track in issue 298
