### ISSUE TITLE
kubeapi-loadbalancer can't talk SPDY / HTTP2 to the kubeapi server

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#201]
Hi,

Whenever someone wants to "kubectl exec" from outside the cluster, and with the config provided by default, the kubectl client will talk to the kubeapi-loadbalancer. Said kubeapi-lb will terminate the TLS connection, and open up a new one to the backend, the kubeapi server. However, it would appear that the kubeapi server only supports SPDY / HTTP2 connections for "kubectl exec", and nginx is unable to do so on its backend connections.

There is no workaround (except intercept connections to the kubeapi-lb and redirect them directly to kubeapi, with iptables, bypassing the lb entirely).

A possible solution is to switch to haproxy and do L4 load-balancing.

Thank you

**Comment by arosales** [comment]
@axinojolais,

Its looking like this won't make the 17.02 (Feb 28) release date with the k8 1.6 feature freeze (https://github.com/kubernetes/features/blob/master/release-1.6/release-1.6.md).  We are targeting this issue for the 17.03 (March 28) charm release and may have a personal-name space charm sooner for testing. @chuckbutler has started working on this, but the fix isn't trivial. Rough estimate of about 2 weeks of development work and then testing before releasing.

I understand this is a production blocker and we'll try to address asap.

-thanks,
Antonio

**Comment by mbruzek** [comment]
@axinojolais I prototyped an haproxy reverse proxy using tcp mode set. We got tls errors on worker connections because the kubeapi-load-balancer's ip address is not in the kubernetes-masters certificates as a valid SAN. Do you have any other suggestions or know how to work around this problem while using IP addresses and TLS certificates?

**Comment by axinojolais** [comment]
Apart from adding them to the certificate (which perhaps the k8s-master could do with information from the load-balancer relation), I don't have a workaround no, sorry.

**Comment by mbruzek** [comment]
@axinojolais I have created a pull request against kubernetes that resolves this issue in my testing. Please look at https://github.com/kubernetes/kubernetes/pull/43625
