### ISSUE TITLE
Import cluster state from another cluster

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#207]
Would be awesome to have an option to import Kubernetes state from another cluster, which would allow an easy migration to CDK.

Like in my case running self created k8s cluster in AWS, would allow to move all work to CDK with all PVCs based on AWS EBS.

**Comment by chuckbutler** [comment]
this scares me for a couple reasons

1) Typically in deployments you wind up with some object types that aren't truly portable. Unless you're manually importing the EBS volume ID's and ensure they are detached before you attempt a restore.

I'm happy to humor the idea and give it a go so you can totally prove that I'm just being a worry wart here, but I feel like we're going to bump our heads. Every time I've tried a cluster migration I find nit-noid things that I wouldn't think would be blockers but they are unless i'm using the simplest of workloads.

**Comment by rimusz** [comment]
let's have a chat about it tomorrow at summit

**Comment by chuckbutler** [comment]
we had a good chat about this, to make sure the information is making it back outside of the vacuum of physical space: 

The etcd dump action is a good first step here. We're talking a bit more in terms of documenting what this process looks like, and what those concerns would be for PersistentVolumes. Its OK to have those workloads CLBO until the old cluster has released the assets (in regards to storage)

I'm not sure what other blockers would be there, but let's start there and get this shipped to users wanting to migrate things.

**Comment by chuckbutler** [comment]
Prelim work on this was done - https://github.com/juju-solutions/layer-etcd/issues/58

There are additional bits to consider here but the etcd dump+restore is a good first vector for this work and we can iterate from there. I'm not crazy about losing ResourceRevisions, but this is a byproduct of the dump+restore procedure in etcd.
