### ISSUE TITLE
Migration to k8s v1.6 and etcd v3

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#208]
How would migration to k8s v1.6 and etcd v3 would look like? Any plans for that already?

**Comment by marcoceppi** [comment]
Yes, we're in the process of updating etcd charm to support migration from 2 -> 3 and producing the instructions necessary for the k8s charms to process that. We should have a beta of this when 1.6-beta2 hits

**Comment by rimusz** [comment]
just awesome 👍

**Comment by chuckbutler** [comment]
xref with the work taking place in etcd
https://github.com/juju-solutions/layer-etcd/pull/77

**Comment by chuckbutler** [comment]
xref with https://github.com/juju-solutions/layer-etcd/pull/78 (continuation of layer-etcd#77)

**Comment by chuckbutler** [comment]
I feel that the initials in this are complete, however etcd v3 is not fully suported in the kubernetes-master charm that i'm aware of. It needs logic to do two things

- [ ] Disable the etcdv2 keyspace backend (which is hard enabled at this time)
- [ ] Migrate the existing data to v3 format. (represented by #287)

**Comment by wwwtyro** [comment]
There's other issues covering the etcd v3 migration, so I'm closing this.
