### ISSUE TITLE
Support CoreOS rkt as alternative runtime engine to docker

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#209]
It looks like k8s v1.6 finally will bring rkt support (beta) via CRI, would be nice to have it as an option.

**Comment by chuckbutler** [comment]
I think this will be included as part of the CRI work as that matures. I believe that will also make a debut in 1.6

**Comment by mbruzek** [comment]
Do you really want *more* coreOS?

**Comment by rimusz** [comment]
heh, rkt is way better than docker as kube runtime engine

**Comment by chuckbutler** [comment]
I think we'll tackle adding RKT support when CRI lands as beta. CRI abstracting the container runtime would be a good vector to deprecate the Docker layer that we have based the k8s charm layers on and can instead refactor to CRI, and then make that model pluggable. 

This seems like post 1.6 work, potentially into the 1.7/1.8 cycle depending on how quickly the Container Runtime Interface stabilizes.

**Comment by rimusz** [comment]
CRI should land as beta in k8s v1.6

**Comment by chuckbutler** [comment]
I've read the same, but we wont be able to ship it with the 1.6 release, so it's likely to be a post 1.6 release or 1.7 depending on time/effort it takes to gut layer-docker and re-focus around layer-cri.

**Comment by tvansteenburgh** [comment]
We have no plans to offer rkt as a configurable container runtime option. Containerd will be next.
