### ISSUE TITLE
Support at least two last kubernetes versions

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#211]
e.g. v1.4x and v1.5x, have two separate charms versions for that, as it is not always possible to move to the latest version, when it gets released.

**Comment by rimusz** [comment]
cc @chuckbutler

**Comment by chuckbutler** [comment]
The charms + snaps now accomplish this goal. You can install the 1.5 series and 1.6 series respectively. Moving between levels of risk using the channels.

eg:

```
juju config kubernetes-master channel=1.5/stable
juju config kubernetes-master channel=1.6/stable

juju config kubernetes-worker channel=1.5/stable
juju config kubernetes-worker channel=1.6/stable
```

or if you want to subscribe to more risk by using our progression channels where we release in-progress work:

```
juju config kubernetes-worker channel=1.6/candiate
juju config kubernetes-worker channel=1.6/beta
juju config kubernetes-worker channel=1.6/edge
```
The same options are available to the kubernetes-master charm respectively.
