### ISSUE TITLE
microbot and create-rbd-pv actions broken in upstream repo

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#212]
@wwwtyro hit this issue running microbot during development:
```
unit-kubernetes-worker-0: 14:03:55 INFO unit.kubernetes-worker/0.microbot Traceback (most recent call last):
unit-kubernetes-worker-0: 14:03:55 INFO unit.kubernetes-worker/0.microbot   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/actions/microbot", line 20, in <module>
unit-kubernetes-worker-0: 14:03:55 INFO unit.kubernetes-worker/0.microbot     from charmhelpers.core.hookenv import action_get
unit-kubernetes-worker-0: 14:03:55 INFO unit.kubernetes-worker/0.microbot ImportError: No module named charmhelpers.core.hookenv
```

It looks like the shebang was broken during our squash and merge upstream. Compare:
- [microbot in juju-solutions/master-node-split](https://github.com/juju-solutions/kubernetes/blob/master-node-split/cluster/juju/layers/kubernetes-worker/actions/microbot)
- [microbot in kubernetes/master](https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/actions/microbot)

We need to revert back to python3.

Looks like the same thing happened to [create-rbd-pv](https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-master/actions/create-rbd-pv) as well:
```
2017-02-06 20:20:03 INFO create-rbd-pv /usr/bin/env: 'python': No such file or directory
```

This does not affect the current stable release of CDK, but is a problem in the upstream repo.

**Comment by Cynerva** [comment]
@mbruzek @chuckbutler Any idea why these were changed during the squash+rebase? Am I going to break something else if I try to revert the shebangs back to python3?

**Comment by chuckbutler** [comment]
@Cynerva yeah, this was due to their lintian thing....

**Comment by chuckbutler** [comment]
Good find on this, I don't think we did check those actions post change, as the shebangs looked proper being routed through env. 

We'll need to probably default their linter settings to not check the actions in cluster/juju tree

**Comment by mbruzek** [comment]
I also think it is fine to put in python3 shebang, but we will need to appease the lint tool either by an exclude on this rule or the whole directory.

**Comment by Cynerva** [comment]
Thanks, that makes sense. I'm having trouble finding the lint tool in question so I'll check back on this later in the week. Any pointers would be appreciated!
