### ISSUE TITLE
KubeDNS ConfigMap Addon was updated upstream, which breaks against previous releases of CDK

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#213]
During a deployment, the kubedns maps are working with whats in teh charm store, however the addon template apparently landed a change which has broken when building from source

```
error: error validating "/etc/kubernetes/addons/kubedns-controller.yaml": error validating data: found invalid field optional for v1.ConfigMapVolumeSource; if you choose to ignore these errors, turn validation off with --validate=false
```

I know this was pending an actual re-publish of the container, but that's not whats listed as broken here, its the presence of the config-map being listed as optional. We've either botched a translation or the template is broken upstream, and we should really fix this before the next CDK rev.

**Comment by Cynerva** [comment]
Thanks @chuckbutler. Here's the upstream PR that made this change: https://github.com/kubernetes/kubernetes/pull/40382

The `optional` field for configmaps was implemented recently: https://github.com/kubernetes/kubernetes/pull/39981

So, this is a versioning problem. We're pulling in a fancy new addon definition before we have the kubernetes binaries to support it.

This might be a good argument for packaging the addons as a resource, which we can update independently, rather than pulling them into the charm at build time.

An alternative would be to give `UpdateAddonsTactic` the option to checkout a non-master branch, though I'm not a big fan of that. Seems like it'd be an easy option to miss, and we won't know the charm is broken until we try to deploy it. Yeah, I'm leaning toward taking out the tactic and making a resource.

**Comment by Cynerva** [comment]
This issue causes a hook failure, by the way, so it's a blocker for kubernetes-master development. @chuckbutler @mbruzek @wwwtyro 

In case somebody needs a quick fix, see https://github.com/Cynerva/kubernetes/commit/0071f7ab7c888c668dc6b8bc94c8a8827209222f which disables `UpdateAddonsTactic` and adds in usable addon definitions directly.

**Comment by Cynerva** [comment]
Here's a branch that removes `UpdateAddonsTactic` and ships addons as a resource instead: [Cynerva:gkk/addons-resource](https://github.com/kubernetes/kubernetes/compare/master...Cynerva:gkk/addons-resource)

More work would be needed to create a jenkins job that produces the addons resource, but I should be able to knock that out quickly if we decide this is the way to go.

@chuckbutler and @mbruzek I'd like to hear your opinions before I take any further action on this issue. Open to ideas!

**Comment by chuckbutler** [comment]
@Cynerva i don't know that we're ready to abandon the add-on tactic just yet...

I think this is simply a case of having landed a broken change in master, and we need to raise awareness that this is a broken change and we should then see if we can't press for having a proper fix vetted in k8s/k8s rather than change our build routine because an add-on manifest was updated.

I imagine if this is broken for us, its broken for everyone

**Comment by Cynerva** [comment]
Ha okay, apologies if I was too gung-ho about this :)

> I think this is simply a case of having landed a broken change in master, and we need to raise awareness that this is a broken change and we should then see if we can't press for having a proper fix vetted in k8s/k8s rather than change our build routine because an add-on manifest was updated.

I disagree. The new addon is broken against the 1.5.2 release, but I don't think it's broken against kubernetes/master builds (though I haven't tested this). I don't it'd be fair of us to ask for cluster/addons on master to always support the latest stable release - it's a development branch, after all.

Perhaps I'm making too many assumptions about a discussion that hasn't occurred yet, but I figure they'll just suggest we grab from an earlier branch. At which point, we'll need more control than `UpdateAddonsTactic` gives us currently.

I'd like to strive for that level of control anyway, to be honest. It doesn't sit well with me that kubernetes-master development is blocked without hacking on the code to make it work.

**Comment by chuckbutler** [comment]
His basically means to me that we should be hacking on the next tagged release or be building against the non 1.5.2 release as that's already cut. Our tests passed it and we should be working on what's next

**Comment by chuckbutler** [comment]
I think i worded it poorly, as i violently agree with what you've said above.

We should have a build from master pushed to edge (or equivalent next branch) and we should be working off that. 

The 1.5.2 is released and in maintenance mode, any new patches would be back ported into a 1.5.x branch in sequence. 

SO, with that being said, +1 to having a more realtime discussion about this and figuring out how we can do this better than we do it today

**Comment by chuckbutler** [comment]
This was fixed with 41251. If you need to set a specific tag for addons, export `KUBE_VERSION` before issuing the build.
