### ISSUE TITLE
option kube-proxy flag --conntrack-max-per-core

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#216]
option kube-proxy flag `--conntrack-max-per-core` support in charm would be good to have, it is specially is needed for web facing apps which use a lot of DNS.

**Comment by chuckbutler** [comment]
I've seen some cases elsewhere, where the conntrack table is filled from horizontally scaled DNS pods + a high volume of requests.  This would be a welcome tunable option.

**Comment by tvansteenburgh** [comment]
This can be set via the `proxy-extra-args` config on the kubernetes-worker charm.
