### ISSUE TITLE
bugs-url of kubernetes core is incorrect

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/bundle-canonical-kubernetes#217]
According to Marco [1](https://github.com/juju-solutions/bundle-kubernetes-core/issues/52#issuecomment-281175983), issues for kubernetes-core bundle should be posted to the CDK bundle. The bugs-url of the kubernetes core bundle in the charm store still points to the bundle-kubernetes-core repo, however.

**Comment by marcoceppi** [comment]
I've updated the bugs url, disabled issues on the old repo and added a deprecation notice. Thanks for the reminder!

**Comment by chuckbutler** [comment]
Thanks marco for following up on this
