### ISSUE TITLE
Automate generation of client certificates.

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/bundle-canonical-kubernetes#218]
I'd like to have an easy way to generate client certificates that a browser can use to connect to the UI. Creating an action to generate client certificates might be a good way to go?

**Comment by chuckbutler** [comment]
@galgalesh - Those client certificates you call out would be used in the `kube proxy` command, not necessarily for client browser sessions as I don't like the idea of polluting the system keychain with self signed certs from K8s. I'm sure other security professionals would agree that this should be isolated to the use cases with kubectl.

But we do need a clean way to generate new client side certs for distribution/deprecation and is a larger bug that needs to be filed/triaged.

I'll leave this issue open as is so we can track progress, but its currently priority: low in terms of this cycle's todo list. I'll be happy to loop you in on any concept work we propose for this feature to ensure we meet your goals with this bug.

**Comment by Cynerva** [comment]
I could've sworn I opened an issue against layer-easyrsa on this. Apparently not, oops!

In case someone finds it helpful, here's a workaround I used when I needed to create server certs manually: [easyrsa-remote.sh](https://gist.github.com/Cynerva/198a11066c47b4bb37bd92be973a8aa9)

I don't know exactly how it would differ for client certs though.

**Comment by galgalesh** [comment]
@chuckbutler - The main reason why I opened the original issue (on the old repo) was to have a way to connect to a Kubernetes cluster from Windows. From what I remember, `kubectl` didn't have official Windows support back then. This has changed since, `kubectl` is now officially supported on Windows so this issue isn't important for my anymore.

Feel free to close it, or keep it open as you wish.

**Comment by chuckbutler** [comment]
Thanks for the update Galgalesh. Closing as your needs have changed.
