### ISSUE TITLE
Kubernetes fail to add external IP in AWS

### ISSUE THREAD

**Issue by tuapuikia** [juju-solutions/bundle-canonical-kubernetes#220]
Not sure this issue have been fixed or not, but when I try to expose port to external. The kubectl get services always show pending.

~/bin/kubectl.conjure-up-canonical-kubernetes-f98 get services
NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
frontend               10.152.183.39    <pending>     80:31488/TCP   11m
kubernetes             10.152.183.1     <none>        443/TCP        33m
redis-master           10.152.183.17    <none>        6379/TCP       11m
redis-slave            10.152.183.157   <none>        6379/TCP       11m

I use the example yaml from https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml

**Comment by chuckbutler** [comment]
Touching this issue, as it can be fixed with some minor documentation. The gist is `kubectl expose` is going to try to route through a LB thats not the ingress controller. It's missing an ingress definition bound to the service object, which would supercede any need to `kubectl expose`.

I'll try to circle back to this today and get something landed in the form of a tutorial.

**Comment by tuapuikia** [comment]
What is the different between conjure-up aws and kops? I can use expose on kops cluster in AWS as it using route 53 for dns registration and cluster discovery.

**Comment by chuckbutler** [comment]
The missing bits here can be resolved with the introduction of the cloud-controller which is landing as beta in 1.7.

Previously this was baked into the controller manager, and you would have to give your cluster an IAM role, and assign that to instances (Juju doesn't have this support currently that I'm aware of). Additionally, the controller manager would have to be configured to talk to your specific cloud.  Neither of the requirements mentioned are implemented in the CDK charms or dependent tooling.

Once CDK gains the capability to communicate with the cloud provider API's it can request the resources it depends on. Until such a time, we recommend you use either ingress rules and leverage the default ingress controller or use NodePort networking.

**Comment by tvansteenburgh** [comment]
This is resolved by the AWS integrator charm (https://jujucharms.com/new/u/containers/aws-integrator), which is deployed automatically by conjure-up.
