### ISSUE TITLE
Backup / restore PKI root certs

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/bundle-canonical-kubernetes#222]
We'd need an ability to export the PKI root from easyrsa - and re-import it. I suggest the following workflow.

```
juju run-action easyrsa/0 backup gpg-key=<key_id>
```
This will create a backup and GPG encrypt that payload which will have the PKI bits inside. The action output will present the user with the SCP command to copy down.

For restoring, the user can decrypt the payload on disk and use

```
juju attach easyrsa pki=backup.tar.xz
```

This will trigger a hook run to unpack the PKI infrastructure then re-generate and redistribute certs to all relations.

This will also provide a path forward to "bring your own PKI"

**Comment by chuckbutler** [comment]
Duplicated by #196

**Comment by chuckbutler** [comment]
Closing this in favor of the duplicated issue.
