### ISSUE TITLE
1.6: Need to set --storage-backend on kube-apiserver

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#225]
In 1.6 they changed the default storage backend to etcd3. We need to continue support for etcd2 in existing deployments.

This is a bit complicated since etcd3 has two distinct datastores for the v2 and v3 APIs. When upgrading from etcd2, we'll need some additional work to migrate the Kubernetes data to the new v3 datastore.

**Comment by mbruzek** [comment]
Good catch @Cynerva! We need to check if any new flags were deprecated or need to be added to our kubernetes services for 1.6. The team has said previously that they can depreciate or introduce new flags on minor releases.

**Comment by chuckbutler** [comment]
@Cynerva i believe this was handled and released with the 1.6.1 update to the charms. Can you confirm and label/close appropriately?

**Comment by Cynerva** [comment]
This was partially handled by hard-coding storage-backend to etcd2: https://github.com/kubernetes/kubernetes/blob/f613e66ad6cc69508419a9b78d72e99f3268772e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L736

There is a bigger fix needed in order to properly support etcd3. I will open a new issue for that.
