### ISSUE TITLE
"Error from server (BadRequest): Upgrade request required" using kubectl exec

### ISSUE THREAD

**Issue by Eblazquez** [juju-solutions/bundle-canonical-kubernetes#226]
Hi, I've just installed the Canonical distribution of Kubernetes (version #20) on Ubuntu 16.04 with conjure-up (version 2.1.0) using the localhost LXD provider. On a clean installation, when performing a "kubectl exec ..." command the result is "Error from server (BadRequest): Upgrade request required", no matter what command I try to execute. Could it be a bug on the Juju bundle?

**Comment by mbruzek** [comment]
Hello @Eblazquez and thank you for the bug report. I am sincerely sorry you encountered this problem with the exec command. We do already have a issue #201 that deals with this issue. We are working on the solution right now, but I don't know exactly when we will have it done. Take a look at issue #201 and add any additional information to that one. Thanks!

**Comment by mbruzek** [comment]
@Eblazquez I have submitted a pull request upstream that in my testing resolves this issue: https://github.com/kubernetes/kubernetes/pull/43625  Please check it out and comment on the PR if you have any feedback.

**Comment by Eblazquez** [comment]
@mbruzek Hi, I just reinstalled the Canonical distribution of Kubernetes and applied the changes you performed on your PR, and it seems to solve the issue indeed. I'll now comment on the PR.
