### ISSUE TITLE
Include cifs-utils when on Azure

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/bundle-canonical-kubernetes#227]
See also: https://github.com/kubernetes/minikube/issues/1197

**Comment by chuckbutler** [comment]
I think it's safe to include this on all clouds, but feel free to object. CIFS seems like it would have a positive impact in more environments, such as on-prem for those old samba servers warehousing data.

**Comment by marcoceppi** [comment]
:+1: let's include out of the box everywhere
