### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pierreozoux** [juju-solutions/bundle-canonical-kubernetes#235]
Your repo is missing a license file, so it means it is proprietary.

(Or did I miss something?)

Thanks to clarify.

**Comment by chuckbutler** [comment]
AH no, we are ASL 2.0 compliant.

cc @mbruzek @marcoceppi  - correct me if i'm wrong here, but I'm fairly certain when we signed up to be contributors to the upstream kubernetes project, we adopted the ASL 2.0 license across the board on all the components.

**Comment by marcoceppi** [comment]
This doesn't necessarily fall under that purview (since it's not directly /in/ upstream). However, as product manager, these files and all associated assets for CDK should be licensed Apache 2. I'll work to make sure the repository is updated to reflect that.
