### ISSUE TITLE
showing only 1 worker node - vsphere

### ISSUE THREAD

**Issue by djmoky83** [juju-solutions/bundle-canonical-kubernetes#237]
after all units are up, accessing both kubectl and dashboard and both are showing only 1 node is available.

juju status is showing 3 worker nodes.

**Comment by mbruzek** [comment]
@djmoky83 I am sorry you are having this problem. I have not seen this problem before, but it looks like a networking issue if the nodes are deployed but not showing up in kubectl.  

We need more information to help. Can you tell us what bundle you deployed, how you deployed, and other relevant information about your vsphere setup?

**Comment by djmoky83** [comment]
Hi, thanks for the reply. Below are the steps i took.

juju version: 2.1.1-xenial-amd64

1. I followed the guide here (https://jujucharms.com/docs/2.1/help-vmware) to bootstrap a vsphere environment.
  a. My vsphere environment is as follows:
    - Single vSphere ESXi 5.5 host
    - vCenter 5.5
    - vSwitch for all the creation of VMs/units
    - I also tried with a full setup of vSphere 6.5 and vCenter 6.5 and the results are the same. 

2. Then following https://jujucharms.com/canonical-kubernetes/
  a. conjure is always hanging, hence i used juju deploy
  b. Orchestration of the VMs are all working fine, screenshot of juju status as below
![juju_status](https://cloud.githubusercontent.com/assets/4156318/23984053/610d4f5c-0a52-11e7-8204-c3bd4e7ca807.png)
  c. This is the cluster-info
`
Kubernetes master is running at https://172.18.12.160:443
Heapster is running at https://172.18.12.160:443/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://172.18.12.160:443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://172.18.12.160:443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://172.18.12.160:443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://172.18.12.160:443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
`
  d. And finally get nodes, and only 1 is showing.
![get_nodes](https://cloud.githubusercontent.com/assets/4156318/23983980/009bc40a-0a52-11e7-8458-2a17cc7260c5.png)
![kubedash_nodes](https://cloud.githubusercontent.com/assets/4156318/23984010/2a866036-0a52-11e7-9d55-aa73ec018018.png)

3. If there is anymore information you need, please inform me and i will try to provide with the best of my limited knowledge.

Thanks!

**Comment by mbruzek** [comment]
@djmoky83 Thanks for the additional information. It is fine that you deployed canonical-kubernetes with juju the conjure-up deployment method is simply another way to do it.  So the cluster looks OK from the Juju perspective which is good. 

It seems strange that the name of this node is "ubuntuguest" if Juju provisioned the systems I would have expected the names would be more unique with numbers to distinguish one kubernetes-worker from another. Can you tell me which of the kubernetes-worker system's IP address maps to "ubuntuguest" on your network? Was there any network configuration done to these machines outside of Juju?

Regarding this stixadmin system. I suspect that you have multiple kubeconfig files (check .kube/config) on your system from past cluster bring up and it may be pointing at an old cluster. Can you run a `kubectl config view` command and put the output in the issue? The config on this system may not be pointing to the same or correct address. It would be interesting if you could `juju ssh kubernetes-worker/0` and run `kubectl get nodes` on that system rather than stixadmin.

If it is a configuration file mixup please ensure you downloaded the package from the kubernetes-master that is in your current running cluster. 

If it is not a configuration mixup then I would request the following actions be run:
```
juju run-action kubernetes-master/0 debug
juju show-action-output --wait=0 def5cb5e-02de-47f6-8301-39bb931a4148    # Your uuid will be different, from the run-action subcommand.
 juju scp kubernetes-master/0:/home/ubuntu/debug-20170316153603.tar.gz .   # Your timestamp will also be different, from the show-action-output command.
```
And please attach that to this bug.

**Comment by marcoceppi** [comment]
I have a feeling this is the DNS issue biting again. @djmoky83 can you run the following as well:

```
juju run --applicaiton kubernetes-worker "hostname -f"
```
and report the output?

**Comment by djmoky83** [comment]
@mbruzek sorry i tore down the cluster used for the screenshots. However i re-up a new cluster and have updated the post with the latest ip address.

Now to answer your questions:

- ubuntuguest has an ip address of 172.18.12.165 which belongs to kubernetes-worker/0
- No network config was done to any of the servers,
- The kube config is correct, and it is pointing to the load balancer ip address
![kube_config](https://cloud.githubusercontent.com/assets/4156318/24027088/fe17d954-0aff-11e7-97cc-db7bc5207ac1.png)
- ssh into worker/0 and the get nodes results as screenshot
![worker0_get_nodes](https://cloud.githubusercontent.com/assets/4156318/24027129/3a63e6e6-0b00-11e7-8400-a803539ca007.png)
- assure you that there are no config mixed up, this is because at any point, only 1 cluster of kubernetes is up.
- and as requested, the debug log as attached.
[debug-20170317025701.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/849534/debug-20170317025701.tar.gz)

**Comment by djmoky83** [comment]
@marcoceppi as instructed, below is the output.

![hostname](https://cloud.githubusercontent.com/assets/4156318/24027308/7bc359f4-0b01-11e7-9b5a-219dfcbaa998.png)

**Comment by marcoceppi** [comment]
Yeah, I suspected that was the problem. We've noticed this in another VMWare setup. The machines all come up with "ubuntuguest" as the hostname. Kubernetes uses the hostname to map node names in Kubernetes. So each new worker registers as ubuntuguest and thats why only one of the three shows up.

@chuckbutler @Cynerva @wwwtyro How did we get around this for the VMWare Q/A Lab?

**Comment by chuckbutler** [comment]
It's still being worked on. Xref with the launchpad bug https://bugs.launchpad.net/juju/+bug/1669072

**Comment by djmoky83** [comment]
Thanks all for the help.

Think for now we have to wait for the proper fix from juju itself.

However i tried changing the hostname manually for now and it is working fine.

**Comment by chuckbutler** [comment]
Thanks for validating our assertions @djmoky83.  We did manual workarounds in initial testing and it yielded a similar result. Once this fix lands in juju proper we should be unblocked here. I'll leave this open to track progress with regard to CDK on Vsphere.

**Comment by chuckbutler** [comment]
@djmoky83 i took a stab at resolving this in the charm as a patch until we can get the juju-core fixes landed, which will be decidedly much later than we can land this charm patch.
