### ISSUE TITLE
coreDNS support

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#243]
optional kube-dns replacement with coreDNS

**Comment by chuckbutler** [comment]
@ktsakalozos Is this getting addressed with the fed work that's been incoming? I believe you have successfully replaced kube-dns with coredns in that branch. I'll assign to you for now and feel free to update as required.

**Comment by drewboswell** [comment]
Any news? As of v.1.12 it is the recommended dns provider.

**Comment by Cynerva** [comment]
No concrete plans at the moment. We are preparing a roadmap for the next few months that is likely to include replacing kube-dns with coreDNS by default, but no promises yet.

**Comment by strainovic** [comment]
Any news about CoreDNS support?

**Comment by tvansteenburgh** [comment]
@strainovic Hi! Yes, thanks for asking - it's on our short-term roadmap. Goal is to have it be the default in CDK for the 1.14 release.

**Comment by strainovic** [comment]
@tvansteenburgh Thank you for information. I hoped it will be included in 1.13 as Kubernetes sets it as default dns provider.

Keep up good work!

**Comment by lopf** [comment]
Will you provide a migration path for existing deployments?

**Comment by Cynerva** [comment]
> Will you provide a migration path for existing deployments?

Yes.

> When can we expect 1.14 to be released? Thanks

The Kubernetes 1.14.0 release is scheduled for release on March 25 ([source](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14)). We will aim to release CDK support for Kubernetes 1.14 within a week after that, so hopefully around April 1, give or take a few days.

**Comment by tvansteenburgh** [comment]
This was released with CDK 1.14 a couple days ago. From the [release notes](https://www.ubuntu.com/kubernetes/docs/release-notes):

> All new deployments of CDK 1.14 will install CoreDNS 1.4.0 by default instead of KubeDNS.
> 
> Existing deployments that are upgraded to CDK 1.14 will continue to use KubeDNS until the operator chooses to upgrade to CoreDNS. See the [upgrade notes](https://www.ubuntu.com/kubernetes/docs/upgrade-notes) for details.
