### ISSUE TITLE
Containers are provided with a ServiceAccount token with privileged access to the API server

### ISSUE THREAD

**Issue by raesene** [juju-solutions/bundle-canonical-kubernetes#246]
Currently by default, containers deployed to clusters get a serviceaccount token when they're created, that has cluster admin rights.

This means that a rogue container can execute API commands against the k8s API server and likely escalate privileges on the hosts running the cluster.

As described in [this documentation](https://kubernetes.io/docs/admin/service-accounts-admin/), when a pod is created the AdmissionController will assign the default ServiceAccount token to the pod.

This means that  when a new pod is launched there's a token file created in `/var/run/secrets/kubernetes.io/serviceaccount/`  which has cluster admin rights.

To test, start a pod, exec into it, get a copy of kubectl and point it at the API server for the cluster.  You should be able to execute commands against it.

The fix for this should be to use [RBAC](https://kubernetes.io/docs/admin/authorization/rbac/) with Kubernetes 1.6 as the default RBAC configuration doesn't provide this token access unless the pod is being deployed to the kube-system namespace.

**Comment by chuckbutler** [comment]
RBAC is such a new feature that we're still evaluating it and had plans on supporting it sometime post launch of our 1.6 release.

I've tagged this bug as a security issue so it gets the proper attention however, I don't see a fast/immediate fix on the horizon pending us supporting RBAC in the charms.

**Comment by chuckbutler** [comment]
xlink with #289

**Comment by tvansteenburgh** [comment]
RBAC support was included with the 1.8 version of the bundle. More info here: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Authorization-Mode-and-RBAC
