### ISSUE TITLE
Inaccurate deployment command.

### ISSUE THREAD

**Issue by burton-swan** [juju-solutions/bundle-canonical-kubernetes#251]
On kubernetes-e2e charm store page, it indicates:

juju deploy kubernetes-e2e

However this command will trigger following error:
$ juju deploy kubernetes-e2e
ERROR cannot resolve URL "cs:kubernetes-e2e": charm or bundle not found

It has to be run in full path, e.g.:
$ juju deploy cs:~containers/kubernetes-e2e-9
Located charm "cs:~containers/kubernetes-e2e-9".
Deploying charm "cs:~containers/kubernetes-e2e-9".

Juju version here is 2.2-beta1-xenial-amd64.

I guess it's because kubernetes-e2e is under the containers, which will result a URL resolve error in juju deploy command.

**Comment by mbruzek** [comment]
Hi @burton-swan thanks for the bug report. You are correct those are the wrong commands and we will fix this as soon as possible.

**Comment by burton-swan** [comment]
The description on kubernetes-e2e charm page still hasn't changed yet - at "Usage" section:
https://jujucharms.com/u/containers/kubernetes-e2e/

**Comment by chuckbutler** [comment]
Thank you for keeping up with this issue @burton-swan.

I've released a fresh build of e2e to the candidate channel here: https://jujucharms.com/u/containers/kubernetes-e2e/13

The readme changes are reflected and once we've used this release as validation for the upcoming 1.6.2 release I'll be happy to bump this into the stable channel.
