### ISSUE TITLE
kubefed is not available after deployment

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#252]
The client for federation ops is not available after deployment of the bundle. It should eb next to kubectl probably needs to be snapped

**Comment by ktsakalozos** [comment]
This PR should package the kubefed snap: https://github.com/juju-solutions/release/pull/2

**Comment by marcoceppi** [comment]
Should kubefed be its own charm?

**Comment by ktsakalozos** [comment]
The kubefed is just a client that you need to have locally. I am not sure how a charm would work towards this goal. Overall I feel that in an HA federated setup you would need to have extra charms to form a reliable DNS.

**Comment by chuckbutler** [comment]
Related to #210

**Comment by ktsakalozos** [comment]
kubefed client is now installed next to kubectl. Enjoy!
