### ISSUE TITLE
One or more component charm/resource cannot be retrieved in bundle deployment.

### ISSUE THREAD

**Issue by burton-swan** [juju-solutions/bundle-canonical-kubernetes#253]
For canonical-kubernetes bundle deployment - juju deploy canonical-kubernetes, sometimes a component charm, or resource of a charm failed to be downloaded. It happened on both local LXD and AWS deployment. This issue may cause unexpected error in automation test, the deployment failure may terminate the entire CI job.

A work-around can be:
Deploy all component charm individually, then at the end run juju deploy canonical-kubernetes. If there is a download/resource fetch error in individual charm deployment, re-run the command several times before give up.

It would be neat if there is a way to solve this issue from the root cause. Also found this description in "Known Limitations and Issues" section on canonical-kubernetes charm page, not sure if this issue here is duplicate to another one:
If resources fail to download during initial deployment for any reason, you will need to download and install them manually.

Following output is from several attempts I tried:
$ juju deploy cs:bundle/canonical-kubernetes-21
Located bundle "cs:bundle/canonical-kubernetes-21"
Deploying charm "cs:~containers/easyrsa-7"
added resource easyrsa
ERROR cannot deploy bundle: cannot get resource metadata from the charm store: Get https://api.jujucharms.com/charmstore/v5/~containers/etcd-24/meta/resources: dial tcp 162.213.33.121:443: getsockopt: connection timed out

$ juju deploy cs:bundle/canonical-kubernetes-21
Located bundle "cs:bundle/canonical-kubernetes-21"
ERROR cannot deploy bundle: cannot add charm "cs:~containers/easyrsa-7": cannot retrieve charm "cs:~containers/easyrsa-7": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/~containers/easyrsa-7/archive?channel=stable: dial tcp 162.213.33.122:443: getsockopt: connection timed out

$ juju deploy canonical-kubernetes
Located bundle "cs:bundle/canonical-kubernetes-21"
Deploying charm "cs:~containers/easyrsa-7"
added resource easyrsa
Deploying charm "cs:~containers/etcd-24"
added resource snapshot
Deploying charm "cs:~containers/flannel-11"
added resource flannel
ERROR cannot deploy bundle: cannot resolve URL "cs:~containers/kubeapi-load-balancer-7": cannot resolve charm URL "cs:~containers/xenial/kubeapi-load-balancer-7": cannot get "/~containers/xenial/kubeapi-load-balancer-7/meta/any?include=id&include=supported-series&include=published": Get https://api.jujucharms.com/charmstore/v5/~containers/xenial/kubeapi-load-balancer-7/meta/any?include=id&include=supported-series&include=published: dial tcp 162.213.33.121:443: getsockopt: connection timed out

$ juju deploy canonical-kubernetes
ERROR cannot retrieve bundle "cs:bundle/canonical-kubernetes-21": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/bundle/canonical-kubernetes-21/archive: dial tcp 162.213.33.122:443: getsockopt: connection timed out

**Comment by marcoceppi** [comment]
In the release coming later this week we shift from resources to snaps as
delivery which should address this issue indirectly.

**Comment by chuckbutler** [comment]
@burton-swan we've released the 1.6.1 charms which now shift the majority of componentry to snaps. Can you give this a re-test and see if this resolves your issues with the resource fetch?

**Comment by chuckbutler** [comment]
I'm going to close this issue for now. If it continues to be an issue, please feel free to respond and we'll re-open and re-evaluate at that time.

**Comment by burton-swan** [comment]
Validated, now the canonical-kubernetes bundle can be deployed without download or resources fetching error, on local LXD, AWS and vSphere.
