### ISSUE TITLE
juju names not resolveable

### ISSUE THREAD

**Issue by spunkedy** [juju-solutions/bundle-canonical-kubernetes#260]
with openstack:

doing:
`juju deploy canonical-kubernete`

`juju scp kubernetes-master/0:config ~/.kube/config`

```
kubectl get nodes                                                                                                                            ✓  6529  19:45:10
NAME                    STATUS    AGE
juju-a2b7e2-default-6   Ready     26m
juju-a2b7e2-default-7   Ready     19m
juju-a2b7e2-default-8   Ready     27m
```

those names are not resolve-able because they are inside openstack. Is there a way to have the cluster specify the floating ips?

**Comment by marcoceppi** [comment]
Kubernetes expects hostnames to be resolvable. While the majority of
Kubernetes works without this, some things like kubectl exec and kubectl
logs won't.

This is an issue with Juju not providing a means consistently rely on
hostnames

**Comment by spunkedy** [comment]
I just noticed that there is a designate charm now. I will give that a try and see how it goes.

If this is working as expected we can just close it then. I figured it was just an issue that the were was a magic way to tell the charm to use the ip instead of name.
