### ISSUE TITLE
Missing support for etcd3 data store

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#264]
Right now we have storage-backend hard-coded to etcd2: https://github.com/kubernetes/kubernetes/blob/f613e66ad6cc69508419a9b78d72e99f3268772e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L736

While this does work with etcd3, it doesn't utilize the new data store that comes with it. Ideally we should support etcd3 proper without falling back to the old data store.

This will be hard to handle correctly, since migrating data from etcd2 to etcd3 isn't currently handled by Kubernetes, nor am I aware of any upstream recommendations on how to do so.

**Comment by tvansteenburgh** [comment]
@Cynerva Is there a reason why these steps wouldn't work for us? https://coreos.com/blog/migrating-applications-etcd-v3.html

**Comment by Cynerva** [comment]
Seems like it might work. After migrating etcd to the 3.1/stable channel, I tried this:

```
juju run --application kubernetes-master 'service snap.kube-apiserver.daemon stop'
juju run --application etcd 'service snap.etcd.etcd stop'
juju run --application etcd 'ETCDCTL_API=3 /snap/bin/etcdctl migrate --data-dir=/var/snap/etcd/current/etcd0.etcd'
juju run --application etcd 'service snap.etcd.etcd start'
juju run --application kubernetes-master 'snap set kube-apiserver storage-backend=etcd3'
juju run --application kubernetes-master 'service snap.kube-apiserver.daemon start'
```

The cluster seems to be in a good state, and I'm not noticing any obvious data loss. However, looking at the upstream [migrate-if-needed.sh](https://github.com/kubernetes/kubernetes/blob/a7d2136ce14f3c9576209860c39a964430607ec9/cluster/images/etcd/migrate-if-needed.sh#L200-L214) script, there's some extra TTL/lease stuff they do after the migration. We might need to do that too, dunno.

**Comment by tvansteenburgh** [comment]
etcd3 support was added with CDK 1.10 and included [instructions](https://www.ubuntu.com/kubernetes/docs/upgrade-notes) for upgrading from etcd2.
