### ISSUE TITLE
kubernetes-core bundle broken using Juju 2.1.2 when spaces constraints are used 

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/bundle-canonical-kubernetes#265]
Juju 2.1.2 introduced the inheriting of constraints by lxd, so if you supply a spaces constraint for the instance which the lxd easyrsa lands on, the easyrsa lxd will inherit the constraint, not be able to reach the space, and then fail to deploy.

To reproduce this:
```bash
juju add-space lxd-fail-space

juju add-subnet subnet-<id> lxd-fail-space

juju deploy etcd --constraints "spaces=lxd-fail-space" # gets machine id 0

juju deploy easyrsa --to lxd:0 

```

**Comment by chuckbutler** [comment]
Thanks for filing this @jamesbeedy. This is known behavior to us unfortunately, as we have not updated the charms yet for 'network-get' style networking and the charms still primarily rely on the older style of network function.  Eg (`unit-get public-address`)

I wouldn't expect any of the charms contained in the CDK bundle to work in spaces until the network code has been updated to respect the spaces-aware network-get command.

**Comment by jamesbeedy** [comment]
@chuckbutler I see, thanks for that. I was thinking it is related to this bug though https://bugs.launchpad.net/juju/+bug/1685782 ....

**Comment by chuckbutler** [comment]
That does seem to be the crux, but there are additional dragons in there you haven't uncovered yet due to that bug.

**Comment by marcoceppi** [comment]
network get is really only for extra bindings. You can always define
bindings on relationships and juju will manage private-address for you.

**Comment by chuckbutler** [comment]
@marcoceppi so does that mean when using space-bound constraints, the unit-get command gets some magic behavior to return the space binding? and this is not something we need to be concerned with?

**Comment by chuckbutler** [comment]
@jamesbeedy the upstream bug has been fix-released. Can you verify this issue has been corrected for you with that patch?

**Comment by jamesbeedy** [comment]
Verified! Thanks!
