### ISSUE TITLE
GPU workers don't need priviledged containers

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#277]
With 1.6, GPU workloads no longer require priv containers. However, we should also take this time to improve visibility of what version of libraries are added, etc.

In the status message:

```
Kubernetes worker running (cuda VERSION)
```

We should also start applying more labels for workers, including a GPU flag, cuda drivers/version, etc.

**Comment by chuckbutler** [comment]
as an update to this issue, we are applying cuda=true and gpu=true. There's room for improvement with the cuda version.

**Comment by ktsakalozos** [comment]
We do not require privileged containers for GPU support anymore.
