### ISSUE TITLE
kubernetes.io/rbd provisioner claims fail

### ISSUE THREAD

**Issue by roll4life** [juju-solutions/bundle-canonical-kubernetes#278]
in CDK 1.6.2 I am unable to make persistent volume claims against the rbd provisioner
the claims stay in a pending state  
kubectl describe pvc
```
Name:		mypvc
Namespace:	default
StorageClass:	fast
Status:		Pending
Volume:		
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:	
Access Modes:	
Events:		<none
```
journalctl | grep rbd shows the following log entries

```
May 05 18:21:43 juju-72926f-default-5 snap[516]: I0505 18:21:43.353205     516 wrap.go:75] POST /api/v1/namespaces/default/persistentvolumeclaims: (23.11892ms) 201 [[kubectl/v1.6.2 (darwin/amd64) kubernetes/477efc3] 192.168.28.16:54853]
May 05 18:21:43 juju-72926f-default-5 snap[516]: I0505 18:21:43.374445     516 wrap.go:75] PUT /api/v1/namespaces/default/persistentvolumeclaims/mypvc: (15.048984ms) 200 [[kube-controller-manager/v1.6.2 (linux/amd64) kubernetes/477efc3/persistent-volume-binder] 127.0.0.1:44122]
May 05 18:21:43 juju-72926f-default-5 snap[516]: I0505 18:21:43.377369     516 wrap.go:75] GET /api/v1/persistentvolumes/pvc-b0d604b1-31bf-11e7-850d-fa163efc6bad: (1.344367ms) 404 [[kube-controller-manager/v1.6.2 (linux/amd64) kubernetes/477efc3/persistent-volume-binder] 127.0.0.1:44122]
May 05 18:21:43 juju-72926f-default-5 snap[516]: I0505 18:21:43.380432     516 wrap.go:75] GET /api/v1/namespaces/default/secrets/ceph-secret-admin: (2.014332ms) 200 [[kube-controller-manager/v1.6.2 (linux/amd64) kubernetes/477efc3/persistent-volume-binder] 127.0.0.1:44122]
May 05 18:21:43 juju-72926f-default-5 audit[15190]: AVC apparmor="DENIED" operation="open" profile="snap.kube-controller-manager.daemon" name="/var/tmp/" pid=15190 comm="rbd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 05 18:21:43 juju-72926f-default-5 kernel: audit_printk_skb: 15 callbacks suppressed
May 05 18:21:43 juju-72926f-default-5 kernel: audit: type=1400 audit(1494008503.415:3621): apparmor="DENIED" operation="open" profile="snap.kube-controller-manager.daemon" name="/var/tmp/" pid=15190 comm="rbd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

This is occurring when cdk has been deployed to openstack and the PV claim is being made against a ceph cluster that is at the layer as openstack.

Static claims work just fine.

**Comment by chuckbutler** [comment]
Thanks for filing this bug @roll4life.  I appreciate the detailed logs attached.

This is due to the rbd bin being included in the kube-controller-manager snap not having access to do what it needs to do in order to provision that volume.

I think we need to take this to the snappy team and see about what slots/plugs we can consume or if there's one that we need to have written. The AppArmor policy is just too restrictive for this to ever work how we expect it to.

The static enlistment is being done by an rbd bin outside of the snaps, which is why this works as we would expect.

cc @marcoceppi @Cynerva and @wwwtyro 

Lets circle back to this on Monday when we're back in office and can dedicate some time investigating our options here.

**Comment by marcoceppi** [comment]
As a work around, though temporary, you can remove the confinement from that snap. `juju ssh kubernetes-master/0` once on the unit:

```
sudo snap install kube-controller-manager --devmode --force
```

The above command is from memory, you may need to use refresh instead of install.

**Comment by roll4life** [comment]
@marcoceppi tried that but I am still getting the error
Here are the commands that I ran and their corresponding output
```
sudo snap install kube-controller-manager --devmode --force
error: unknown flag `force'

sudo snap install kube-controller-manager --devmode
snap "kube-controller-manager" is already installed, see "snap refresh --help"

sudo snap refresh kube-controller-manager --devmode --force
error: unknown flag `force'

sudo snap refresh kube-controller-manager --devmode
snap "kube-controller-manager" has no updates available
```

Is there a way to display the confinement mode so that I can be certain that devmode has been applied?

**Comment by marcoceppi** [comment]
You should see it with `snap list`. I'm not near a computer but I'll verify
the command in a few hours.

**Comment by roll4life** [comment]
```
snap list --all
Name                     Version  Rev   Developer  Notes
cdk-addons               1.6.2    21    canonical  -
core                     16-2     1689  canonical  -
kube-apiserver           1.6.2    27    canonical  -
kube-controller-manager  1.6.2    18    canonical  -
kube-scheduler           1.6.2    27    canonical  -
kubectl                  1.6.2    27    canonical  classic
```

**Comment by roll4life** [comment]
Is there any other information that you would like me to provide at this time?

**Comment by chuckbutler** [comment]
@roll4life not at this time. we've not had a chance to circle back but we've got this as pretty high in the list of bugs to investigate on our next bug-fixing cycle. Thank you for your continued patience here.

**Comment by Cynerva** [comment]
I wasn't able to reproduce this with CDK 1.6.2 on AWS. Here's what I did:

1. Deployed and related kubernetes-core, ceph-mon, and ceph-osd with EBS storage:

```
Model    Controller  Cloud/Region   Version
default  aws-dev     aws/us-east-1  2.1.2

App                Version  Status  Scale  Charm              Store       Rev  OS      Notes
ceph-mon           10.2.7   active      3  ceph-mon           jujucharms    9  ubuntu
ceph-osd           10.2.7   active      3  ceph-osd           jujucharms  241  ubuntu
easyrsa            3.0.1    active      1  easyrsa            jujucharms    9  ubuntu
etcd               2.3.8    active      1  etcd               jujucharms   34  ubuntu
flannel            0.7.0    active      2  flannel            jujucharms   15  ubuntu
kubernetes-master  1.6.2    active      1  kubernetes-master  jujucharms   19  ubuntu  exposed
kubernetes-worker  1.6.2    active      1  kubernetes-worker  jujucharms   23  ubuntu  exposed

Unit                  Workload  Agent  Machine  Public address  Ports           Message
ceph-mon/0            active    idle   0        54.196.17.113                   Unit is ready and clustered
ceph-mon/1*           active    idle   1        54.157.215.165                  Unit is ready and clustered
ceph-mon/2            active    idle   2        52.23.218.51                    Unit is ready and clustered
ceph-osd/0*           active    idle   5        54.91.11.70                     Unit is ready (1 OSD)
ceph-osd/1            active    idle   6        54.175.252.30                   Unit is ready (1 OSD)
ceph-osd/2            active    idle   7        54.173.252.223                  Unit is ready (1 OSD)
easyrsa/0*            active    idle   3/lxd/0  10.0.173.23                     Certificate Authority connected.
etcd/0*               active    idle   3        54.85.24.167    2379/tcp        Healthy with 1 known peer
kubernetes-master/0*  active    idle   3        54.85.24.167    6443/tcp        Kubernetes master running.
  flannel/0*          active    idle            54.85.24.167                    Flannel subnet 10.1.38.1/24
kubernetes-worker/0*  active    idle   4        52.207.253.28   80/tcp,443/tcp  Kubernetes worker running.
  flannel/1           active    idle            52.207.253.28                   Flannel subnet 10.1.15.1/24

Machine  State    DNS             Inst id              Series  AZ
0        started  54.196.17.113   i-0372584dff3e6454e  xenial  us-east-1b
1        started  54.157.215.165  i-00e4a4c6c4c481500  xenial  us-east-1c
2        started  52.23.218.51    i-05b54c5c8baeeb31c  xenial  us-east-1d
3        started  54.85.24.167    i-0982c06656e72fb83  xenial  us-east-1e
3/lxd/0  started  10.0.173.23     juju-4a3db3-3-lxd-0  xenial
4        started  52.207.253.28   i-005610782a5441341  xenial  us-east-1b
5        started  54.91.11.70     i-07afb075c88fd8d59  xenial  us-east-1c
6        started  54.175.252.30   i-0171114d2d2b573ad  xenial  us-east-1b
7        started  54.173.252.223  i-09115290f3baed6dc  xenial  us-east-1d

Relation      Provides           Consumes           Type
mon           ceph-mon           ceph-mon           peer
mon           ceph-mon           ceph-osd           regular
ceph-storage  ceph-mon           kubernetes-master  regular
certificates  easyrsa            etcd               regular
certificates  easyrsa            kubernetes-master  regular
certificates  easyrsa            kubernetes-worker  regular
cluster       etcd               etcd               peer
etcd          etcd               flannel            regular
etcd          etcd               kubernetes-master  regular
cni           flannel            kubernetes-master  regular
cni           flannel            kubernetes-worker  regular
cni           kubernetes-master  flannel            subordinate
kube-control  kubernetes-master  kubernetes-worker  regular
cni           kubernetes-worker  flannel            subordinate
```

2. Created a StorageClass named `rbd`:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.31.49.213:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
```

3. Created a PersistentVolumeClaim named `testclaim`:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: rbd
```

4. Observed the PVC successfully reached `Bound` status:
```
Name:		testclaim
Namespace:	default
StorageClass:	rbd
Status:		Bound
Volume:		pvc-004d5ab9-3be5-11e7-9315-06c807027e92
Labels:		<none>
Annotations:	pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:	500Mi
Access Modes:	RWO
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  7s		7s		1	persistentvolume-controller			Normal		ProvisioningSucceeded	Successfully provisioned volume pvc-004d5ab9-3be5-11e7-9315-06c807027e92 using kubernetes.io/rbd
```

I also created a pod using this PVC and was able to write to the mount, recreate the pod, and see that the data persisted as it should.

On kubernetes-master/0, I do see the read denied to /var/tmp:

```
AVC apparmor="DENIED" operation="open" profile="snap.kube-controller-manager.daemon" name="/var/tmp/" pid=27650 comm="rbd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

but it doesn't seem to be causing problems for me.

**Comment by Cynerva** [comment]
@roll4life Since I wasn't able to reproduce this issue, I do have a couple follow-up questions for you:
1. Do you see anything I did differently, or incorrectly, in my reproduction steps above?
2. Is this a regression? Did it work for you with CDK 1.5.3 and earlier?
3. Can you double-check that your StorageClass is configured with the correct monitor endpoint, secrets, etc?
4. Can you share the output of `journalctl -u snap.kube-controller-manager.daemon` from each of your kubernetes-master units?

Thanks for your patience. Any further information you can provide would be much appreciated.

**Comment by roll4life** [comment]
@Cynerva sorry for the delayed response.  The main difference I see between your enviroment and ours is that your ceph cluster is in the same environment as your kubernetes cluster and there are juju managed relations between ceph and kubernetes.

In our environment there are two separate juju controllers because, if I understand the documentation correctly, juju requires a 1 to 1 relationship between controllers and clouds.
Controller 1 is tied to a MaaS cloud and was used to deploy OpenStack base, ceph-mon, ceph-osd, and ceph-radosgw were deployed as part of this installation.
Controller 2 is tied to the OpenStack cloud mentioned above, CDK was deployed into the OpenStack cloud, and is connecting to the ceph cluster deployed by controller 1.

I am not sure whether it is a regression as CDK 1.6 is the first version we've used.  I would be happy to fire up an instance of CDK 1.5 to test.

I'll double check the secrets etc... I am able to make static claims without any problems, so I think that the secrets and endpoints are ok.

I will provide the rest of the information later in the day.

**Comment by Cynerva** [comment]
@roll4life No problem, thanks for the update.

> The main difference I see between your enviroment and ours is that your ceph cluster is in the same environment as your kubernetes cluster and there are juju managed relations between ceph and kubernetes.

Good point. I don't have ready access to MaaS/OpenStack clouds, but I'll see if I can at least give it another test run across controllers at least.

> I am not sure whether it is a regression as CDK 1.6 is the first version we've used. I would be happy to fire up an instance of CDK 1.5 to test.

I'm not sure if we can actually still deploy CDK 1.5 today, but I'll let you know if I find out :P

> I'll double check the secrets etc... I am able to make static claims without any problems, so I think that the secrets and endpoints are ok.

Thanks. The main reason I asked about this is because I _think_ the `StorageClass` isn't used for static claims, but I could be completely wrong about that. Apologies if that's the case.

**Comment by roll4life** [comment]
@Cynerva things have been a bit crazy lately so I am just getting back to this.
here is what I have done.
1. Deployed CDK
```
Model  Controller           Cloud/Region         Version
k8s    openstack-RegionOne  openstack/RegionOne  2.1.2

App                    Version  Status  Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active      1  easyrsa                jujucharms   12  ubuntu  
etcd                   2.3.8    active      3  etcd                   jujucharms   40  ubuntu  
flannel                0.7.0    active      4  flannel                jujucharms   20  ubuntu  
kubeapi-load-balancer  1.10.3   active      1  kubeapi-load-balancer  jujucharms   16  ubuntu  exposed
kubernetes-master      1.7.0    active      1  kubernetes-master      jujucharms   35  ubuntu  exposed
kubernetes-worker      1.7.0    active      3  kubernetes-worker      jujucharms   40  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports                     Message
easyrsa/0*                active    idle   0        10.148.0.117                              Certificate Authority connected.
etcd/0*                   active    idle   1        10.148.0.121    2379/tcp                  Healthy with 3 known peers
etcd/1                    active    idle   2        10.148.0.109    2379/tcp                  Healthy with 3 known peers
etcd/2                    active    idle   3        10.148.0.107    2379/tcp                  Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   4        10.148.0.102    443/tcp                   Loadbalancer ready.
kubernetes-master/0*      active    idle   5        10.148.0.116    6443/tcp                  Kubernetes master running.
  flannel/3               active    idle            10.148.0.116                              Flannel subnet 10.1.50.1/24
kubernetes-worker/0       active    idle   6        10.148.0.105    80/tcp,443/tcp,10250/tcp  Kubernetes worker running.
  flannel/2               active    idle            10.148.0.105                              Flannel subnet 10.1.96.1/24
kubernetes-worker/1       active    idle   7        10.148.0.114    80/tcp,443/tcp,10250/tcp  Kubernetes worker running.
  flannel/1               active    idle            10.148.0.114                              Flannel subnet 10.1.2.1/24
kubernetes-worker/2*      active    idle   8        10.148.0.128    80/tcp,443/tcp,10250/tcp  Kubernetes worker running.
  flannel/0*              active    idle            10.148.0.128                              Flannel subnet 10.1.22.1/24

Machine  State    DNS           Inst id                               Series  AZ
0        started  10.148.0.117  fb558940-7f1d-47f0-8bf1-a6bc743ea14f  xenial  nova
1        started  10.148.0.121  7c79670e-0d79-4eeb-807a-683bdf000c04  xenial  nova
2        started  10.148.0.109  35918958-787b-47d9-a5b6-0a2c0af78900  xenial  nova
3        started  10.148.0.107  68148aa1-b34e-4b99-a61a-59cef0d3429a  xenial  nova
4        started  10.148.0.102  666e2886-cb0f-4e86-893b-969fe4548460  xenial  nova
5        started  10.148.0.116  e77e4023-1dc4-4d04-b836-ce67151c4896  xenial  nova
6        started  10.148.0.105  df130233-43f6-4a48-a1f8-3ffb617d678c  xenial  nova
7        started  10.148.0.114  5fa851a1-78ca-4320-9415-f6108533d92b  xenial  nova
8        started  10.148.0.128  4cc2d7da-f02e-4444-94db-bf835a1c7820  xenial  nova

Relation           Provides               Consumes               Type
certificates       easyrsa                etcd                   regular
certificates       easyrsa                kubeapi-load-balancer  regular
certificates       easyrsa                kubernetes-master      regular
certificates       easyrsa                kubernetes-worker      regular
cluster            etcd                   etcd                   peer
etcd               etcd                   flannel                regular
etcd               etcd                   kubernetes-master      regular
cni                flannel                kubernetes-master      regular
cni                flannel                kubernetes-worker      regular
loadbalancer       kubeapi-load-balancer  kubernetes-master      regular
kube-api-endpoint  kubeapi-load-balancer  kubernetes-worker      regular
cni                kubernetes-master      flannel                subordinate
kube-control       kubernetes-master      kubernetes-worker      regular
cni                kubernetes-worker      flannel                subordinate
```
2. Created a StorageClass named `rbd`:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rbd
provisioner: kubernetes.io/rbd
parameters:
    monitors: 10.115.0.15:6789,10.115.0.16:6789,10.115.0.17:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: default
    pool: k8s
    userId: admin
    userSecretName: ceph-secret-admin
```
3. Created a PersistentVolumeClaim named `mypvc`:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: rbd
```
4. Observe pvc status pending
```
Name:		mypvc
Namespace:	default
StorageClass:	rbd
Status:		Pending
Volume:
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:
Access Modes:
Events:		<none>
``` 

> Can you double-check that your StorageClass is configured with the correct monitor endpoint, secrets, etc?

I am using the same monitor endpoints for persistent volume static claims that I am using for the StorageClass.  Unless I am missing something, I believe that the ceph monitors and ceph-admin-secret should work both for static claims and storage provisioner claims.
here is an example of a working static volume and the corresponding claim
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - 10.115.0.15:6789
      - 10.115.0.16:6789
      - 10.115.0.17:6789
    pool: k8s
    image: gitlab
    user: admin
    secretRef:
      name: ceph-admin-secret
    fsType: ext4
    readOnly: false
```
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
```

> Can you share the output of `journalctl -u snap.kube-controller-manager.daemon` from each of your kubernetes-master units?

there are no entries in the logs when the storage class is created and the claim is made

If I perform a static claim, I see the following
```
Jul 19 16:44:11 juju-4aeefe-k8s-5 snap[8264]: I0719 16:44:11.549396    8264 pv_controller.go:718] volume "ceph-pv" entered phase "Available"
Jul 19 16:44:19 juju-4aeefe-k8s-5 snap[8264]: I0719 16:44:19.420109    8264 pv_controller.go:792] claim "default/ceph-claim" bound to volume "ceph-pv"
Jul 19 16:44:19 juju-4aeefe-k8s-5 snap[8264]: I0719 16:44:19.456974    8264 pv_controller.go:718] volume "ceph-pv" entered phase "Bound"
Jul 19 16:44:19 juju-4aeefe-k8s-5 snap[8264]: I0719 16:44:19.457083    8264 pv_controller.go:853] volume "ceph-pv" bound to claim "default/ceph-claim"
Jul 19 16:44:19 juju-4aeefe-k8s-5 snap[8264]: I0719 16:44:19.487162    8264 pv_controller.go:654] claim "default/ceph-claim" entered phase "Bound"
```

**Comment by Cynerva** [comment]
Thanks for the update @roll4life 

I see `ceph-secret-admin` in your StorageClass, vs. `ceph-admin-secret` in your static claim. Is there a difference between those? I'm guessing that's not the cause of the issue but want to make sure.

A couple quick observations about things we did different:
1. My StorageClass only specified one of the three monitor endpoints. Yours has all three.
2. My PVC was 500Mi, vs. your 15Gi
3. As you mentioned before, I was on AWS and had ceph deployed and related in the same model.

None of these stand out as likely culprits, but we can probably try again to repro this keeping all that in mind.

> things have been a bit crazy lately

Same :P I'm not sure when we'll be able to look into this again, but I'll make sure we have this evaluated and prioritized appropriately. Thanks again for the info and for your patience.

**Comment by roll4life** [comment]
@Cynerva 
Thanks, if there is anything else that you want me to examine, please let me know.

> I see ceph-secret-admin in your StorageClass, vs. ceph-admin-secret in your static claim. Is there a difference between those? I'm guessing that's not the cause of the issue but want to make sure.

that was a typo in the static claim . . . strange that static claim works with the wrong credentials
the provisioner will actually throw an warning if the secret does not exist, although not sure if it throws an error if the credentials are wrong.
```
Name:		mypvc


  1 apiVersion: v1
Namespace:	default
StorageClass:	rbd
Status:		Pending


  1 apiVersion: storage.k8s.io/v1
Volume:
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  1m		11s		7	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "rbd": failed to get admin secret from ["default"/"ceph-admin-secret"]: failed to get secret from ["default"/"ceph-admin-secret"]
```

> 1. My StorageClass only specified one of the three monitor endpoints. Yours has all three.

I've tried each monitor individually, but get the same results

> 2. My PVC was 500Mi, vs. your 15Gi

I've tried a variety of sizes, my understanding is that I should (not that it would be a good idea) be able to pick a size that exceeds the total storage capacity of the ceph cluster, because of the way ceph thin provisions all volumes.  Currently there is still about 40TB free on the ceph cluster so I think I'm ok there

>3. As you mentioned before, I was on AWS and had ceph deployed and related in the same model.

My guess is that the issue is here 
The claim stays in pending forever (or at least I think it will, I've never left one in place for longer than a week), there are no errors or warnings and it never fails. It seems like there is something that is not allowing the claim to actually be fully processed

**Comment by roll4life** [comment]
@Cynerva @chuckbutler 
This ticket can be closed. In troubleshooting another ceph rbd issue I was able to resolve this issue.  the root issue was rp_filter on the Ceph Monitors dropping the packets coming from the kubernetes cluster, since kubernetes was running on a different network segment than the ceph monitors, and the ceph monitors have multiple vLAN's assigned
```
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1
```
Modifying the rp_filter config in /etc/sysctl.conf on on the ceph monitors to the following configuration resolved the issue.
```
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter=0
```
If anyone else in the future hits a similar issue you can use telnet or nmap from the kubernetes master/workers to validate connectivity to the ceph monitors.  
`telnet <ceph-monitor-ip> 6789`
`nmap -sT -p 6789 <ceph-monitor-ip>`
