### ISSUE TITLE
Shipping an outdated ingress controller

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#279]
The current image of the ingress-rc should be shipping with image: 
`      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.5`

however, we are shipping
`      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3`

Current deployment manifests can be found here: https://github.com/kubernetes/ingress/tree/master/examples/deployment/nginx

Note: these manifests change the namespace to kube-system, and would not work for me in my deployment using CNI until I set 'hostNetwork: true' in the manifest, which is commented out.

**Comment by tvansteenburgh** [comment]
This will be updated when the RBAC stuff is merged/released.

**Comment by hyperbolic2346** [comment]
I think this is safe to close now. We have updated the controller to image gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15 and exposed a configuration variable for that. Before that, the image was updated to beta.13.
