### ISSUE TITLE
juju run-action kubernetes-worker/0 registry - exposed as ingress (should be nodePort)

### ISSUE THREAD

**Issue by andrebron** [juju-solutions/bundle-canonical-kubernetes#280]
https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/actions/registry#L67-L68

**Comment by chuckbutler** [comment]
I'm not certain NodePort was the accepted answer here, however it should be providing the cert as a secret and being configured by a configmap to the ingress controller.

I'll circle back with jacekn about this and see if we can sort where the mismatch came from. The only thing I can figure is when we moved the ingress controller over to the cdk-addon snap we had a gap in testing coverage there and managed to omit the configmap declaration but I need to do more investigation into this before I rule that as the culprit.

**Comment by chuckbutler** [comment]
@andrebron I've lost context on this. Is this still an issue for you?

**Comment by chuckbutler** [comment]
I actually think this is better covered in the linked issue 281, and I'm going to close this infavor of that bug.
