### ISSUE TITLE
No way to skip CUDA installation in a CUDA capable unit

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#282]
There is no way to skip CUDA installation here are a couple of reasons you would want to do that:
1. Deploying k8s on LXD on a local machine. CUDA pull in few GBs of dependencies times the number of workers. This makes deploying k8s on a local machine rather impractical.
2. Deploy k8s in a network restricted environment. The nvidia-cuda layer tries to access the web.
3. For some reason the external dependency of CUDA fails, leaving us broken.

**Comment by marcoceppi** [comment]
The only valid reason, imo, is the first one. The other two are known issues and should be addressed independently.

I think an `enable-gpu` flag with an auto value and false/off/no for not would be the right path to address this. We should then have conjure-up set that to off for localhost.

**Comment by ktsakalozos** [comment]
Closed via https://github.com/juju-solutions/layer-nvidia-cuda/pull/4
