### ISSUE TITLE
Is API-loadbalancer a single point of failure?

### ISSUE THREAD

**Issue by hzamani** [juju-solutions/bundle-canonical-kubernetes#296]
If that is the case, how we can add failovers?

**Comment by hzamani** [comment]
@givia

**Comment by chuckbutler** [comment]
Greetings @hzamani,

What we have implemented today is certainly scalable. Each worker has the limitation however of only being able to contact a single api-endpoint, irrespective of how many addresses you inform it of. This is a limitation of the kubelet codebase itself.  We've mitigated this with round-robin distribution of those requests via a load balancer.

As you've pointed out, it certainly could be a single point of failure, however, you can scale the kube-api-loadbalancer application. Each worker unit has logic in the charm to pick one at random from the presented list and will communicate with that api-loadbalancer for the duration of its lifecycle. As you add/remove loadbalancers, the kubelet units will reconfigure based on the *-departed and *-changed events respectively.

If you wish to distribute load against these load balancers from a client user perspective, I would recommend a DNS based solution, where you route to those api-loadbalancers with a PTR record, where you can weight them and additionally use health checking depending on the cloud/DNS provider. Update the client kubeconfig on your workstation with that DNS record and it should perform as expected. (You might need to add extra SANS to the LB's TLS certificate if you take this route however.)

Let me know if this successfully answers your question.

**Comment by chuckbutler** [comment]
As there has been no movement on this bug for 20 days since the last interaction, I'm going to close this. If there are any further questions relating to this issue please comment here and we'll get it reopened.
