### ISSUE TITLE
Add description to bundles

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundle-canonical-kubernetes#302]
As shown here: https://jujucharms.com/docs/2.1/charms-bundles#creating-a-bundle

The Juju GUI is going to start displaying the description, so we need to have it populated.

**Comment by Cynerva** [comment]
I think we have this already for canonical-kubernetes via https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/293, but not kubernetes-core
