### ISSUE TITLE
Make channel match between charm config and bundle config

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#305]
https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/config.yaml#L23

Does not match the default configuration of the bundle, which defaults to `1.6/stable`. This can trigger a premature upgrade notice for end users and is confusing at how they entered this scenario if the worker was ever deployed independently of the bundle. The most basic approach to resolving this would be to make the channels match and attempt to keep them in lockstep.

**Comment by Cynerva** [comment]
Same will need to be done for kubernetes-master, too

**Comment by tvansteenburgh** [comment]
Update master, worker, and e2e.
