### ISSUE TITLE
CDK control plane is not HA

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundle-canonical-kubernetes#308]
CDK bundle should include 3 master nodes, at which point we can actually call it an HA cluster.

**Comment by tvansteenburgh** [comment]
@marcoceppi What do you think about this? Should we update the CDK bundle to include 3 masters so that every component is HA?

**Comment by ktsakalozos** [comment]
Why 3 masters @tvansteenburgh? Is there a need for quorum on the masters? Would just one failover master be enough (2 masters in total)? Should there be a heartbeat between LB and master? This might also be in place, did not check.

**Comment by tvansteenburgh** [comment]
@ktsakalozos True, two is probably enough for the default. Of course then the single point of failure is the LB. There should be a health check in place from LB to master, but I haven't confirmed that.

Maybe we shouldn't bother making the bundle multi-master by default - interested in others' opinions.

**Comment by marcoceppi** [comment]
We don't need three, as @ktsakalozos points out - failover (2) is enough. However, as you mentioned the LB becomes the bottleneck again which is one of the reasons HAProxy is more interesting as an apilb - it would allow for more fine grained health checks, and better supports failover. I don't think we need to have two by default, the bundle is already pretty large in machine count, it's easy enough for anyone to `juju add-unit` and if the master goes away, you simply need to `juju add-unit` to replace the downed unit

**Comment by tvansteenburgh** [comment]
@marcoceppi +1, thanks for your input.
