### ISSUE TITLE
Use resources for the kubectl tools? 

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/bundle-canonical-kubernetes#31]
Finding the master and scping the tools to my local machine is annoying, perhaps we can just toss the tools in a resource for the user to snag?

**Comment by chuckbutler** [comment]
The problem with putting the tools in resources is we are then providing the tools, and it's not obvious to the user how to get them (nor is telling them to scrape juju status for an scp command), as resources are primarily for delivery of bins for the charm.

While this will make our charm(s) far more friendly to being behind the firewall, we're still dependent on gcr.io for the Kubernetes images at present. I feel like this is a small subset of a larger scope of work, to push the images as resources. However, we're still beta-testing large resources in the store and this may not be a good solution -today-.

**Comment by chuckbutler** [comment]
Whats great is the kubectl tools are now being delivered with resources! closed :)
