### ISSUE TITLE
Can't set snap config bool variable to false

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#314]
We have a param of kubelet that is called `anonymous-auth`, this variable has a default value of true.

If we try to set it to false it will just be removed from the set of arguments passed to kubelet and it will be true by default.

```shell
root@ip-172-31-8-191:/home/ubuntu# ps -ef | grep kubelet
root      3541     1  4 10:18 ?        00:00:01 /snap/kubelet/27/kubelet --address 0.0.0.0 --allow-privileged --client-ca-file /root/cdk/ca.crt --cluster-dns 10.152.183.10 --cluster-domain cluster.local --kubeconfig /root/cdk/kubeconfig
root@ip-172-31-8-191:/home/ubuntu# snap set kubelet anonymous-auth=true
root@ip-172-31-8-191:/home/ubuntu# systemctl restart snap.kubelet.daemon
root@ip-172-31-8-191:/home/ubuntu# ps -ef | grep kubelet
root      4123     1 20 10:19 ?        00:00:00 /snap/kubelet/27/kubelet --address 0.0.0.0 --allow-privileged --anonymous-auth --client-ca-file /root/cdk/ca.crt --cluster-dns 10.152.183.10 --cluster-domain cluster.local --kubeconfig /root/cdk/kubeconfig
root@ip-172-31-8-191:/home/ubuntu# snap set kubelet anonymous-auth=false
root@ip-172-31-8-191:/home/ubuntu# systemctl restart snap.kubelet.daemon
root@ip-172-31-8-191:/home/ubuntu# ps -ef | grep kubelet
root      4601     1 10 10:20 ?        00:00:00 /snap/kubelet/27/kubelet --address 0.0.0.0 --allow-privileged --client-ca-file /root/cdk/ca.crt --cluster-dns 10.152.183.10 --cluster-domain cluster.local --kubeconfig /root/cdk/kubeconfig
```

**Comment by Cynerva** [comment]
@tvansteenburgh This one seems important. We can't disable anonymous-auth on kubelet and that has security implications.

**Comment by tvansteenburgh** [comment]
So this is a `snap set` problem?

**Comment by Cynerva** [comment]
It's a problem with the configure hooks in our snaps. We generate the configure hooks using [this script](https://github.com/juju-solutions/release/blob/rye/snaps/snap/shared/generate-configure-hook) and it doesn't properly allow for the `--anonymous-auth=false` format that we need to pass to kubelet.

**Comment by Cynerva** [comment]
To clarify, with the configure hooks we have now, there's nothing we can pass to `snap set kubelet ...` to get `--anonymous-auth=false` passed to kubelet. So we need to fix the hooks.
