### ISSUE TITLE
Are namespace actions really important?

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#329]
There are 3 actions to CRUD namespaces in K8s present in the charms. At this point in time, beside the fact they fail, I am wondering if they are really so important?

**Comment by ktsakalozos** [comment]
I am also not sure what purpose these actions serve. We are not supposed to wrap all kubectl commands but we do so with namespace CRUD actions. There might be some other reason why we have these actions, if not, +1 for removing them.

**Comment by tvansteenburgh** [comment]
I think these are useful and I vote for keeping them. They were contributed by @jacekn from Canonical IS, who are Real Users of CDK. Maybe they seem out of place b/c we don't have many actions yet, but that will change once we start implementing user-management actions.

**Comment by ktsakalozos** [comment]
Here are tests so we do not break these actions again. https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/334
