### ISSUE TITLE
Generated kubectl tarball needs a subdirectory

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/bundle-canonical-kubernetes#33]
It's considered rude in unix land to have a tarball dumping tools in the root dir, please modify the kubectl generation to include a subdirectory, recommend something like `kubectl-x.x/` for a version.

**Comment by chuckbutler** [comment]
@castrojo - is it a hard rquirement to have the version? the way we are currently packing the tarball doesn't seem to include the version id. We can get it from config, however thats an intermediary step in creating the package. 

Would it satisfy the current need to not just dump in $PWD if we encapsulate it in a `kubernetes` directory?

eg:

```
tar xvfz kube_credentials.tar.gz =>   kubernetes/kubectl , kubernetes/client.key ... and so on.
```

**Comment by castrojo** [comment]
I was thinking the version would be useful but not a hard requirement.

**Comment by chuckbutler** [comment]
I see your point. i'll noodle this and eat the code lines in favor of being more obvious to the user just *what* it is they have downloaded.

**Comment by chuckbutler** [comment]
Closed with how we're delivering the client package now
