### ISSUE TITLE
Certificates have a 0770 in /root/cdk

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#336]
Weirdly I get: 

<pre><code>
$ sudo ls -l /root/cdk
total 44
-rw-r--r-- 1 root root   17 Jun 23 15:00 basic_auth.csv
-rwxrwx--- 1 root root 1187 Jun 23 15:09 ca.crt
-rwxrwx--- 1 root root 4379 Jun 23 15:09 client.crt
-rwxrwx--- 1 root root 1703 Jun 23 15:09 client.key
drwxr-xr-x 2 root root 4096 Jun 23 15:11 etcd
-rw-r--r-- 1 root root  149 Jun 23 15:00 known_tokens.csv
-rwxrwx--- 1 root root 4998 Jun 23 15:11 server.crt
-rwxrwx--- 1 root root 1704 Jun 23 15:11 server.key
-rw-r--r-- 1 root root 1675 Jun 23 15:00 serviceaccount.key
</code></pre>

I think they should be in 640, or even in 440 to avoid unecessary mistakes (but that would be harsh)

**Comment by tvansteenburgh** [comment]
@SaMnCo Which charm is this on (easyrsa, master, worker)?

**Comment by SaMnCo** [comment]
Ah, this was colocated but I think it is the Master that carries /root/cdk

I'll give it a try asap and confirm

**Comment by luxas** [comment]
Any update on this? Can this be reproduced?

**Comment by Cynerva** [comment]
I haven't tried to reproduce this, but I think the culprit is here: https://github.com/juju-solutions/layer-tls-client/blob/master/reactive/tls_client.py#L118

**Comment by CalvinHartwell** [comment]
Potential fix for review here: [https://github.com/juju-solutions/layer-tls-client/pull/12](https://github.com/juju-solutions/layer-tls-client/pull/12)

These are the offending lines at the bottom: [https://github.com/juju-solutions/layer-tls-client/blob/master/reactive/tls_client.py#L118](https://github.com/juju-solutions/layer-tls-client/blob/master/reactive/tls_client.py#L118):

`def _write_file(path, content):
    '''Write the path to a file.'''
    _ensure_directory(path)
    with open(path, 'w') as stream:
        stream.write(content)
    os.chmod(path, 0o440)`

Also note, there is another potential offending function, which creates directories with 0770:

`def _ensure_directory(path):
    '''Ensure the parent directory exists creating directories if necessary.'''
    directory = os.path.dirname(path)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    os.chmod(directory, 0o770)`

I think this also needs to be modified, thoughts?
