### ISSUE TITLE
Improve constraints in bundles

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#338]
The default kubernetes-core and CDK bundles have no constraints. As a result, the base instance on AWS is so small that it is barely possible to run Helm Tiller pod once nginx and the dashboard components are loaded. Not great from a UX perspective.  

It would make sense to add a constraint on the worker nodes to add 4 cores and 4GB RAM so users can start playing with the system, and/or to scale to at least 2 workers and keep the same sizing.

**Comment by tvansteenburgh** [comment]
Fair point, let's update the worker nodes with 4 cpu, 4GB RAM constraints in both bundles. @marcoceppi Any objections?

**Comment by marcoceppi** [comment]
:+1:
