### ISSUE TITLE
Open up configuration management for various services

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#339]
In the worker config there is the option to add docker-opts, which is great for users to customize their docker engine. 
It would be awesome to get the same options for kube-apiserver, kube-scheduler, kube-controller-manager on the masters and kubelet, kube-api-proxy on the workers. 

There is a lot that can augment the default set that goes via the command line options, and making it resilient within Juju would definitely be of great help. 

In the behavior that I would expect: 

* parsing out the options that are "juju controlled" (etcd endpoints...) and surface that to the user to explain why they have been removed
* match against the official list of options
* config-change does a restart on the services that need it

**Comment by tvansteenburgh** [comment]
This is in-progress for kube-apiserver: https://github.com/kubernetes/kubernetes/pull/47912

**Comment by tvansteenburgh** [comment]
All of the snap arguments can now be configured via the `*-extra-args` config options on the kubernetes-master and kubernetes-worker charms.
