### ISSUE TITLE
Charms do not indicate when some services are dead

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#341]
This came up in testing this week -- the kube-proxy service was totally dead on LXD, and we got quite a lot of testing in before we noticed.

Seems like the charms should tell us if any of the services are dead.

**Comment by tvansteenburgh** [comment]
Do this check in update-status I assume? For any stopped service, we could try to restart it once, and if that fails, report it via charm status.
