### ISSUE TITLE
Bundle descriptions have weird formatting

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#342]
In the [fragment](https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/master/fragments/k8s/cdk/bundle.yaml), the description looks fine:

```
description: |
    A nine-machine Kubernetes cluster, appropriate for production. Includes a
    three-machine etcd cluster and three Kubernetes worker nodes.
```

In our [built bundles](https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml), it looks off:

```
description: 'A nine-machine Kubernetes cluster, appropriate for production. Includes
  a

  three-machine etcd cluster and three Kubernetes worker nodes.

  '
```

**Comment by tvansteenburgh** [comment]
Fixed by https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/349
