### ISSUE TITLE
Dynamic EBS volume provisioning for AWS

### ISSUE THREAD

**Issue by eric-sonchaiwanich** [juju-solutions/bundle-canonical-kubernetes#345]
Need an option (or default behavior) where an AWS cloud provider is configured in Kubernetes when when CDK is deployed to AWS.  When Pods are deployed with a persistent volume claim, those claims should result in dynamically creating EBS volumes to satisfy that claim.

**Comment by tvansteenburgh** [comment]
This behavior is available via the AWS integrator charm (https://jujucharms.com/new/u/containers/aws-integrator), which is deployed automatically by conjure-up when deploying CDK to AWS.
