### ISSUE TITLE
Review kubernetes docs and point to snaps when needed

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#358]
As @castrojo pointed out we should review pages like:
https://kubernetes.io/docs/setup/independent/install-kubeadm/ and reference snaps if available.

**Comment by tvansteenburgh** [comment]
Also https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/

**Comment by tvansteenburgh** [comment]
There are a variety of reasons why we can't do much more than https://github.com/kubernetes/kubernetes.github.io/pull/4601 for now. Will revisit later.
