### ISSUE TITLE
Support for Calico as NetworkPolicy provider

### ISSUE THREAD

**Issue by eric-sonchaiwanich** [juju-solutions/bundle-canonical-kubernetes#359]
Request support for Calico as a Kubernetes network policy provider.  Presently, CDK has no support for Kubernetes network policy resources because this functionality is provided by an external network plugin.  Network policies are important for segmenting access to services within the Kubernetes cluster.  

The documentation for Network Policies are here:
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

Note: There is a project, Canal, which bundles Flannel and Calico together.  Since CDK includes Flannel currently, this may be of interest.

Project Canal: https://github.com/projectcalico/canal

**Comment by tvansteenburgh** [comment]
@eric-sonchaiwanich Thanks, we'll start looking at Canal in this sprint.

**Comment by tvansteenburgh** [comment]
Canal charm here: https://github.com/juju-solutions/layer-canal
Test bundle here: cs:~cynerva/canonical-kubernetes-canal-0

`juju deploy cs:~cynerva/canonical-kubernetes-canal-0`

Note this is still work-in-progress, not officially "ready" yet.
