### ISSUE TITLE
OVN charm : etcd relation

### ISSUE THREAD

**Issue by AakashKT** [juju-solutions/bundle-canonical-kubernetes#365]
Hi all,
I noticed that the flannel charm has an etcd relation, and for the OVN charm, I would like to add that too. For this, I want to understand what exactly the etcd relation is used for, and how it can be used with the OVN charm. 
I had tried once to use etcd, by installing etcdctl separately on the worker / master, but etcdctl gave connection refused. 
I had used all the right flags (as done by flannel), --endpoint, --ca-file, --key-file, --cert-file.
Would like to have your help on this :-)
Cheers!

**Comment by ktsakalozos** [comment]
Hi,

You can find the flannel source https://github.com/juju-solutions/charm-flannel/blob/master/reactive/flannel.py . Etcd plays a rather important role for flannel. As you can see flannel uses the etcd interface: https://github.com/juju-solutions/charm-flannel/blob/master/layer.yaml#L2 and the interface source is here: https://github.com/juju-solutions/interface-etcd .
