### ISSUE TITLE
nginx-controller-manager should be a DaemonSet

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#367]
We currently have nginx-controller-manager defined as a ReplicationController [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/templates/ingress-replication-controller.yaml), with some logic in the charm to keep it scaled to the number of nodes [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L398-L400).

Looks like Kubernetes has a DaemonSet object that would make more sense for this: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by SaMnCo** [comment]
+1 
In addition please consider adding a nodeSelector set to the juju application name so that if you have a cluster with multiple kubernetes-worker charms deployed with different names, the ingress controller does not spread to all nodes. 
This would then allow you to do something like
```
juju deploy cs:~containers/kubernetes-worker ingress-only-workers --space=dmz
juju deploy cs:~containers/kubernetes-worker no-ingress-workers --config set-ingress-false.yaml --space=secure
```

**Comment by wwwtyro** [comment]
@hyperbolic2346 Can this be closed?

**Comment by hyperbolic2346** [comment]
Yes, closing.
