### ISSUE TITLE
doc: Kubernetes API Server, controller-manager, scheduler, and kubelets configuration update

### ISSUE THREAD

**Issue by evgkarasev** [juju-solutions/bundle-canonical-kubernetes#370]
Hello! Many Kubernetes new features depends to Kubernetes API Server, controller-manager, scheduler, and all kubelets configuration to enable feature gate, and sometimes require privileged mode. 
Since `/etc/default/kubelet` as well as `/etc/default/kube-apiserver` configuration files were hidden within recent releases of CDK, please could you advice how to setup `--allow-privileged` and `--feature-gates` flags for kubelet and API server within Kubernetes deployment? Thank you!

**Comment by wwwtyro** [comment]
Hi @evgkarasev -- we currently support setting `--allow-privileged` via juju config:

```sh
juju config kubernetes-master allow-privileged=true
juju config kubernetes-worker allow-privileged=true
```

Make sure you set that configuration on both master and worker to get them working.

We don't currently have support for setting arbitrary flags, but have a PR open to add support for this on the apiserver that should land soon: https://github.com/kubernetes/kubernetes/pull/47912

We'll use this issue to track adding support for arbitrary flags to the other services as well.

**Comment by evgkarasev** [comment]
@wwwtyro Thank you for prompt response!
