### ISSUE TITLE
Description in the bundle.yaml is malformed

### ISSUE THREAD

**Issue by hatched** [juju-solutions/bundle-canonical-kubernetes#371]
https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml

```
description: 'A nine-machine Kubernetes cluster, appropriate for production. Includes
  a

  three-machine etcd cluster and three Kubernetes worker nodes.

  '
```

**Comment by ktsakalozos** [comment]
Thank you for reporting this.

A fix has already been merged (https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/349) and will be available on the next release.
