### ISSUE TITLE
Registry reverts to broken SSL certificate after deployment

### ISSUE THREAD

**Issue by dave-lawson** [juju-solutions/bundle-canonical-kubernetes#380]
I deployed the CDK with a malformed registry certificate file that just included the chain certs, not the actual cert itself.  I then tore down the various applications deployed by the bundle, fixed the cert file then re-deployed and the registry worked fine, I was able to both push to it and pull from it.  The next day, for reasons passing understanding, accessing the registry started failing with the same error as the original, failed deployment of the service.  As far as I can tell, the registry related contents of the k8s secrets are correct, the tls-key secret field has all three certs in it, etc.  Can you give me some pointers about what to look at on the registry pod to identify what's going wrong here?

$ sudo docker pull prod-comms.docker-registry.canonical.com/ubuntu:xenial
Error response from daemon: Get https://prod-comms.docker-registry.canonical.com/v1/_ping: x509: certificate is valid for fd0d62fec9a3, not prod-comms.docker-registry.canonical.com

**Comment by ktsakalozos** [comment]
The registry action you called on a kubernetes-worker creates a `registry.yaml` file under `/root/cdk/addons` and then applies it (https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/actions/registry#L83). The first time you run the action command a faulty yaml file was created. Then you corrected and recreated everything but you did not do that by correcting and re-applying the registy.yaml, right? I suspect that that faulty registry.yaml file got reapplied for reasons I do not know. Do you happen to have a kubernetes-master charm deployed on the same unit as the kubernetes-worker where the registry is?

**Comment by dave-lawson** [comment]
I suspect you're right but I don't have a process for replicating and given it was a one time weirdness, I think we can close this.  If I see that behavior again I'll try to boil it down to something that can be replicated.

**Comment by ktsakalozos** [comment]
Thanks. Closing this.
