### ISSUE TITLE
Ability for etcd and kubernetes-master applications on same machine instances

### ISSUE THREAD

**Issue by eric-sonchaiwanich** [juju-solutions/bundle-canonical-kubernetes#387]
Requesting the ability for etcd and kubernetes-master components to reside on the same machine instance.  

The desired impact is to reduce the number of machine instances required to run a CDK cluster by consolidating etcd and k8s master nodes.

Etcd is a core dependency of k8s, and the practice of not allowing non-kubernetes components to use the same etcd cluster appears to be common.

**Comment by marcoceppi** [comment]
This ability exists today, just assign etcd to master unit

**Comment by ktsakalozos** [comment]
As Marco said, you can co-locate etcd and kubernetes-master as we do on the kubernetes-core bundle (https://jujucharms.com/kubernetes-core/). To see how it's done, have a look here: https://api.jujucharms.com/charmstore/v5/kubernetes-core/archive/bundle.yaml
