### ISSUE TITLE
hook failed: "install" Error

### ISSUE THREAD

**Issue by ramkuvel** [juju-solutions/bundle-canonical-kubernetes#393]
I deployed Kubernetes Core (and in canonical kubernetes as well) in Ubuntu 16.04 localhost, getting hook failed: "install" error in etcd and kubernetes-master.

Please find the debug logs attached.
[debug.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254090/debug.txt)
[easyrsa.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254093/easyrsa.txt)
[etcd.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254091/etcd.txt)

[kube-master.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254092/kube-master.txt)
[kube-worker.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254094/kube-worker.txt)
[master.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254095/master.txt)
[status.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254096/status.txt)

[storage-pools.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1254097/storage-pools.txt)

**Comment by ktsakalozos** [comment]
Hi,

Thank you for reporting this. 

Looking at the logs you attached I see a number of "snap install" failures. Do you happen to be in a network restricted environment? Can you `juju ssh kubernetes-maste/0` and there do a `sudo snap install --channel=1.7/stable --classic kubectl`? What is the output? Also can you describe how you did the deployment? Did you do a conjure-up installation? How did you deploy conjure-up? `snap install conjure-up --classic`?

Just tested a localhost deployment inside a clean VM on AWS with no problems.

We would be interested to know how your setup looks like, in hope we can improve our installation procedure to handle your use case.

Thanks.

**Comment by infinitydon** [comment]
Hi @ktsakalozos,

Am getting the same error when installing in Openstack.

I tried "sudo snap install --channel=1.7/stable --classic kubectl" in the k8s master container but not successful.

But the same command is working in the host VM. 

Any assistance will be appreciated.

**Comment by ktsakalozos** [comment]
Hi @infinitydon ,

This seems to be a problem with some kind of network restriction. Is it possible your lxd containers are behind some firewall? How do they access the internet? There is a proxy config variable you can use on the charms. Your openstack admin might now what is going on.

**Comment by infinitydon** [comment]
I actually installed the openstack :)
I agree it's some sort of restriction. 
Strange thing is that the snap install command is working on the VM itself but not lxd containers. 

We are. not using any proxy,  Internet connection is direct. 

I took a tcpdump on the VM but it didn't give much insight because the packets were encrypted with TLS. 

Also using wget to fetch data via https is working in the lxd containers. 

Is there any snap command with debugging? 

I will also check the Neutron logs if there are, any clues there.

**Comment by infinitydon** [comment]
Hi @ktsakalozos ,

How can I change the MTU size LXD will use for containers?

I think it's the MTU that is causing the error, I need to change the MTU default size to 1450 for the containers.

**Comment by infinitydon** [comment]
Finally got this working!

I matched the MTU size of the lxd bridge interface to that of the host VM:
"ip link set mtu 1450 dev lxdbr0"

Then did the conjure-up kubernetes... Now cluster is up and running:

> ubuntu@cdk:~$ kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-1               Healthy   {"health": "true"}   
etcd-2               Healthy   {"health": "true"}   
etcd-0               Healthy   {"health": "true"}

**Comment by ktsakalozos** [comment]
Great news @infinitydon . I am sorry I wasn't much of a help.

**Comment by ktsakalozos** [comment]
Do you think your fix could/should be part of the conjure-up scripts [1] so we guard against this case? @battlemidget what do you think?

[1] https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/steps/00_process-providertype/before-deploy

**Comment by infinitydon** [comment]
Hi @ktsakalozos ,

If possible yes, I faced this issue on Openstack Ocata. Maybe this is a general issue with Openstack enviroment.

Or the documentation can be updated with the fix.
