### ISSUE TITLE
Kubernetes does not run on the LXD provider in Juju

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#4]
Juju's LXD implementation does not currently allow custom profiles to be used when starting LXD containers. The Kubernetes charm uses docker containers and to run docker with in LXD requires a special profile.

We should note the limitation of LXD on the observable bundle.

**Comment by battlemidget** [comment]
What do you have to do to the LXD profile to make it work?

**Comment by mbruzek** [comment]
Since kubernetes uses docker containers we have to be able to run the LXD provider with the docker profile. I do not believe Juju allows configuration of the LXD profile used. I am waiting for the bug you opened to be able to try more out: https://bugs.launchpad.net/juju-core/+bug/1552815

After that tyc0 has indicated that some Docker containers may not run well inside LXD depending on what they do. The containers in the kubernetes charm are using many advanced docker features that would have to be tested to verify they work correctly in LXD.

**Comment by battlemidget** [comment]
Ok cool, I may have a workaround for applying a docker profile for LXD using `conjure-up`. Do you have a docker profile that I can apply?

**Comment by mbruzek** [comment]
LXD ships with a profile named "docker" in my manual testing that was what was needed to get the "hello world" docker container to run in LXD.  The way Stephan explained it to me was you need **both** the default profile and the docker profile and you can specify multiple profiles on the command line (the commands I don't recall at the moment).

**Comment by battlemidget** [comment]
Ah interesting about the double profile on the cli, ill have to try this out and see if I can get something turnkey working

**Comment by mbruzek** [comment]
We have documented this in the bundle README.

**Comment by chuckbutler** [comment]
Primary concerns of this bug are covered in #70
