### ISSUE TITLE
Make it easy to deploy the vSphere provider 

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#402]
The vSphere provider is well documented by VMWare in the [official documentation](https://kubernetes.io/docs/getting-started-guides/vsphere/). This note will therefore focus on the specifics of CDK rather than redo the whole thing. 

**Before you begin**: If no changes are made to the snaps / install method, it is only possible to (sort of) automate the installation of the vSphere provider if you name your VMs after their FQDN in vSphere or any other value that the system can return regardless of the status of the snaps for kube-apimanager and kube-controller-manager (hostname…). Any other naming convention will require manual setup for every master (workers are OK since the kubelet snap is in classic at the time of this writing)

First of all we need to prepare a configuration file for the provider, which will be sent to each individual machine. Below is the template of the file. Note that the important line here is the "vm-name" which we set to FQDN. We will come back on the reason for this later on. 

```
[Global]
        user = vsphere
        password = xxxxxxxxxxx
        server = my.vsphere.vcenter.host
        port = 443 
        insecure-flag = true
        datacenter = vSphereDataCenter
        datastore = DefaultDatatore
        working-dir = DefaultWorkingDir
        vm-name = FQDN
[Disk]
        scsicontrollertype = pvscsi
```

Now we create a small script that will update the FQDN of this file on each and every machine and replace it by the fqdn of the machine: 

```
#!/bin/bash
FQDN=$(hostname --fqdn)
sed -i s#FQDN#${FQDN}#g /root/cdk/vsphere.conf
```
Note that you could update this with any value provided that the snaps can collect it from the host system and, obviously, that it matches the name of the VM in vSphere. This is why the naming convention of the VMs was outlined as critical in the "before you begin" note. 

Now we are ready to proceed. We need to upload the file to all masters and workers, then update the configuration of the kubelet, API server and controller-manager and finally restart all services. 

```
for i in $(seq 0 1 NumberOfMasters)
do
     juju scp vsphere.conf kubernetes-master/${i}: 
     juju ssh kubernetes-master/${i} "sudo chown root:root /home/ubuntu/vsphere.conf; sudo mv /home/ubuntu/vsphere.conf /root/cdk/"
    juju ssh  kubernetes-master/${i} "sudo snap set kube-apiserver cloud-provider=vsphere; sudo snap set kube-apiserver cloud-config=/root/cdk/vsphere.conf" 
    juju ssh  kubernetes-master/${i} "sudo snap set kube-controller-manager cloud-provider=vsphere; sudo snap set kube-controller-manager cloud-config=/root/cdk/vsphere.conf"
done

for i in $(seq 0 1 NumberOfWorkers)
do
     juju scp vsphere.conf kubernetes-worker/${i}:
     juju ssh  kubernetes-worker/${i} "sudo chown root:root /home/ubuntu/vsphere.conf ; sudo mv /home/ubuntu/vsphere.conf /root/cdk/"
     juju ssh  kubernetes-worker/${i} "sudo snap set kubelet cloud-provider=vsphere; sudo snap set kubelet cloud-config=/root/cdk/vsphere.conf"
done

juju run --application kubernetes-master 'sudo bash -c "$(echo IyEvYmluL2Jhc2gKRlFETj0kKGhvc3RuYW1lIC0tZnFkbikKc2VkIC1pIHMjRlFETiMke0ZRRE59I2cgL3Jvb3QvY2RrL3ZzcGhlcmUuY29uZgoK | base64 -d)"'

juju run --application kubernetes-worker 'sudo bash -c "$(echo IyEvYmluL2Jhc2gKRlFETj0kKGhvc3RuYW1lIC0tZnFkbikKc2VkIC1pIHMjRlFETiMke0ZRRE59I2cgL3Jvb3QvY2RrL3ZzcGhlcmUuY29uZgoK | base64 -d)"'

juju run --application kubernetes-master 'sudo systemctl restart snap.kube-apiserver.daemon.service'
juju run --application kubernetes-master 'sudo systemctl restart snap.kube-controller-manager.daemon.service'

juju run --application kubernetes-worker 'sudo systemctl restart snap.kubelet.daemon.service'
```

The use of base64 here is to elegantly send our mini script to the machines for execution. 

**IMPORTANT NOTE**: the vm-name tag is optional in the normal configuration. The reason why we have to use it in CDK at this point in time is that 

* CDK will only name the hosts after their hostname and not FQDN or VM name (as in vSphere), which means that the name of the K8s node after installing the provider will differ from the name it had before
* If you do not specify vm-name, it is read from /sys/class/dmi/id/product_serial by the API server, Controller Manager and Kubelet. While kubelet is a classic snap and can read this file, the 2 others are not and fail to retrieve the value. 
* Also note the "before you begin"note about naming the VMs after the FQDN. If you do not apply this, then there is no way to guess the vm-name from the machine itself and the controller-manager and apiserver services won't start, putting the cluster in an error mode. 

Therefore, in the case of CDK, it is mandatory to include the vm-name or the vm-uuid in the configuration file. 

Suggested changes to make this much much easier: 

1. The best solution in my opinion is to add an interface for kube-apiserver and kube-controller-manager (and kubelet if at some point it is not deployed in classic mode, which would make sense btw) so they can read /sys/class/dmi/id/product_serial
2. another quick fix is to deploy the kube-apiserver and kube-controller-manager snaps in classic for now

++
Sam

**Comment by espigle** [comment]
It appears that this documentation is no longer relevant for CDK version 1.10 as some changes apparently happening around version 1.9.4 or so. Is there any way to get the vSphere provider to work with the current release of CDK (1.10 as of this comment)?

**Comment by tvansteenburgh** [comment]
vSphere integration now available via the vSphere integrator charm (see https://blog.ubuntu.com/2018/08/23/vsphere). The integration is enabled automatically when deploying to vsphere with conjure-up.
