### ISSUE TITLE
Bundle Kubernetes shield does not show the right kubernetes version

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#403]
For example here: https://jujucharms.com/u/containers/canonical-kubernetes/bundle we say 1.7.0 but you get whatever the latest kubernetes is in the snaps channel (v1.7.4 for now).

Should we go for just v1.7 so it reflects the decoupling of charms and snaps we have?

**Comment by tvansteenburgh** [comment]
IMO we should keep the readme updated to reflect what you'll get when you deploy the bundle (so in this case, 1.7.4).

**Comment by tvansteenburgh** [comment]
I think we decided to just leave off the patch version and stick with e.g. 1.8, so we only need to update once every three months.
