### ISSUE TITLE
rolling upgrade procedure for kubernetes-masters

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#408]
Kubernetes supports API versioning which allows one to run multiple API servers in a mixed mode. This is useful to perform upgrades without control plane downtime: masters are upgraded first and workers still use the old API. Once all masters are upgraded, workers follow and upgraded workers use the new API.

Our current approach to upgrade masters does provide not any step-by-step procedure: they are upgraded all at once causing short API downtime.

https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/overview/kubernetes-api.md#api-versioning
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/versioning.md
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#alpha-beta-and-stable-versions
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#on-compatibility
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#incompatible-api-changes

This could be avoided by providing a rolling upgrade procedure similar to kubernetes workers.

**Comment by tvansteenburgh** [comment]
This was released with the 1.9 charms (https://github.com/kubernetes/kubernetes/pull/55990), and the Upgrading wiki page has been updated accordingly (https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/CDK-upgrade-testing-steps)
