### ISSUE TITLE
rbac roles

### ISSUE THREAD

**Issue by lghinet** [juju-solutions/bundle-canonical-kubernetes#414]
hello, 
i cannot create roles and clusterroles , is rbac mode active ? 
if not how can i turn it on 

thanks 

canonical kubernetes on lxd

**Comment by marcoceppi** [comment]
They are not at the moment. You can enable them with the following script, though some services like the dashboard, may not work as expected:

```
juju ssh kubernetes-master/0 -- 'sudo snap set kube-apiserver
authorization-mode=RBAC'
juju ssh kubernetes-master/0 -- 'sudo service snap.kube-apiserver.daemon restart'
sleep 120 
juju ssh kubernetes-master/0 -- '/snap/bin/kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=admin && /snap/bin/kubectl create clusterrolebinding kubelet-node-binding --clusterrole=system:node --user=kubelet'
```

The team will soon have a configuration option to enable/disable RBAC in a Canonical Kubernetes cluster

**Comment by lghinet** [comment]
ok, thank you

**Comment by tvansteenburgh** [comment]
Latest charms/bundles contain RBAC support, which you can enable via charm config, like so:
```
juju config kubernetes-master authorization-mode="RBAC,Node"
```
More info here: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Authorization-Mode-and-RBAC
