### ISSUE TITLE
Installing Canonical Kubernetes with Elastic

### ISSUE THREAD

**Issue by lghinet** [juju-solutions/bundle-canonical-kubernetes#415]
hello,
i am trying to install Canonical Kubernetes Elastic on ubuntu - localhost
but with conjure-up i only have Canonical Kubernetes option without elastic, so i tried to install elastic afterwards with 
`juju deploy beats-core` no errors, but beats are in a waiting state 
and 
```
juju add-relation kubernetes-master topbeat
juju add-relation kubernetes-master filebeat
juju add-relation kubernetes-worker topbeat
juju add-relation kubernetes-worker filebeat
```
where i get 
ERROR cannot add relation "topbeat:beats-host kubernetes-master:juju-info": principal and subordinate applications' series must match

is this a good approach ?

this is my setup, you can see that the beats are waiting for something .. 

![image](https://user-images.githubusercontent.com/12889810/30812014-7011e686-a212-11e7-9a1c-b3c8f3c83972.png)

thanks

**Comment by marcoceppi** [comment]
It looks like the beats bundle is a bit out of date, requesting trusty machines. All of the Kubernetes are xenial which is what that error refers to. Let me see if i can get you the right bundle, for now you should be able to `juju remove-application topbeat filebeat` in preparation for the updated bundle.

**Comment by marcoceppi** [comment]
It looks like the bundle that has the right integrations for beats/elastic is [`canonical-kubernetes-elastic`](https://jujucharms.com/canonical-kubernetes-elastic/). You should be able to just type `juju deploy canonical-kubernetes-elastic` for it to deploy the new applications (after you remove the topbeat and filebeat) and perform the relations needed.

**Comment by lghinet** [comment]
thanks for the fast reply
still went for trusty

![image](https://user-images.githubusercontent.com/12889810/30813837-3398bfd6-a217-11e7-9755-8bb50798bfa2.png)

**Comment by marcoceppi** [comment]
The unknown status is expected, furthermore the trusty machines for elasticsearch and kibana are expected. You have a deployed elastic stack and monitoring for kubernetes! I'd follow the instructions in the readme to getting indexes into kibana

**Comment by lghinet** [comment]
ok
thanks

**Comment by lghinet** [comment]
can you point me to that readme please ?
