### ISSUE TITLE
LXD not found 

### ISSUE THREAD

**Issue by yinjianfei** [juju-solutions/bundle-canonical-kubernetes#416]
I am new to conjure,using unbuntu 16.04
After 'sudo snap install conjure-up --classic'
![print](https://user-images.githubusercontent.com/12878463/30914905-afa7fafe-a3c7-11e7-9782-c1c83246dc44.png)

**Comment by marcoceppi** [comment]
Hello! Thanks for trying conjure. If you're trying to deploy to a public or private cloud you can ignore this message. If you're trying to deploy to your local 16.04 machine you'll need to run the following in a terminal before restarting conjure-up:

```
sudo snap install lxd
/snap/bin/lxd init --auto
/snap/bin/lxd network create lxdbr0 ipv4.address=auto ipv4.nat=true ipv5.address=none ipv6.nat=false
```

Once you've done that, run `conjure-up` again!

**Comment by yinjianfei** [comment]
Thanks for you help,but it is still not working, and  I try service --status-all and see the lxd is already up.

![image](https://user-images.githubusercontent.com/12878463/30944922-bcea9198-a42d-11e7-9f14-a532519d59d8.png)

**Comment by yinjianfei** [comment]
@marcoceppi 
Hi:
    Thanks for help，problem solved by using below commands.
sudo snap install lxd
sudo newgrp lxd
sudo usermod -G lxd myuser
sudo chmod 777  /var/snap/lxd/common/lxd/unix.socket
/snap/bin/lxd init --auto
/snap/bin/lxc network create lxdbr0 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false
