### ISSUE TITLE
Certificate error after changing IP address of kubernetes master machine

### ISSUE THREAD

**Issue by Frank-auckland** [juju-solutions/bundle-canonical-kubernetes#425]
/kind bug

**What happened**:
I deploy the kubernetes on AWS by using juju, the command shows as follow:

> juju deploy kubernetes-core

The juju status show as follow:
![screenshot from 2017-10-06 10-38-30](https://user-images.githubusercontent.com/20473627/31253767-91d1bc60-aa82-11e7-92a8-6cb7cf39acc2.png)

Then I set an Elastic IP address of the kubernetes master machine. So the IP address of the kubernetes master changed. After this, I can't connect to kubernetes.
It responded an error message as follow:

> Unable to connect to the server: x509: certificate is valid for 13.124.194.81, 172.31.20.111, 10.152.183.1, not 13.125.7.33

**What you expected to happen**:
I expected the connection between kube client and kube service is normal.
**How to reproduce it (as minimally and precisely as possible)**:
Change the kubernetes master instance IP address.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
AWS
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux frank-ThinkPad-L570 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
juju version is 2.2.4-xenial-amd64
- Others:

@ktsakalozos 
@wwwtyro

**Comment by ktsakalozos** [comment]
Hi,

I have some problems reproducing this. When I add an Elastic IP on the master the IP already assigned by Juju did not change so the cluster was available all the time. Can you describe in more detail what caused the IP change? 

In any case, I understand you changed the IP of the master and this caused a certificate mismatch. Why do you consider this to be a bug? It seems to me this should be the expected behaviour since it guards from unauthorised nodes acting as masters in your cluster. Would you expect the master to react on its IP change and request the issue of a new cert? That is something we can work on. Is there something else we can react upon to update the certificate?

Can you try to remove and add the relation between the easyrsa and the master? Also, is the master available to the Juju controller (eg does it show up on juju status after the IP change)?

Thank you for reporting this.

**Comment by Frank-auckland** [comment]
Hi, 
I use the command to deploy the kubernetes on AWS. The command is "juju deploy kubernetes-core". So the AWS will deploy two instances for me. These two instances have two public IP addresses, but these IP addresses are not Elastic IP. I want to add a new Elastic IP to master node. After the kubernetes running well, I create the Elastic IP and associate the Elastic IP to the master node. The IP of the master node will change to the new Elastic IP. As a result, I meet the certificate error problem.

Why I think this is a bug because if I change the IP of the master node, I will lose the control of whole kubernetes cluster. I don't know if there are some methods to get the control after the IP changing, except to change IP back because the old IP address might be used by other ones. So for my understanding, we should have some methods to get the control again, because the system administrator might change the IP by mistake, or we can set the IP as the Elastic IP when we create the kubernetes cluster.

I think the master is still available to the juju, I can see the IP change by using juju status.

**Comment by tvansteenburgh** [comment]
Ah, okay, this is basically the same as https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/426 then, I think. The IP changes, and then the cert is no longer valid. We need a way to generate and use a new cert when the IP or dns name changes.

**Comment by Frank-auckland** [comment]
Yes, we need the method to get the control again, after IP or DNS name changing.

**Comment by Frank-auckland** [comment]
I thought this problem might only happen in the kubernetes-core bundle because I try to use the canonical kubernetes. It doesn't have this problem.

**Comment by marcoceppi** [comment]
That's because traffic goes through the kube-api-loadbalancer. If that is
changes the same problem presents itself. The team is working on being able
to re-roll certs when this happens, stay tuned!

**Comment by hyperbolic2346** [comment]
Commits https://github.com/juju-solutions/layer-easyrsa/commit/7105b8b742353e97e8936e474066fd279a2c17ce and https://github.com/kubernetes/kubernetes/commit/73e8af34af6443df6fdfdca2a4c4dcbe702b5976#diff-a3d7f3f33a8970f4d4be30d9bc4e67ac help here. We don't get notification of an IP change in juju, but we will regenerate a changed certificate now in ~5 minutes. If that isn't fast enough, you can `juju config kubernetes-master extra_sans="<ip>"` to force it to change immediately.

**Comment by marcoceppi** [comment]
We should be getting notifications of IP address changes on the juju
relation when juju realizes the ip change, but I would need to double check
that.

**Comment by Frank-auckland** [comment]
Hi @hyperbolic2346, 
Thanks for your work.
But cloud you get me some information about what's the best way to test these changes, I try to get a release version, but I can't. So could I get a version number to test it?

**Comment by hyperbolic2346** [comment]
You can get version 60 of the kubernetes-master charm and version 23 of easyrsa to pick up these changes. The easiest way to do that currently is to use the edge channel, so something like `juju deploy kubernetes-core --channel edge`. Eventually, these changes will make their way down into the stable release.

**Comment by tvansteenburgh** [comment]
Latest stable charms contain support for cert regen with additional ips and/or dns names. Docs are at https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Certificate-regeneration-via-extra_sans-options

**Comment by vijayrkp** [comment]
Hello,  I am running into the same exact problem.  The kubernetes dashboard doesn't come up after master restarted and IP changed. 
I followed the steps provided in this post but couldn't resolve the issue.
Here are the steps I applied:
juju add-relation easyrsa:client kubernetes-master:certificates"
juju remove-relation easyrsa:client kubernetes-master:certificates"
juju config kubernetes-master extra_sans="<ip>" -- No effect on this.

However the following command errored out as below.
juju scp kubernetes-master/0:config ~/.kube/config
ERROR cannot connect to any address: [172.31.84.240:22 252.84.240.1:22 10.1.21.0:22 10.0.23.1:22 18.205.24.108:22]

Another point is that the juju ssh command doesn't work as well, that narrows down to the IP and network is conflicting somehow.

If the solution is to regenerate the certificate then it would be great if I get the steps to regenerate the certs for master and assign it.
Can you please provide sequence of steps that needs to be performed to solve this issue ?
Any help would be greatly appreciated.

Regards
VJ

**Comment by hyperbolic2346** [comment]
@vijayrkp I wouldn't call this the same issue. Can you please open a new one? Off the cuff, I would say that in general having non-static IP addresses for your servers would be problematic. Is there a reason you are letting them float? It seems juju is not following the IP address change so it is unable to resolve kubernetes-master/0 into an IP that will reach the machine.
