### ISSUE TITLE
Allow additional names to be added to Certificates

### ISSUE THREAD

**Issue by fraenkel** [juju-solutions/bundle-canonical-kubernetes#426]
I would like to provide a DNS name to my Masters or place a TCP proxy in front to spray across them. In both situations, there will either be a different IP address or more importantly a DNS name to reach this endpoint.
The certificates stamped for the Master (api server) needs to include these additional names so that the TLS negotiation may succeed.

**Comment by Cynerva** [comment]
This does look to be an oversight on our part and an important case to cover. I'll make sure we evaluate and prioritize this appropriately. Thanks for the report.

**Comment by hyperbolic2346** [comment]
Commits juju-solutions/layer-easyrsa@7105b8b and kubernetes/kubernetes@73e8af3#diff-a3d7f3f33a8970f4d4be30d9bc4e67ac now allow you to specify additional sans entries in the certificate. You can do so with `juju config kubernetes-master extra_sans="lb.example.com"`.

**Comment by tvansteenburgh** [comment]
This has been released. Docs are at https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Certificate-regeneration-via-extra_sans-options
