### ISSUE TITLE
`juju deploy kubernetes-core` doesn't work on LXD

### ISSUE THREAD

**Issue by rongou** [juju-solutions/bundle-canonical-kubernetes#431]
I followed the instruction at https://jujucharms.com/docs/stable/tut-lxd to setup LXD, and ran `juju deploy kubernetes-core`. It's stuck trying to allocate a machine `0/lxd/0` with the error message `LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported.` Seems like in the bundle file (https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/master/fragments/k8s/core/bundle.yaml#L21) it should just say '0' instead of 'lxd:0'?

**Comment by marcoceppi** [comment]
You will need to use conjure-up for LXD as additional LXD profiles need to
be applied.

https://kubernetes.io/docs/getting-started-guides/ubuntu/local/

**Comment by rongou** [comment]
This (conjure-up+LXD) works on my desktop, but when I tried it on my laptop (Lenovo ThinkPad T570 with 16GB memory) it crashes the OS. Do you think the machine is just too under powered?

**Comment by tvansteenburgh** [comment]
No, I run it on my 16GB laptop all the time and don't have any problems.

**Comment by rongou** [comment]
OK, probably something to do with my system. Closing this for now.
