### ISSUE TITLE
AWS deployment

### ISSUE THREAD

**Issue by iramsey85** [juju-solutions/bundle-canonical-kubernetes#433]
I deployed Canonical Kubernetes to AWS and 12 instances were create. I was able to account for 8 instances including the following:
1 juju controller
1 master node
2 worker nodes
1 easyrsa
2 etcd
1 kube api/loadbalancer

there are 4 instances whose role is not accounted for by both AWS or the juju status command (machines 5-8). How can I determine what these machines are being used for?

**Comment by tvansteenburgh** [comment]
Please post the output of `juju status`.

**Comment by Cynerva** [comment]
This sounds like there may have been a bug during deployment. If `juju status` shows machines that have no units assigned to them, then those machines aren't being used by CDK. Assuming that's the case, then it should be safe to remove them with `juju remove-machine`.

A typical CDK deployment has 9 machines (10 counting the controller):
1 easyrsa
3 etcd
1 kubeapi-load-balancer
1 kubernetes-master
3 kubernetes-worker
(1 juju controller)

It's weird that you only ended up with 2 etcd and worker nodes.

@iramsey85 couple questions for you:
1. Can you show us the output of `juju status`? (per @tvansteenburgh)
2. How did you deploy CDK? Did you use `juju` or `conjure-up`?
3. What instance types do the unused instances have? e.g. t2.xlarge. This will help us figure out if there is an issue related to [machine constraints on kubernetes-worker](https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/master/fragments/k8s/cdk/bundle.yaml#L33). (I have seen similar issues before.)

**Comment by iramsey85** [comment]
1. Below is the output of my juju status. 
2. I used conjure-up to deploy CDK, but I changed the deployment to give me 2 workers and 2 etcd. 
3. The unused instances (4) are all m3.mediums.
![juju_status_of_kubeenvironment](https://user-images.githubusercontent.com/32397569/31965761-5e6df7dc-b8d6-11e7-8568-337f1f9f1430.png)

**Comment by Cynerva** [comment]
Thanks. I'm able to reproduce the issue by deploying with conjure-up and reducing the number of units as you describe.

It looks like there is an open issue for this on conjure-up: https://github.com/conjure-up/conjure-up/issues/1140. I'll bring this to their attention.

In the meantime, feel free to clean up those extra machines:
```
juju remove-machine 5
juju remove-machine 6
juju remove-machine 7
juju remove-machine 8
```

**Comment by iramsey85** [comment]
Awesome, thank you.
