### ISSUE TITLE
AWS Instance Management - Shutdown

### ISSUE THREAD

**Issue by iramsey85** [juju-solutions/bundle-canonical-kubernetes#434]
Is there a way to gracefully power off and power on CKD instances in AWS?
I'mtrying to conserve cost by powering down over night.
When I booted machines up this monring, juju status command hangs, not loading any info about the machines. Eventually, I get the error, unable to connect to the controller in AWS.

ERROR unable to connect to API: websocket.Dial wss://xxx.xxx.xxx.xxx:17070/model/5e7955f3-6899-431d-8c20-07311dba86bc/api: dial tcp xxx.xxx.xxx.xxx:17070: getsockopt: connection timed out

Kubectl cluster-info command doesn't show all services loaded. (heapster, kubeDNS, etc)

**Comment by tvansteenburgh** [comment]
Can you confirm that the controller machine is running (the ip you xxx'd out above) and that the jujud process is running on that machine?

**Comment by iramsey85** [comment]
I wound up just killing the entire controller and redeploying the distro. Is there anything documented describing how someone should gracefully stop their machines if they wanted them turned off overnight? Is the assumption that users will just leave their AWS instances always on?

**Comment by ktsakalozos** [comment]
Hi @iramsey85 I cannot tell you if you should take down the entire infrastructure and bring it up when you need it or if you should delete it entirely and set it up from scratch, this depends on your use case. However, I 'd like to offer some thoughts on scaling the infrastructure. The cost of the k8s infrastructure comes mainly from the worker nodes; you are expected to have enough of those to host your deployments. You could scale the workers down at low demand periods and spin up more worker nodes to handle more load. There is the charmscaler charm (https://jujucharms.com/charmscaler/) that could help in worker scaling but I have never used it. To figure out the right number and type of workers you should look at the hosted pods. If for example you host an API and your bottleneck is the tcp connections you would better go for smaller type of nodes but in larger numbers. Also, when you scale up your infrastructure you should make sure that the hosted deployments are scaled up as well and the pods are rescheduled after the new worker nodes are ready. This will allow you to spread the load across all workers.

**Comment by iramsey85** [comment]
Thanks @ktsakalozos. Based on what I've read so far, it doesn't look like taking down my entire infrasructure and bringing it back online is an option at all. Do you think this is that case?

**Comment by ktsakalozos** [comment]
Machines setup with juju should be be able to survive restarts. Stopping and then starting them later should work as long as they get the same IP after a reboot. I did a quick test on aws (deploy, stop, start) and it seems machines did not get the same IP so the controller was not accessible.
