### ISSUE TITLE
AWS Deployment -

### ISSUE THREAD

**Issue by iramsey85** [juju-solutions/bundle-canonical-kubernetes#435]
During deployment to AWS, I get an error when the install is trying to configure Native AWS Integration. I checked the "step-03_enable-cni.err" file and get the output below. Am I missing a configuration setting on my end?

IAM policy juju-kubernetes-master already exists
IAM policy juju-kubernetes-worker already exists
IAM role juju-kubernetes-master already exists
IAM role juju-kubernetes-worker already exists
Instance profile juju-kubernetes-master already exists
Instance profile juju-kubernetes-worker already exists
IAM policy juju-kubernetes-master attached to IAM role juju-kubernetes-master
IAM policy juju-kubernetes-worker attached to IAM role juju-kubernetes-worker
IAM role juju-kubernetes-master already on instance profile juju-kubernetes-master
IAM role juju-kubernetes-worker already on instance profile juju-kubernetes-worker
Instance i-052d4eace5cc7bb31 (i-052d4eace5cc7bb31) associated with profile juju-kubernetes-master: iip-assoc-056436f5b77cc28eb
Instance i-048e20ba678c9ac23 (i-048e20ba678c9ac23) associated with profile juju-kubernetes-worker: iip-assoc-05e1060c320b51853
Instance i-0b94266a53d491ed8 (i-0b94266a53d491ed8) associated with profile juju-kubernetes-worker: iip-assoc-0e9a390e0ca231385
Removed KubernetesCluster tag from sg-92844504 for kubernetes-master
Removed KubernetesCluster tag from sg-738243e5
sg-92844504 for kubernetes-worker
Created tag KubernetesCluster=conjure-canonical-kubern-ddf-xnzu on i-052d4eace5cc7bb31  sg-738243e5
sg-92844504
Created tag KubernetesCluster=conjure-canonical-kubern-ddf-xnzu on i-048e20ba678c9ac23 i-0b94266a53d491ed8  sg-738243e5
sg-92844504

An error occurred (MissingParameter) when calling the CreateTags operation: The request must contain the parameter resourceIdSet

**Comment by tvansteenburgh** [comment]
@iramsey85 Is your deployment going into a vpc, or is it a really old aws account that predates vpc? I've seen deployments fail in strange ways when not in a vpc. Shot in the dark but figured I'd ask.

**Comment by iramsey85** [comment]
I believe i'm deploying into the EC2-Classic platform. I'm using an IAM account and I believe the admin account holder created the account a week ago.

**Comment by iramsey85** [comment]
I resolved this issue by launching an instance within the aws console. I was then able to execute my spell deployment from my local machine.
