### ISSUE TITLE
Support for launching p3 instances

### ISSUE THREAD

**Issue by dvavili** [juju-solutions/bundle-canonical-kubernetes#437]
Need support to launch P3 instances on AWS

**Comment by marcoceppi** [comment]
This needs to be filed with Juju, which is the tool used to provision instances and such. I've opened the following: https://bugs.launchpad.net/juju/+bug/1730122

**Comment by marcoceppi** [comment]
As well, here's a PR to address this: https://github.com/juju/juju/pull/8022 which should hopefully end up being in juju 2.3

**Comment by tvansteenburgh** [comment]
Closing here, please track the juju bug referenced above.

**Comment by marcoceppi** [comment]
This is available in Juju 2.3 beta3 and will be GA shortly
