### ISSUE TITLE
does CDK need to expose kubernetes-worker?

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bundle-canonical-kubernetes#446]
We currently expose the k8s-worker here(ish):

https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/master/fragments/k8s/cdk/bundle.yaml#L32

But workers are related to `kubeapi-load-balancer`.  It feels like the LB should route ingress traffic to the workers for us.  If that's true, then we should stop exposing workers.

I'm not sure how to test ingress, but i'd be happy to kick the tires on unexposed workers if someone can give me a test case.

**Comment by marcoceppi** [comment]
That's what you would think, butts not the case. We could write a custom load balancer in k8s that would configure the kube-api-loadbalancer but that would be a custom solution

**Comment by kwmonroe** [comment]
Fair enough. Against my better judgement, i'm going to trust @marcoceppi and close this out.  We can revisit if someone has an actual requirement to un-expose the workers in the future.

**Comment by marcoceppi** [comment]
We could do something like this with Envoy, where we juju deploy it then
connect it into k8s. It's a good idea, just not how our cluster works
