### ISSUE TITLE
Allow increase of nginx's proxy_read_timeout value in the apilb

### ISSUE THREAD

**Issue by mmiller1** [juju-solutions/bundle-canonical-kubernetes#450]
The default value of 90 causes long running api calls, such as tailing logs, and interactive 'kubectl exec' commands to close too soon, leaving many errors like the following in the nginx error logs:

[error] 4910#4910: *2459737 upstream timed out (110: Connection timed out) while reading upstream, client: <worker_ipaddress>, server: _, request: "GET /api/v1/services?resourceVersion=5098949&timeoutSeconds=476&watch=true HTTP/2.0", upstream: "https://<master_ipaddress>:6443/api/v1/services?resourceVersion=5098949&timeoutSeconds=476&watch=true", host: "<worker_fqdn>:443"

I bumped these up manually to 660 and have not seen the errors since (along with a `chattr +i sites-available/apilb` to keep juju from reverting it)

Can this be configured somewhere so that the changes are not overridden?

**Comment by wwwtyro** [comment]
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/461
