### ISSUE TITLE
Support load-balancer failover

### ISSUE THREAD

**Issue by boucherv** [juju-solutions/bundle-canonical-kubernetes#453]
For the moment, the canonical-kubernetes bundle support only the high availability of the kubernetes-master by adding a load-balancer. If this load-balancer unit doesn't work (machine down etc..) kubernetes will be no longer reachable! So, It's a Single Point of Failure (**SPOF**) .. It's not fine for a "production deployment".

To avoid that, we can add a **virtual IP** in front of load-balancers (same as OpenStack canonical bundle): 
![image](https://user-images.githubusercontent.com/13995481/33842205-e35060be-de67-11e7-948e-e352e9e00a9b.png)

I have started work on this subject, I will upload the code soon.

**Comment by marcoceppi** [comment]
Thanks for lodging this issue, it's a limitation we've known about for some time, but have yet to address completely.

I was always under the impression that a vIP only works on bare metal deployments - would this vIP also be portable to public clouds, etc?

**Comment by boucherv** [comment]
Yes, it's true the vIP is mainly for bare metal deployments - public clouds have lot of mechanism to support failover and high availability (if depend of the cloud provider solution). For example, Amazon provide directly a [load-balancer with failover ](https://aws.amazon.com/fr/elasticloadbalancing/).

So, if you want to do generic bundle (for both public cloud and baremetal) it isn't easy to support loadbalancer failover on both platform. Each cloud provider have their own mechanism and the vIP solution is mainly for bare-metal.

For you what is the best way to have a real production bundle (with load-balancer failover) ?

**Comment by marcoceppi** [comment]
I think it's worth doing this for kube-api-loadbalancer - honestly we should just make a kube-api-lb that works directly with clouds and make the default one work on bare metal/on-prem

**Comment by boucherv** [comment]
Yes it's true! I started the work for this change #458 .. Tell me the next step

**Comment by tvansteenburgh** [comment]
This is now supported via the keepalived charm: https://github.com/juju-solutions/charm-keepalived
