### ISSUE TITLE
hostPort does not work

### ISSUE THREAD

**Issue by falfaro** [juju-solutions/bundle-canonical-kubernetes#456]
I've deployed this 9-machine bundle into a KVM-virtualized environment managed by MAAS. After deployment, I feed the following manifest to Kubernetes:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-host
spec:
  containers:
  - image: caseydavenport/nginx
    imagePullPolicy: IfNotPresent
    name: nginx-host
    ports:
    - containerPort: 80
      hostPort: 8081
  restartPolicy: Always

My expectation would be that the Kubernetes node where the Pod is deployed creates a port mapping between port 8081 on the host and port 80 on the container, but that is not the case. No port on the host is ever made available. Is this related to using Flannel and CNI?

**Comment by Cynerva** [comment]
Aye, hostPort doesn't work when using CNI. See https://github.com/kubernetes/kubernetes/issues/23920 (long read)

Actually, it looks like they fixed this upstream with CNI 0.6.0 (which we already ship), but we need to update our CNI configurations to include the `portMap` plugin. See [this example](https://github.com/kubernetes/kubernetes/blob/0cddb6b0973f50c9f5bce59e02986d855975aaef/cluster/addons/calico-policy-controller/calico-node-daemonset.yaml#L118-L122) - note the .conflist extension and the portMap plugin definition.

Here's the config we currently ship for Flannel: https://github.com/juju-solutions/charm-flannel/blob/master/templates/10-flannel.conf

**Comment by Cynerva** [comment]
Our workaround has been to use hostNetwork: true instead of hostPort, e.g. [here](https://github.com/kubernetes/kubernetes/blob/722cb7a758d4678e7ed5c4f09ded99d6bc5b0b4c/cluster/juju/layers/kubernetes-worker/templates/ingress-replication-controller.yaml#L149).

I'mma work on the proper fix, though, and hopefully get that out with our next release.

**Comment by falfaro** [comment]
Any idea when these changes will be available in the Charm store?

**Comment by falfaro** [comment]
Alternatively, I guess I just need to build the flannel Charm myself locally and use that in my bundle, right? I've never built a Charm myself. Any quick pointers?

**Comment by Cynerva** [comment]
A test build with this fix is currently on the charm store in my namespace, at `cs:~cynerva/flannel-5` (or `cs:~cynerva/flannel` channel edge).

Keep in mind on some clouds, if you intend to use hostPort and access that port from outside the cluster, you'll need to expose the port with `juju run --unit kubernetes-worker/0 open-port 12345` for whichever worker unit hosts the pod.

Hopefully in about an hour here, we'll get this pushed to the ~containers namespace's edge channels. With any luck, we might be able to get this out to stable later this week. Worst case, early January.

**Comment by marcoceppi** [comment]
@Cynerva if you're using hostPort on a public cloud, does flannel check the API server for which ports should be opened and do the `open-port` or will users just need to do that still themselves?

**Comment by Cynerva** [comment]
> if you're using hostPort on a public cloud, does flannel check the API server for which ports should be opened and do the open-port or will users just need to do that still themselves?

Users will need to do the open-port themselves. Having the flannel or kubernetes-worker charm do this intelligently is an interesting idea, but likely not as trivial as it sounds. I won't be pursuing it as part of this issue at least.

**Comment by Cynerva** [comment]
The fixes for this are now available on edge channels for `cs:~containers/flannel`, `cs:~containers/canal`, and `cs:~containers/calico`

**Comment by falfaro** [comment]
Fixes in cs:~containers/flannel-39 works for me. Thanks!
