### ISSUE TITLE
on gpu-enabled clusters, kubernetes-master hooks sometimes thrash forever

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#459]
See this [kubernetes-master debug-log output](https://gist.githubusercontent.com/Cynerva/90f4894e53ec9dacad28c01aa1625101/raw/6ceefde317d575da6c829b9c8ad71d7afdc63819/gistfile1.txt). A single hook gets stuck in a loop.

In the happy path, it goes like this:
1. `on_gpu_available` runs, setting `kubernetes-master.gpu.enabled` to true
2. `start_master` runs, sees `kubernetes-master.gpu.enabled` is set, and sets `kubernetes-master.privileged` to true
3. since `kubernetes-master.privileged` is true, `disable_gpu_mode` never runs.

In the failure case, `disable_gpu_mode` preempts start_master:
1. `on_gpu_available` runs, setting `kubernetes-master.gpu.enabled` to true
2. `disable_gpu_mode` runs, setting `kubernetes-master.gpu.enabled` to false
3. `start_master` runs, does not see `kubernetes-master.gpu.enabled`, so it sets `kubernetes-master.privileged` to false
4. `on_gpu_available` is eligible to run again, so... repeat

**Comment by ktsakalozos** [comment]
Hi @CalvinHartwell, we often use gpu capable cloud instances to develop the respective set of features.

**Comment by kwmonroe** [comment]
I've hit this a few times (1 in 5) when deploying to a p2.xlarge in AWS.  When the hook starts-a-flappin, this workaround has been good to me:

```
juju run --unit kubernetes-master/0 'service snap.kube-apiserver.daemon restart'
```

**Comment by ktsakalozos** [comment]
We addressed this as part of the work we did on GPU support.
