### ISSUE TITLE
Set k8s master to non schedulable

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#46]
In the current design all nodes are schedulable. So if the master must be rebooted for some maintenance reason, it will need a drain then an uncordon to work again. 

Could we have an option to make it unschedulable so that the actual workloads run only on the worker nodes instead of a mix? (this also allows for running master on smaller units)

**Comment by chuckbutler** [comment]
We are in the process of refactoring out the control plane into separate charms. 

This will effectively make the control plane un-scheduleable and only nodes will run the workloads, but we're still cycling on this during the sprint this week.

**Comment by chuckbutler** [comment]
This is now invalid, as hyperkube is not the delivery mechanism. Master's do not run workloads
