### ISSUE TITLE
Configurable kubeapi-load-balancer `proxy_read_timeout` to prevent `kubectl exec` sessions from terminating after 90 seconds

### ISSUE THREAD

**Issue by eric-sonchaiwanich** [juju-solutions/bundle-canonical-kubernetes#461]
Requesting that
1) Validation that setting proxy_read_timeout is an acceptable solution to prevent session timeouts, and
2) Making proxy_read_timeout a configurable setting on the charm/bundle

The intention is to allow `kubectl exec` sessions to not timeout after 90 seconds.  A common use case is running a shell session in a container for troubleshooting/debugging.  Examples of running interactive shell sessions might be:
```
kubectl exec -n mynamespace mycontainer -ti -- bash
kubectl exec -n mynamespace mydatabasecontainer -ti -- psql
```
The default nginx configuration causes these shell sessions to become disconnected after 90 seconds if no user input is received (even if there is console output), which is problematic.

It appears that making this change extends the timeout from 90 seconds to 1 hour:

In `/var/lib/juju/agents/unit-kubeapi-load-balancer-2/charm/templates/apilb.conf`

Change  `proxy_read_timeout      90;` -----> `proxy_read_timeout      3600;`

So far, I haven't seen any adverse effects due to this change.  Would we expect any adverse affects, and if not, can this be made configurable?

**Comment by Cynerva** [comment]
I can't think of any adverse effects, though I haven't looked into it too deeply.

It seems like making this configurable would be good. Not sure when we'll get around to it.

**Comment by wwwtyro** [comment]
Here's a PR: https://github.com/kubernetes/kubernetes/pull/57926

Haven't tested it yet, I'll try to sneak it in on Monday.

**Comment by wwwtyro** [comment]
@eric-sonchaiwanich A fix has been committed and will be available in the next release. For an early look, feel free to deploy from edge.
