### ISSUE TITLE
Set up log rotation to /var/log/nginx

### ISSUE THREAD

**Issue by alejdg** [juju-solutions/bundle-canonical-kubernetes#463]
The current kubernetes loadbalancer charm only has logrotate configuration for the apilib found /var/log/nginx/*.log. There is still the nginx logs found /var/log/nginx.{access,error}.log which aren't rotated. 

The charm should handle these logs.

**Comment by hyperbolic2346** [comment]
This was added to the charm with [this commit](https://github.com/kubernetes/kubernetes/commit/57059ea4428265cdea7e4c79646ad476fe79fcd8#diff-62515902f2f0b074724269361a1c42b3) back in December. Are you having trouble with it still? What version of the charm are you running?
