### ISSUE TITLE
Need an easy way to provide enterprise level-authentication

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#465]
The default authentication mechanism for kubernetes uses a CSV file in /root/cdk/known_tokens.csv. 

Almost every enterprise customer will require: LDAP, Kerberos, OAUTH (or another mechanism) for user authentication. Making it easier to integrate with these protocols/technologies will be a big win for CDK as almost every enterprise customer will want it. 

My suggestion is we either containerize/charm DEX or do something with an existing tool to make it easier to deploy/run/use. Documentation should also be updated to reflect this. Feel free to ask questions.

**Comment by tvansteenburgh** [comment]
We now support LDAP via Keystone, see https://www.ubuntu.com/kubernetes/docs/ldap.
