### ISSUE TITLE
Support encryption at rest for secrets in Kubernetes

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#466]
Customers may choose to use Kubernetes to store their secrets, however, we do not currently support encryption at rest as part of CDK. This saves them from having to setup a separate vault instance. 

We should enable this and make sure it works as some customers will most certainly want to use this as part of their CD/CI pipeline. 

Also this functionality is quite common in other SOA like Hadoop, and would blend very nicely with Kubeflow. 

FYI this requirement comes from the European Union. There may be ways around this, I.E disk encryption on the host (such as LUKS) but this isn't clear yet. 

If this is supported and enabled, the documentation should be updated.

**Comment by caio1982** [comment]
We will be deploying Vault on our own in a fully on-prem setup exactly because CDK does not support it yet, it would be amazing if it did and I could save some time from doing it manually and apart from CDK.

**Comment by tvansteenburgh** [comment]
@caio1982 Thanks for the feedback. We will be working on Vault integration for CDK very soon. In the meantime you might want to check out the Vault charm (https://jujucharms.com/u/openstack-charmers/vault/1). At least you could `juju deploy vault` or add it to your bundle rather than deploying it manually.

**Comment by tvansteenburgh** [comment]
This is now supported, see https://www.ubuntu.com/kubernetes/docs/encryption-at-rest.
