### ISSUE TITLE
Docs issue: Heapster, Grafana, and Influx

### ISSUE THREAD

**Issue by japhar81** [juju-solutions/bundle-canonical-kubernetes#472]
The docs do a great job of walking you thru proxying your way to the K8S dashboard, but are absent on how to get to grafana, heapster, and influx. I stumbled my way onto a way to pull up an empty grafana page on a kubernetes-core deploy, which I can't even find my way back to now, and everything was throwing 502's, so no data was showing.

If anyone has any tips on how to actually make it work, I'd be glad to write it up and PR some docs.

**Comment by japhar81** [comment]
Sorry, found the link. So you can get to grafana here;
http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/?orgId=1&editview=settings

But, no data appears. Query URLs like the below throw a 502;
http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/api/datasources/proxy/1/query?db=k8s&q=SHOW TAG VALUES FROM "uptime" WITH KEY = "nodename"&epoch=ms

**Comment by ktsakalozos** [comment]
Hi @japhar81, apologies for the late response.

To get the metrics show-up on the dashboard you will need to change the influxdb url in the respective data source. Data sources are available at http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/datasources . In the influxdb-datasource under the "Http Settings" change the "url" from http://monitoring-influxdb:8086 to http://localhost:8086 . Grafana and InfluxDB are in the same pod and here we tell grafana to use the local influxdb to populate its graphs.

This is a known issue and we have a PR already in place, so in the next release you should not need to redo this configuration. We are also looking into properly documenting the steps to reach the self-hosted grafana service.

**Comment by ktsakalozos** [comment]
Here is a wiki page describing the different monitoring options for CDK: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Monitoring-Solutions

**Comment by japhar81** [comment]
Got it working -- thank you @ktsakalozos !
