### ISSUE TITLE
upgrade-charm may fail if start_worker runs before catch_change_in_creds

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bundle-canonical-kubernetes#474]
As reported in #juju on Jan 24, we may have old clusters out there that never did a kv.set from here:

https://github.com/kubernetes/kubernetes/commit/b134ce762165cd7742cde7fa695949a0ff1f1712#diff-25f2686437984f527090205ba417c242R140

If those clusters are upgraded, we may try to grab creds in `start_worker` before `catch_change_in_creds` has a chance to set them (meaning `creds` will be empty):

https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L355

This will lead to a failed `upgrade-charm` scenario like this (127-142):

https://paste.ubuntu.com/26454287/

One potential fix may be removing the `worker.auth.bootstrapped` state during `upgrade_charm`. This would prevent `start_worker` from running until `catch_change_in_creds` has set the credentials in the kv.

**Comment by ktsakalozos** [comment]
This should be fixed with the merged PR. Thank you @kwmonroe @hyperbolic2346
