### ISSUE TITLE
Adding extra san entries to master or load balancer results in error

### ISSUE THREAD

**Issue by hyperbolic2346** [juju-solutions/bundle-canonical-kubernetes#477]
`juju config kubernetes-master extra_sans="example.com"`
or
`juju config kubeapi-load-balancer extra_sans="example.com"`

results in error. See gists [here](https://gist.github.com/Cynerva/1bd6a98e98c8e5e9f2f028c86e61a748) and [here](https://gist.github.com/Cynerva/8833dd5bea8d9fa6bdef686ad4b03007)

**Comment by Cynerva** [comment]
Fix merged, and this bug never made it to stable, so I'mma go ahead and close this. Thanks for the fix.
