### ISSUE TITLE
Beats input in graylog not always starting.

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#479]
A few times the Beats input on graylog did not start after a deployment. We had to go to the graylog Inputs and start Beats manually. Did not have time to further debug, sorry.

**Comment by kwmonroe** [comment]
This may be fixed.  A couple days after this was reported, we updated the CDK spell so graylog/filebeat are properly related:

https://github.com/conjure-up/spells/pull/141

This should ensure the graylog beats input is configured:

https://git.launchpad.net/graylog-charm/tree/reactive/graylog.py#n277

Please retry with the current CDK spell to see if this is still an issue. Thanks!

**Comment by wwwtyro** [comment]
Failed attempted repro 3 times, closing as fixed.
