### ISSUE TITLE
Autoscaler with CDK v1.9

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#484]
Starting with v1.9 HPA uses new resource metrics API that is not available in CDK out of the box. If you want to use autoscaler you should do a:
```
$ juju config kubernetes-master controller-manager-extra-args="horizontal-pod-autoscaler-use-rest-clients=false"
```

Based on the discussion here https://github.com/kubernetes/kubernetes/issues/57673 we can either set the  --horizontal-pod-autoscaler-use-rest-clients=false or deploy this Metrics server: https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/

Issue reported here as well: https://github.com/kubernetes/kubernetes/issues/57996

**Comment by hyperbolic2346** [comment]
The metrics server is deployed by default in kube-up. I would think we should deploy it as well.

**Comment by ktsakalozos** [comment]
PR is merged, the fix should be available in the next release.
