### ISSUE TITLE
Adding multiple masters to the bundle/model is not reflected in the kube config

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#488]
Adding multiple masters to the bundle/model is not reflected in the kube config. How is the failover handled? Do DNS records or load balancer configuration need to be created or added? 🎱 

I suggest we add some more documentation around the failover/HA of each component in the cluster. 🐱

**Comment by ktsakalozos** [comment]
Adding more masters is reflected on the load balancer configuration. Your kube config file should be pointing to the load balancer not the masters, right? The load balancer will automatically take out of circulation any unresponsive masters.

+1 for the documentation

**Comment by CalvinHartwell** [comment]
> Adding more masters is reflected on the load balancer configuration. Your kube config file should be pointing to the load balancer not the masters, right? The load balancer will automatically take out of circulation any unresponsive masters.

It was reported by a customer and I've not had a chance to test it yet myself but if it is already handled by the load balancer, we're good.

**Comment by boucherv** [comment]
I @CalvinHartwell  if depend of your deployment (baremetal or virtual). If you deploy on baremetal you need an ip failover component to avoid the load-balancer SPOF! An issue was already open for that #453 and one pull request is under review #458 !

**Comment by wwwtyro** [comment]
@CalvinHartwell This appears resolved by @ktsakalozos's response. Please reopen if you need to.
