### ISSUE TITLE
LXD deployments and proxy-extra-args="proxy-mode=userspace"

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#505]
On LXD deployments pods cannot talk to services using the service Cluster IP. A workaround for this is to configure kube proxy with proxy-mode=userspace.

```
juju config kubernetes-worker proxy-extra-args="proxy-mode=userspace"
```

**Comment by wwwtyro** [comment]
Feels like there's at least a couple solutions here:

1) Add this as a step to conjure-up spells.
2) Detect lxd context in the charm and add it there.

I'd vote for number one. If ya'll agree we can transfer this there.

**Comment by tvansteenburgh** [comment]
I agree, and we should also add it to https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD

It would also be nice to know why iptables routing doesn't work on lxd. Perhaps @stgraber could help us figure that out?

**Comment by ktsakalozos** [comment]
As discussed we will have a fix for this on conjure-up.
