### ISSUE TITLE
How to fix kubernetes release (including minor version)

### ISSUE THREAD

**Issue by boucherv** [juju-solutions/bundle-canonical-kubernetes#509]
Hello,

I want to fix kubernetes installed release but not only the major release (1.9 etc) also the minor one like (1.9.3). Currently, with the snaps channel (like 1.9/stable) you can fix major but visibly not minor.. What is the best way to do that ?

Thanks in advance,
Valentin

**Comment by wwwtyro** [comment]
This can be accomplished by installing the snaps as charm resources. You can use `snap download` to get the snaps and `juju attach` them to the relevant CDK charms.

**Comment by boucherv** [comment]
Ok thanks you for this advice!
