### ISSUE TITLE
Dashboard not always available on new cluster deployment?

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#512]
Hi all,

Every now and again the dashboard isn't being deployed, not sure why. If I try kubectl proxy, I get this error: 

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

Attempting to hit the dashboard on the kubectl cluster-info link gives a similar error. The strange thing is that this sometimes does work straight away, its really hit and miss.

Attempting to do things like http://127.0.0.1:8001/ui also doesn't work.  Trying this: 

```
juju config kubernetes-master enable-dashboard-addons=true
```

Gives me the message that the dashboard is already enabled. Any ideas?

**Comment by Cynerva** [comment]
Can you check on the kubernetes-dashboard pod?

```
kubectl get po -n kube-system
kubectl describe po -n kube-system <kubernetes-dashboard-pod-name>
kubectl logs -n kube-system <kubernetes-dashboard-pod-name>
```

**Comment by Cynerva** [comment]
I suspect this is the same issue as https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/512, which I just released a fix for. @CalvinHartwell please let us know if you continue to see problems with kubernetes-dashboard after existing clusters have had a chance to update.

**Comment by CalvinHartwell** [comment]
@Cynerva let me redeploy the cluster now and I'll check.

**Comment by tvansteenburgh** [comment]
@CalvinHartwell Okay to close this?
