### ISSUE TITLE
Kubernetes Dashboard Crashlooping

### ISSUE THREAD

**Issue by ernestmartinez** [juju-solutions/bundle-canonical-kubernetes#514]
Everything was fine last night. This morning I powered up my MAAS nodes and the kubernetes dashboard would error with:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"https:kubernetes-dashboard:\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

I destroyed the model and re-deployed the bundle, but same issue.
CDK-FA logs attached.

[results-2018-03-13-13-01-34.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1807909/results-2018-03-13-13-01-34.tar.gz)

**Comment by Cynerva** [comment]
We released Kubernetes 1.9.4 to stable channels yesterday, and it seems kubernetes-dashboard broke with that release. I'm looking into it.

**Comment by Cynerva** [comment]
Fix here: https://github.com/juju-solutions/cdk-addons/pull/29

Merged, tested, released to stable. This should fix itself on existing clusters within the next day or so when snapd auto-refreshes the cdk-addons snap to revision 364.

**Comment by Cynerva** [comment]
Closing, please reopen if you continue to see problems after existing clusters have had a chance to upgrade.

**Comment by CalvinHartwell** [comment]
@Cynerva is there a reason why this is not covered by the automated test suites? We should not ship a new release if this is broken.

**Comment by CalvinHartwell** [comment]
Appears to be working now for me. Thanks!
