### ISSUE TITLE
not able to install juju with snap install juju --classic

### ISSUE THREAD

**Issue by naveenkumartangallapally** [juju-solutions/bundle-canonical-kubernetes#518]
i am not able to install juju with snap install juju --classic command.

am getting below error:

root@juju:~# snap install juju --classic
error: cannot install "juju": cannot get nonce from store: Post
       https://api.snapcraft.io/api/v1/snaps/auth/nonces: net/http: request canceled while waiting
       for connection (Client.Timeout exceeded while awaiting headers)

**Comment by tvansteenburgh** [comment]
Please file a bug on the juju project: https://bugs.launchpad.net/juju
