### ISSUE TITLE
"upgrade" action does not work with resources

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#528]
Attached a new kubelet snap and ran `juju run-action kubernetes-worker/0 upgrade`. It did not actually upgrade to the new snap.

I'm pretty sure the calls to `any_file_changed` in [kubernetes-worker](https://github.com/kubernetes/kubernetes/blob/cad4385cb07c470833953fbb117a29a584a33762/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L159) and [layer-snap](https://github.com/stub42/layer-snap/blob/d0161902e8b7746de1f9411221d50ba7d4e1aa49/lib/charms/layer/snap.py#L127) are conflicting with eachother, resulting in a noop.

kubernetes-master is likely affected by this, too.

**Comment by serngawy** [comment]
I have seen the same issue with kubernetes-master and kubernetes-worker

**Comment by Cynerva** [comment]
Fix merged and released, thanks @ktsakalozos for reminding me to close this.
