### ISSUE TITLE
Constraints not satisfiable in azure cloud.

### ISSUE THREAD

**Issue by Pekkari** [juju-solutions/bundle-canonical-kubernetes#536]
constraints: cores=4 mem=4G for workers is a kind of vm not existing in azure. It's possible to
find 4 cores, 8 gigs, or 4 cores, 16g, depending on the region, not all would have them.

**Comment by ktsakalozos** [comment]
Hi @Pekkari ,

These constraints should be the minimum requirements. Juju should be able to instantiate a VM with at least those resources. Are you getting an error when deploying on Azure?

**Comment by CalvinHartwell** [comment]
> These constraints should be the minimum requirements. Juju should be able to instantiate a VM with at least those resources. Are you getting an error when deploying on Azure?


Hi Kos,

Essentially the default constraints are not enough for building clusters on Azure, so juju deploy canonical-kubernetes does not work on Azure, it generates errors as they do not seem to have an instance type which matches the default constraints. This also varies per data-center, as default flavours/sizes of machines are available, just like on AWS.

**Comment by ktsakalozos** [comment]
To the best of my knowledge a constraint "cores=4 mem=4G" results in a machine with at least those resources. This means that on Azure (and on any cloud) depending on the region you should get VMs with 4 cores & 8G, or 4 cores & 16G. If this is not the case we should gather the error logs and escalate the issue to Juju.

Do you have any logs showing the error?

**Comment by Pekkari** [comment]
From azure, it's possible to read the following errors:

The requested size for resource '/subscriptions/026941fe-e52c-4334-ac8f-71c31ed83d4e/resourceGroups/juju-default-model-c072f60a-030e-43fe-8e12-2b5d37653bb7/providers/Microsoft.Compute/virtualMachines/machine-13' is currently not available in location 'uksouth' zones '' for subscription '026941fe-e52c-4334-ac8f-71c31ed83d4e'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.

I'll reproduce again to bring some of the juju outputs.

**Comment by CalvinHartwell** [comment]
@ktsakalozos perhaps this is an error with juju itself? Even if we remove the default constraints (so juju should attempt to satisfy them), we get this error output. Of course we can fix it by specifying instance types per service or much higher values for the constraints, I.E 16gb of ram and 8 cores per service, but we would it to be easier to deploy on Azure.

**Comment by ktsakalozos** [comment]
It does indeed look like an issue with Juju. It seems it cannot get the specs of the instance types and therefore it cannot map the constraints we provide to a proper VM. Can you please open a ticket against juju (https://bugs.launchpad.net/juju)?

**Comment by CalvinHartwell** [comment]
@ktsakalozos any chance you could do this for us?

**Comment by ktsakalozos** [comment]
Just came back from vacations. Thank you for opening the ticket, @CalvinHartwell.

**Comment by CalvinHartwell** [comment]
> Just came back from vacations. Thank you for opening the ticket, @CalvinHartwell.

No worries Kos, I actually was working with the bundle builder today and it seems to add sufficient ram, cores, etc by default. Maybe we should generally suggest that route for Azure builds. Issue is open with juju team so I will close this issue.
