### ISSUE TITLE
Monitoring stack does not work on Microsoft Azure

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#540]
Hi all,

It appears that the monitoring stack does not seem to work on Microsoft Azure.  The Grafana dashboard is there but the metrics are not filling up. We had a similar problem on OVH and managed to fix this using hosts files because the resolution of nodes was messed up for Prometheus. 

IMO this seems to be the only component in the system which requires DNS resolution, but it should work out of the box on Azure as it works perfectly on AWS. Logging and monitoring was configured using this: 

[https://github.com/CalvinHartwell/canonical-kubernetes-demos/tree/master/cdk-logging-and-monitoring](https://github.com/CalvinHartwell/canonical-kubernetes-demos/tree/master/cdk-logging-and-monitoring)

Cheers

**Comment by kwmonroe** [comment]
I was able to get the prometheus/grafana bits working on Azure:

![screen shot 2018-04-05 at 4 43 19 pm](https://user-images.githubusercontent.com/4576822/38393475-86e9f036-38f0-11e8-9089-0ed12c493e54.png)

I had 2 problems:
- Default azure instance size is too small.  Prometheus and grafana didn't like 1.6G of memory.  I deployed to 4G machines and it went better.
- Grafana charm revisions < 11 would not properly execute the `import-dashboard` actions. I pushed revision 11 to the beta channel of the charm store, which should resolve this:

https://jujucharms.com/grafana/11

@CalvinHartwell would you please verify you are using machines with more than 2G ram and the following charm revs:

```
App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
grafana                         active       1  grafana                jujucharms   11  ubuntu  exposed
prometheus                      active       1  prometheus             jujucharms    5  ubuntu
telegraf                        active       4  telegraf               jujucharms   11  ubuntu
```

**Comment by CalvinHartwell** [comment]
@kwmonroe are you able to share the _exact_ versions of the charms you used just for reference? 

I just tried with Grafana v11 and it is now LGTM, I will confirm with customer tomorrow. :+1: :zap: 

[https://github.com/CalvinHartwell/canonical-kubernetes-demos/blob/master/cdk-logging-and-monitoring/cdk-logging-monitoring.yaml](https://github.com/CalvinHartwell/canonical-kubernetes-demos/blob/master/cdk-logging-and-monitoring/cdk-logging-monitoring.yaml)

**Comment by kwmonroe** [comment]
@CalvinHartwell i'll do one better than giving you my exact charm revisions:

https://github.com/CalvinHartwell/canonical-kubernetes-demos/pull/1

This sets our latest known-good charms for 1.9/stable, adds minimum constraints so things like graylog/prometheus/elasticsearch (and k8s components) come up nicely, and simplifies some post-deployment graylog config.

Best of all, it works ootb with azure:

![screen shot 2018-04-07 at 1 21 42 pm](https://user-images.githubusercontent.com/4576822/38458744-4348d874-3a67-11e8-9b68-d57a90ad0443.png)

Or at least it does for me ;)

**Comment by CalvinHartwell** [comment]
@kwmonroe thanks for the help - I see you forked my demo(s) repo to this account which is good, we need to make one which is more official. This issue now resolved and we can close it. The Azure monitoring and logging is now working perfectly.
