### ISSUE TITLE
CI: CNI failure when etcd connection_string changes

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bundle-canonical-kubernetes#544]
This is sporadic, but has come up a few times in CI.  The dashboard gives a 504 in bundletester:

https://ci.kubernetes.juju.solutions/job/test-cdk/628/testReport/junit/(root)/bundle/40_security_check_py/
```
FAIL: test_basic (__main__.IntegrationTest)
Test the effect of changing the admin password
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bundletester-Lwl7QJ/canonical-kubernetes/tests/40-security-check.py", line 77, in test_basic
    self.assertEqual(status, 200)
AssertionError: 504 != 200
```

Turns out this a problem with kubedns:
```
$ kubectl get po -n kube-system
NAME                                             READY     STATUS    RESTARTS   AGE
heapster-v1.5.0-dbc674964-8rdl8                  4/4       Running   0          14h
kube-dns-5c6c5b55b-jz9c8                         0/3       Error     0          15h
kubernetes-dashboard-7d5dcdb6d9-mjfnr            1/1       Running   0          15h
metrics-server-v0.2.1-7486f5bd67-g8v9c           2/2       Running   0          14h
monitoring-influxdb-grafana-v4-6d67c7f4f-s8flh   2/2       Running   0          15h

$ kubectl describe po kube-dns-5c6c5b55b-jz9c8 -n kube-system|tail
...
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                       Message
  ----     ------                  ----                  ----                       -------
  Warning  FailedCreatePodSandBox  55m (x1126 over 1h)   kubelet, ip-172-31-68-203  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-5c6c5b55b-jz9c8_kube-system" network: open /run/flannel/subnet.env: no such file or directory
```

Check out the flanneld process on the kube-dns node.  It only has 1 etcd-endpoint, even though there's a cluster of 3 etcds:
```
$ ps -ef | grep -i flan
root      1586     1  0 14:25 ?        00:00:00 /usr/local/bin/flanneld -iface=ens5 -etcd-endpoints=https://172.31.76.203:2379 -etcd-certfile=/etc/ssl/flannel/client-cert.pem -etcd-keyfile=/etc/ssl/flannel/client-key.pem -etcd-cafile=/etc/ssl/flannel/client-ca.pe
m
```

I suspect this flannel unit came up when the etcd deployment first started, and only etcd/0 was available. This is a problem because by now, other etcds have joined the cluster, but our flannel still only knows about etcd/0.  This means `etcd.tls.available` and `flannel.service.installed` are still true, so the the flannel template never gets re-rendered to pick up the current etcd connection string:

https://github.com/juju-solutions/charm-flannel/blob/master/reactive/flannel.py#L125

Here's where we go sideways. During the bundletester run, we remove the etcd leader:

https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/master/tests/20-charm-validation.py#L182

So etcd/0 gets removed by the test and our flannel stops working because it can't reach the only etcd-endpoint that it knows about.  This causes kube-dns to error, which causes the dashboard to stop working.

Again, this is sporadic because the moon and stars have to align -- the kubedns pod has to be running on the worker which has flannel running against a single etcd unit when that unit is removed.

I suggest we fix this by finding an appropriate handler (or adding a new one) to ensure the flannel template is up2date with the current etcd connection string... Then, do something like:
```python
if charms.reactive.helpers.data_changed('flannel_etcd_connections', etcd.get_connection_string())
    remove_state('flannel.service.installed')
```

Edit: we may need to `.sort()` the connection string stored by `data_changed` to prevent ordering issues from triggering a re-render of the flannel template.

Edit 2: on closer look, it doesn't seem like we'll need to `.sort` because the etcd members are already sorted:

https://github.com/juju-solutions/layer-etcd/blob/master/reactive/etcd.py#L208

**Comment by ktsakalozos** [comment]
The sorting of etcd endpoints is already in place: https://github.com/juju-solutions/layer-etcd/blob/master/reactive/etcd.py#L208
