### ISSUE TITLE
Kube-system services running with one pod

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#568]
Consider the case of DNS. When we update the cdk-addon manifest (with for example a new dns image) there is a small period where there is no dns running. We should review the proposed manifests and make sure critical services are always available.

**Comment by Cynerva** [comment]
I think the upgrade concern may be addressed by the `rollingUpdate.maxUnavailable` setting that's in the kube-dns spec: https://github.com/kubernetes/kubernetes/blob/v1.9.7/cluster/addons/dns/kube-dns.yaml.in#L76

Raising the replicas would still be good for failure tolerance though, I think.

**Comment by tvansteenburgh** [comment]
Closing as I don't think there's actually a problem here.
