### ISSUE TITLE
hook failed during deployment : "kube-control-relation-changed" for kubernetes-master:kube-control

### ISSUE THREAD

**Issue by yaumeg** [juju-solutions/bundle-canonical-kubernetes#570]
Hi,

I have a kubernetes-core deployment with the master stuck in the state "Waiting for kube-system pods to start" and a hook failed error on each of my workers: hook failed: "kube-control-relation-changed" for kubernetes-master:kube-control.

This setup runs on MAAS : master and easyrsa are vmware VMs and workers are physical machines.

This exact same setup was running fine for months, with multiple deployments without a single issue. I can't figure out what is going on ; only differences seems to be a new version of juju and kubernetes 1.9.7 instead of 1.9.6.

Also, it appears that kubelet and kube-proxy are not running  on workers :

`ps -ef | grep kube`

```
root      3672     1  0 May06 ?        00:00:00 bash /var/lib/juju/init/jujud-unit-kubernetes-worker-0/exec-start.sh
root      3677  3672  0 May06 ?        00:00:12 /var/lib/juju/tools/unit-kubernetes-worker-0/jujud unit --data-dir /var/lib/juju --unit-name kubernetes-worker/0 --debug
root     19399     1  0 May06 ?        00:01:55 /snap/kube-proxy/399/kube-proxy --cluster-cidr 10.1.0.0/16 --kubeconfig /root/cdk/kubeproxyconfig --logtostderr --master https://192.168.2.108:6443 --v 0
ubuntu   21456 21203  0 08:08 pts/0    00:00:00 grep --color=auto kube
```

Here is the full debug log :

[results-2018-05-07-07-05-46.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1978855/results-2018-05-07-07-05-46.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @yaumeg ,

Looking at the kubelet logs I see:
```
May 06 23:54:41 gpux1 kubelet.daemon[19744]: invalid argument "Accelerators=true,feature-gates=PersistentLocalVolumes=true,MountPropagation=true,VolumeScheduling=true" for --feature-gates: invalid value of feature-gates: PersistentLocalVolumes=true, err: strconv.ParseBool: parsing "PersistentLocalVolumes=true": invalid syntax 
```
cloud this be the issue?

**Comment by ktsakalozos** [comment]
Your `kubelet-extra-args` in the kubernetes-worker configuration should be:

```
feature-gates=Accelerators=true,PersistentLocalVolumes=true,MountPropagation=true,VolumeScheduling=true
```

**Comment by yaumeg** [comment]
You made my day, thank you !
