### ISSUE TITLE
Mismatch in kubernetes-master units in bundle vs. jujucharms.com text

### ISSUE THREAD

**Issue by mthaddon** [juju-solutions/bundle-canonical-kubernetes#571]
Looking at https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml I see 1 unit for kubernetes-master. However, on https://jujucharms.com/kubernetes under "Production cluster" (which leads me to a page that has that bundle on it)  2 masters, 3 workers, 3 etc nodes and API load balancer.

**Comment by CalvinHartwell** [comment]
Yes, this is supposed to be addressed in this PR: https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/549

**Comment by tvansteenburgh** [comment]
This has been resolved (bundle now contains 2 masters, 3 workers, 3 etcd).
