### ISSUE TITLE
Feature Request: CDK should have the ability to segregate logs and performance monitoring for namespaces (multi-tenancy)

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#574]
Hi all,

I have a request here to improve our multi-tenant model. Essentially the customer would like to have the ability to segregate our performance and log monitoring tools based on namespace/users/groups. 

For example, if you are a service provider and you have customer A, customer B and customer C using the same kubernetes cluster, each with their own namespaces. Each customer should not be able to view logs or performance data for each of the other customers clusters. 

Cheers,

- Calvin

**Comment by kwmonroe** [comment]
I know for sure that we can create dashboards based on the juju model.  We inject that key into the log entries here(ish):

https://github.com/juju-solutions/layer-filebeat/blob/master/templates/filebeat.yml#L17

I'll dig into the logs themselves to see if we can find a way to key off of k8s namespaces as well.

**Comment by kwmonroe** [comment]
Closing this in favor of #651. It'll be easier to move the elastic stack to 6.x and use the built in k8s metadata feature than it will be to determine/inject that same data in our current 5.x stack.
