### ISSUE TITLE
Feature Request: Option/Ability to use LEGO over easyrsa + self-signed certs

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#575]
Hi all, 

I think it would be really nice to use LEGO over self-signed certs and easyrsa, especially for clusters on public clouds (AWS, Azure, etc). [https://github.com/jetstack/kube-lego](https://github.com/jetstack/kube-legol). 

Perhaps this could be a flag or different bundle which replaces easyrsa with a LEGO component? 

Cheers

**Comment by hyperbolic2346** [comment]
The project is abandoned though, so I would be careful there. I have thought about using certmanager to handle the certs in the cluster though. We have a HA issue with easyrsa and a recovery issue.

**Comment by sfabel** [comment]
Vault is planned as the replacement for easyrsa

**Comment by CalvinHartwell** [comment]
@hyperbolic2346 if its abandoned we can scrap this idea. The main benefit I see from this is using certs which are already trusted by the OS and other systems out of the box instead of using a self-signed CA or paying Verisign etc to generate certs.

**Comment by hyperbolic2346** [comment]
@CalvinHartwell I completely understand and think we should do something better here as well. I just worry about using a project that is abandoned. We should use something, be it vault, cert manager or something else.

**Comment by wwwtyro** [comment]
I'm closing this because I don't think we plan to move towards LEGO. Please reopen if there's any argument otherwise, happy to discuss.
