### ISSUE TITLE
etcd scaling-up does not work after backup and restore.

### ISSUE THREAD

**Issue by lolwww** [juju-solutions/bundle-canonical-kubernetes#577]
Hi all, 

We performed a snapshot of etcd 2.X using the commands in the manual and on the charm here: 

[https://kubernetes.io/docs/getting-started-guides/ubuntu/backups/](https://kubernetes.io/docs/getting-started-guides/ubuntu/backups/)
[https://github.com/juju-solutions/layer-etcd](https://github.com/juju-solutions/layer-etcd)

```
# command used to take the snapshot
juju run-action etcd/0 snapshot
```

Our cluster is made up of 3 etcd units which are setup in a HA clustered configuration. The idea is we tried to replicate a cluster failure of CDK but not the controller machine, as that is in another data center. 

We tried to restore the snapshot in two ways: 

1) Deploy a full CDK cluster and power down the etcd2/3 nodes to leave one active node ready to have the snapshot restored. This did not seem to work at all and we could not see the data inside etcd using the etcdctl tool. 

2) The second method followed the manual closely, instead of redeploying the whole of CDK, we deployed a single instance of etcd and easyrsa with a relationship and then attempted to restore the cluster: 

After doing etcd snapshot and restoring this snapshot with:

```
juju attach etcd *filename* 
juju run-action etcd/3 restore 
```
And then trying to scale etcd application with the following command, we added two more units: 

```
juju add-unit etcd 
```

Eventually we get stuck, the cluster never achieves quorum for the three nodes and just hangs: 

```
Unit                      Workload     Agent      Machine  Public address                Ports                                    Message
apache2/0*                unknown      idle       5        infkc-prd-mon.p.cutekittens.net                                             
easyrsa/0*                active       idle       0/lxd/0  10.0.98.226                                                            Certificate Authority connected.
elasticsearch/0*          active       idle       5        infkc-prd-mon.p.cutekittens.net    9200/tcp                                 Ready
etcd/0*                   active       idle       2        infkc-prd-etcd1.p.cutekittens.net  2379/tcp                                 UnHealthy with 2 known peers
etcd/1                    error        idle       3        infkc-prd-etcd2.p.cutekittens.net  2379/tcp                                 hook failed: "cluster-relation-broken"
etcd/2                    error        idle       4        infkc-prd-etcd3.p.cutekittens.net                                        hook failed: "cluster-relation-broken"
grafana/0*                active       idle       5        infkc-prd-mon.p.cutekittens.net   3000/tcp                                 Started grafana-server
graylog/0*                error        idle       5        infkc-prd-mon.p.cutekittens.net    5044/tcp                                 hook failed: "website-relation-joined" for apache2:reverseproxy
```

I had a browse of the docs and the unit tests, I don't think they currently cover these two scenarios. We are currently redeploying with etcd3.2 to test again.

**Comment by CalvinHartwell** [comment]
+1 hitting this in the field with @lolwww in our team.

**Comment by CalvinHartwell** [comment]
Further investigation with etcd3 leads us to believe that the whole backup and restore scripts don't work properly for etcd3: 

```
# defines which backup mechanism is used 
ETCD_KEYS_VERSION=$(action-get keys-version)

...omitted

if [ "${ETCD_KEYS_VERSION}" == "v2" ]; then
  # Dump the data currently in the cluster
  /snap/bin/etcd.etcdctl backup --data-dir $ETCD_DATA_DIR --backup-dir $ETCD_BACKUP_TARGET_DIR/$JUJU_ACTION_UUID
elif [ "${ETCD_KEYS_VERSION}" == "v3" ]; then
  mkdir -p $ETCD_BACKUP_TARGET_DIR/$JUJU_ACTION_UUID
  cp $ETCD_DATA_DIR/member/snap/db $ETCD_BACKUP_TARGET_DIR/$JUJU_ACTION_UUID
else
  action-fail "keys-version must be either v2 or v3"
  exit
fi
```
[snapshot-code](https://raw.githubusercontent.com/juju-solutions/layer-etcd/15e6bfd6f206fcdf6c210923f78db56286c58ceb/actions/snapshot)

We constantly see that the ETCD_KEYS_VERSION variable is set to v2 and not v3 even when deploying etcd v3. More importantly, the snapshot command for v3 looks wrong: 

```
  mkdir -p $ETCD_BACKUP_TARGET_DIR/$JUJU_ACTION_UUID
 cp $ETCD_DATA_DIR/member/snap/db $ETCD_BACKUP_TARGET_DIR/$JUJU_ACTION_UUID
```

According to the manual, we should be using this command, but it throws an error: 

```
ubuntu@infkc-prd-etcd1:~$ ETCDCTL_API=3 etcdctl --insecure-skip-tls-verify=true snapshot save snapshot.db
Error:  rpc error: code = Internal desc = transport is closing
ubuntu@infkc-prd-etcd1:~$ ETCDCTL_API=3 etcdctl --insecure-skip-tls-verify=true --debug=true snapshot save snapshot.db
grpc: transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:55386->127.0.0.1:2379: read: connection reset by peer.
Error:  rpc error: code = Internal desc = transport: write tcp 127.0.0.1:55386->127.0.0.1:2379: write: broken pipe
ubuntu@infkc-prd-etcd1:~$ 
ubuntu@infkc-prd-etcd1:~$ ETCDCTL_API=3 etcdctl --insecure-skip-tls-verify=true --debug=true snapshot save snapshot.db
``` 
[https://coreos.com/etcd/docs/latest/op-guide/recovery.html](https://coreos.com/etcd/docs/latest/op-guide/recovery.html). 

Looks like this was related in the past: https://github.com/juju-solutions/layer-etcd/issues/94

**Comment by Cynerva** [comment]
> We constantly see that the ETCD_KEYS_VERSION variable is set to v2 and not v3 even when deploying etcd v3.

This is a parameter to the snapshot action, `keys-version`: https://github.com/juju-solutions/layer-etcd/blob/9fc8e32961e2586df3f4117c287e6150d0d5fca3/actions.yaml#L22-L25

**Comment by lolwww** [comment]
After changing v2 to v3 in actions yaml and running snapshot again we still get 
ETCD_KEYS_VERSION=v2 :
https://pastebin.canonical.com/p/Xqy2ksdMSR/

**Comment by ktsakalozos** [comment]
@lolwww can you show us how you trigger the action?

**Comment by ktsakalozos** [comment]
@lolwww based on https://docs.jujucharms.com/2.3/en/developer-actions#action-get if you trigger the action with `juju run-action snapshot keys-version="v3"` this line https://github.com/juju-solutions/layer-etcd/blob/master/actions/snapshot#L14 should set the ETCD_KEYS_VERSION to v3

**Comment by ktsakalozos** [comment]
This issue was resolved after some internal discussions. Calm down there is nothing wrong with the snapshot & restore actions. There are however a couple of points that we need to be aware of when taking snapshots and restoring them.

1. There are two etcd versions and you should consider each version as a separate datastore. Etcd v2 (from 2.x/stable channel) will store data in v2 format. Etcd v3 (from 3.x/channel) may have v2, v3 data or both. At some point you may want to migrate the v2 data to v3 but this is out of the scope of this issue. When we snapshot data we must be explicit what version (keys-version) we want to snapshot. Needless to say you cannot snapshot a v2 dataset restore it and expect it to be in the v3 format.

2. Etcd uses raft under the hood [1] this means that there is a leader elected among the etcd units. If there is no leader the etcd cluster becomes read-only. If at any point the leader looses majority vote a new one is elected. Therefore you should not be reusing any old etcd nodes when scaling up because they may gain majority and erase the data the more up-to-date leader has. Always scale up with `juju add-unit etcd`.

[1] https://www.youtube.com/watch?v=LAqyTyNUYSY
