### ISSUE TITLE
Upstream pod security policies and docs missing mention of apparmour

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#583]
Hi all,

The upstream pod security policies now available in kubernetes 1.10 only mention SELinux and not AppArmour: [https://kubernetes.io/docs/concepts/policy/pod-security-policy/#selinux](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#selinux). It is the same within Rancher 2.X as well. 

My suggestion is to contribute to PSP and add support for AppArmour, including adding to the upstream documentation for this. 

Cheers,

- Calvin

**Comment by tvansteenburgh** [comment]
There is now an AppArmor section here: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
