### ISSUE TITLE
unable to use eviction-hard config option via kubelet-extra-args charm option

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#601]
For example I am unable to use eviction-hard config option via kubelet-extra-args charm option.

The charm config in the bundle contains the following:

```
  kubernetes-worker:
    # ...
    options: |
                  system-reserved="memory=500Mi" eviction-hard=memory.available<650Mi
```

Due to the fact that kubelet's configure hook in the snap package uses -t option with snapctl I get "\u003c" put into /var/snap/kubelet/current/args instead of its unencoded version ("<"). This makes kubelet binary unhappy and prevents this config flag from being used. Quoting this in the charm config does not work.

This is a fairly important config option for production deployments - we need a way to set it.

See below for more details:

https://github.com/juju-solutions/release/blob/rye/snaps/snap/shared/generate-configure-hook#L19-L26
  value=$(snapctl get -t $key)

http://paste.ubuntu.com/p/BTJkDNqdvc/
```
* snap.kubelet.daemon.service - Service for snap application kubelet.daemon
   Loaded: loaded (/etc/systemd/system/snap.kubelet.daemon.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2018-06-28 16:14:16 CAT; 2s ago
  Process: 42927 ExecStart=/usr/bin/snap run kubelet.daemon (code=exited, status=255)
 Main PID: 42927 (code=exited, status=255)

Jun 28 16:14:16 redacted kubelet.daemon[42927]:   -v, --v Level                                                                                                   log level for V logs
Jun 28 16:14:16 redacted kubelet.daemon[42927]:       --version version[=true]                                                                                    Print version information and quit
Jun 28 16:14:16 redacted kubelet.daemon[42927]:       --vmodule moduleSpec                                                                                        comma-separated list of pattern=N setti
Jun 28 16:14:16 redacted kubelet.daemon[42927]:       --volume-plugin-dir string                                                                                  The full path of the directory in which
Jun 28 16:14:16 redacted kubelet.daemon[42927]:       --volume-stats-agg-period duration                                                                          Specifies interval for kubelet to calcu
Jun 28 16:14:16 redacted kubelet.daemon[42927]: F0628 16:14:16.582139   42927 server.go:145] invalid argument "memory.available\\u003c650Mi" for "--eviction-hard" flag: malformed pair, expect string<st
Jun 28 16:14:16 redacted systemd[1]: snap.kubelet.daemon.service: Service hold-off time over, scheduling restart.
Jun 28 16:14:16 redacted systemd[1]: Stopped Service for snap application kubelet.daemon.
Jun 28 16:14:16 redacted systemd[1]: snap.kubelet.daemon.service: Start request repeated too quickly.
Jun 28 16:14:16 redacted systemd[1]: Failed to start Service for snap application kubelet.daemon.

ubuntu@redacted (DB):~$ sudo snap run --shell kubelet 

root@redacted (DB):~# snapctl get eviction-hard
memory.available<650Mi
root@redacted (DB):~# snapctl get -t eviction-hard
"memory.available\u003c650Mi"
```

**Comment by dshcherb** [comment]
Similarly specifying **kube-reserved** and **system-reserved** command-line arguments on kubelet via kubelet-extra-args does not work as those parameters are specified with an equal sign between an argument and a value:

--<key>=<value>

https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/
https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/kubelet/apis/kubeletconfig/v1beta1/types.go#L422-L433

While the snap renders this:

--<key> <value>

**Comment by dshcherb** [comment]
Kubelet seems to have a different convention for command-line arguments (--<key>=<value> instead of --<key> <value>) as opposed to other binaries. This is problematic K8's documentation as well because only a few command-line arguments are visible in the CLI reference:

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by dshcherb** [comment]
As of 1.12 (and probably 1.11) we should use dynamic kubelet configuration in order to apply those settings instead of config flags passed via CLI.

https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#relationship-to-dynamic-kubelet-config

However, for older versions, handling kubelet config flag usage differences is necessary.

**Comment by Cynerva** [comment]
I'm looking into this now. Thanks for the detailed report.

**Comment by Cynerva** [comment]
A fix has been merged (thanks for making it easy @dshcherb). We'll need to build new snaps to include it, which we'll probably want to do for 1.11, 1.10 and 1.9.

**Comment by dshcherb** [comment]
@Cynerva 
Sounds good to me, thanks for the fix!

**Comment by Cynerva** [comment]
Fix has been released to stable channels, closing. You should be able to set `kubelet-extra-args=eviction-hard=memory.available<650Mi` in new deployments, or within the next 24 hours for existing deployments.

As for dynamic kubelet configuration, I've opened a new issue to follow up on that: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/605
