### ISSUE TITLE
Description of the CDK Bundle

### ISSUE THREAD

**Issue by hatched** [juju-solutions/bundle-canonical-kubernetes#611]
Original: https://github.com/CanonicalLtd/jujucharms.com/issues/533

While the https://jujucharms.com/canonical-kubernetes/ bundle is now 10 machines (with 2 master nodes now), the bundle description on that page does still state it's "A nine-machine Kubernetes cluster".
In addition, the same description error is in the bundle.yaml file itself.

**Comment by tvansteenburgh** [comment]
Thanks @hatched . I'm of the opinion that we should remove any references to "# of machines" since it'll always be subject to change.
