### ISSUE TITLE
Kubelet from kubernetes-core doesn't start up on lxd.

### ISSUE THREAD

**Issue by omalley** [juju-solutions/bundle-canonical-kubernetes#618]
When I use conjure-up kubernetes and pick kubernetes-core on lxd, the kubelet servers fail to come up. I suspect that part of their problem is that they aren't getting the arguments. From their logs:

```-- Logs begin at Tue 2018-07-24 17:46:11 UTC, end at Tue 2018-07-24 18:01:29 UTC. --
Jul 24 17:50:48 juju-b0c97b-1 systemd[1]: Started Service for snap application kubelet.daemon.
Jul 24 17:50:48 juju-b0c97b-1 kubelet.daemon[29420]: cat: /var/snap/kubelet/437/args: No such file or directory
Jul 24 17:50:51 juju-b0c97b-1 kubelet.daemon[29420]: I0724 17:50:51.629921   29420 server.go:408] Version: v1.11.1
Jul 24 17:50:51 juju-b0c97b-1 kubelet.daemon[29420]: I0724 17:50:51.632015   29420 plugins.go:97] No cloud provider specified.
Jul 24 17:50:51 juju-b0c97b-1 kubelet.daemon[29420]: W0724 17:50:51.632097   29420 server.go:549] standalone mode, no API client
```

The other kubernetes servers also have the same message about being unable to read their args files, but their processes stay up.

[results-2018-07-24-11-06-44.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2224834/results-2018-07-24-11-06-44.tar.gz)

**Comment by omalley** [comment]
I guess I should also say that I can cat the args file just fine from the command line.

```
root@juju-b0c97b-1:~# ls -l /var/snap/kubelet/437/args
-rw-r--r-- 1 root root 390 Jul 24 17:59 /var/snap/kubelet/437/args
```

**Comment by tvansteenburgh** [comment]
It looks like your lxd is using btrfs storage, is that right? If so, please see this comment: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/608#issuecomment-404165310

**Comment by omalley** [comment]
Yeah, I tried zfs first and found some pages that said that didn't work. *sigh*
I had switched to btrfs in hopes of getting around the problems.

**Comment by omalley** [comment]
ok, switching lxd to use the dir backend worked. I *still* get the message about the args file not being found, but things start up.

Given that zfs and btrfs are strongly encouraged as lxd backing stores, it would be good to check the backing store in the charms to prevent people wasting time diagnosing a known problem.

**Comment by tvansteenburgh** [comment]
Yeah, this kinda sucks right now. We should:

1. Update lxd docs to highlight these restrictions
2. Update charms to detect unsupported storage and fail gracefully
3. Make our kubernetes bundles work on zfs and btrfs

Ideally we would just skip straight to 3. But realistically I don't know how quickly we'll get there.
