### ISSUE TITLE
runtime option set to upstream uses dockerproject.org while docker switched to providing packages at docker.com

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#620]
It is possible to change the runtime option to "upstream" on kubernetes-worker to get the latest docker packages from the upstream apt repository, however, the URL used in the charm has **apt.dockerproject.org** in it which is no longer updated as packages are provided at **https://download.docker.com/linux/ubuntu**

https://github.com/juju-solutions/layer-docker/blob/4209bcf/reactive/docker.py#L231-L256

**Comment by joedborg** [comment]
https://github.com/juju-solutions/layer-docker/pull/125

**Comment by joedborg** [comment]
New repository added to charm.
