### ISSUE TITLE
docker-ce-version does not work for non-nvidia runtime configuration (docker version customization)

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#621]
Currently, docker-ce-version is only used when "runtime" is set to "nvidia" on kubernetes-worker.

https://github.com/juju-solutions/layer-docker/blob/4209bcf/reactive/docker.py#L49-L54

There should be options to:

1. specify a docker apt repo;
2. specify a GPG key used by that repo;
2. specify a package name and a version to pin to.

This will allow users to replace rather dated docker versions if they are using a previously released LTS with contemporary ones or with docker-ee versions.

**Comment by joedborg** [comment]
Available in kubernetes-worker-398 and above
