### ISSUE TITLE
Pre-1.11 versions do not set --apiserver-count with --endpoint-reconciler-type master-count

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#622]
While 1.11 changed the reconciler type to `lease` from `master-count`, previous supported versions need to have `--apiserver-count` set to the number of kubernetes-master units.

https://github.com/kubernetes/kubernetes/blame/master/CHANGELOG-1.11.md#L417
https://github.com/kubernetes/kubernetes/pull/63383

Otherwise 2 or more masters are not aware of each other and are in conflict for making changes to etcd state.

https://github.com/kubernetes/kubernetes/issues/24327#issue-148618205
https://github.com/kubernetes/website/pull/6695/commits/97c9d23e30e49cad2c763706a873274f1230b1c8#diff-f1740b3dc59376d8eeb5d86fbb755bb6R207

> "If you do not add the `--apiserver-count` flag, the value defaults to 1. Your cluster will work correctly, but each apiserver replica will continuously try to add itself to the list of endpoints while removing the other ones, causing a lot of extraneous updates in kube-proxy and other components."

**Comment by hyperbolic2346** [comment]
Here are the options:
1. No code changes, document workaround
    * At this point we only support 1.9 - 1.11, and 1.11 is fixed, so in 2 releases this problem will phase itself out
    * The misconfiguration is wasteful in that it generates extra traffic and etcd activity in the cluster, but not catastrophic (does not cause data loss or corruption). The impact is minimal enough that the problem itself has gone largely unnoticed until now.
    * For those who do care, we will document the workaround, which is to set kube-api-extra-args appropriatly via charm config.
    * This is the quickest and easiest option.
2) Add a peer-relation so we can count the number of units
    * Adds complexity for an issue that no longer exists in Kubernetes.
    * Time-consuming - requires new code and testing
3) Use goal-state to determine the number of units
    * Requires juju >= 2.4
    * Feels like a tiny subset of older Kubernetes installations would have newest juju
    * Have to wait and monitor number of units to catch additions/removals
4) Set reconciler to lease for older Kubernetes.
    * Easy to do and quick
    * Lease reconciler wasn’t [bug-free](https://github.com/kubernetes/kubernetes/issues/63378) back then

**Comment by hyperbolic2346** [comment]
workaround would be 
```
juju config kubernetes-master api-extra-args="apiserver-count=<number of kubernetes master units>"
```

**Comment by dshcherb** [comment]
For new installations we would go for 1.11 anyway, however, if 1 is the easiest option for pre-1.11 it needs to be communicated through support channels and documented until 1.9 and 1.10 go EoL.

**Comment by tvansteenburgh** [comment]
1.9 and 1.10 are EoL now.
