### ISSUE TITLE
IPv6 disabled on kubeapi-loadbalancer machines leads to a charm error during installation

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#623]
IPv6 has been disabled on manually provisioned VMs and nginx-full package contained a default site that used a local IPv6 address which caused nginx service to fail to start which in turned stopped kubeapi-load-balancer charm from progressing further with installation.

```
apt install nginx-full
grep listen /etc/nginx/sites-enabled/default 
	listen 80 default_server;
	listen [::]:80 default_server;
# ...
```

This default site comes from the package itself.
https://git.launchpad.net/~usd-import-team/ubuntu/+source/nginx/tree/debian/conf/sites-available/default?h=applied/ubuntu/xenial-updates#n16

The charm should disable the default site in any case and this situation is yet another reason for it.

**Comment by joedborg** [comment]
https://github.com/battlemidget/juju-layer-nginx/pull/19

**Comment by joedborg** [comment]
Available from kubeapi-load-balancer-560
