### ISSUE TITLE
Default Number of Open File Descriptors is not tweaked (nofile softlimit is 1024)

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#626]
Currently the prlimit for the maximum number of open files is not tuned which results in problematic situations when apiserver runs out of file descriptors to use. Default softlimit:hardlimit for init process children is 1024:4096 unless set explicitly and 1024 may be quite low for large clusters.

The maximum number of kernel file handles (fs.file-max sysctl) is calculated by the kernel based on the amount of RAM with lower limit being NR_FILE (8192). Generally, it will be set to a reasonable value like this:

```
sysctl fs.file-max
fs.file-max = 3243822
```

http://kernel.ubuntu.com/git/ubuntu/ubuntu-xenial.git/tree/fs/file_table.c#n321
```
/*
 * One file with associated inode and dcache is very roughly 1K. Per default
 * do not use more than 10% of our memory for files.
 */
void __init files_maxfiles_init(void)
{
	unsigned long n;
	unsigned long memreserve = (totalram_pages - nr_free_pages()) * 3/2;

	memreserve = min(memreserve, totalram_pages - 1);
	n = ((totalram_pages - memreserve) * (PAGE_SIZE / 1024)) / 10;

	files_stat.max_files = max_t(unsigned long, n, NR_FILE);
} 
```
http://kernel.ubuntu.com/git/ubuntu/ubuntu-xenial.git/tree/include/uapi/linux/fs.h#n62
```#define NR_FILE  8192	/* this can well be larger on a larger system */```

https://elixir.bootlin.com/linux/v4.17.12/source/Documentation/sysctl/fs.txt#L91
> The value in file-max denotes the maximum number of file handles that the Linux kernel will allocate. When you get lots of error messages about running out of file handles, you might want to increase this limit.

Defaults for systemd children are taken from the kernel as well:
http://kernel.ubuntu.com/git/ubuntu/ubuntu-xenial.git/tree/include/uapi/linux/fs.h#n23
```
/* Fixed constants first: */
#define INR_OPEN_CUR 1024	/* Initial setting for nfile rlimits */
#define INR_OPEN_MAX 4096	/* Hard limit for nfile rlimits */
```

And can be viewed as follows:
```
systemctl show | grep NOFILE        
DefaultLimitNOFILE=4096
DefaultLimitNOFILESoft=1024
```

They can be redefined on a per-service (parent process + all children) basis so it would be a good idea to adjust those for `snap.kube-apiserver.daemon.service` by default via kubernetes-apiserver charm and provide a config option to modify the systemd service file based on the cluster needs.

if needed, adjust fs.file-max:

sysctl fs.file-max
sudo bash -c "echo 'fs.file-max = <newvalue>' >> /etc/sysctl.conf"
sysctl -p

And then also use `systemctl edit snap.kube-apiserver.daemon.service` to change this value for the service as it is spawned by systemd, e.g.

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties

```
systemctl edit snap.kube-apiserver.daemon.service
[Service]
LimitNOFILE=16384:16384
```

It might be also relevant to adjust this for worker nodes as well.

**Comment by joedborg** [comment]
https://github.com/juju-solutions/kubernetes/pull/198

**Comment by joedborg** [comment]
Available from kubernetes-master-542
