### ISSUE TITLE
Ceph relation join doesn't create necessary pools

### ISSUE THREAD

**Issue by hyperbolic2346** [juju-solutions/bundle-canonical-kubernetes#631]
When you relate ceph to the master, it requires two pools: xfs-pool and ext4-pool. It currently falls to the user to create these pools after relating ceph in order for things to work. The ceph relation has the ability to create pools now, but no way to check to see if the pool exists. The charms should create these pools when the relation is setup.

**Comment by Cynerva** [comment]
There's a default `rbd` pool, right? Can you use that?

**Comment by hyperbolic2346** [comment]
Yes, we could. I just had a feeling that people would want to segregate things, but I don't use Ceph yet so I'm not sure on this feeling.

**Comment by Cynerva** [comment]
Yeah, I don't know either. Seems like having separate pools would be nice, so you could see metrics on each pool individually or something. I dunno if there are any downsides. I just wanted to make sure you were aware of the default pool as an option.

**Comment by hyperbolic2346** [comment]
Yeah, I've thought about it and I even made the pool a variable so if we get nice support for the creation of pools we could expose it as a variable with a default of rbd and let people do what they want.

**Comment by grebennikov** [comment]
Let me bring up this issue again.
Just deployed k8s 1.13 with latest charms.
Add units are green and all necessary pods csi-rbdplugin-XXXX have been created.
However, the storageclasses created by juju expect to have pools to be created (ext4-pool and xfs-pool), which have never been created. Consequently, the volumes cannot be created either.

**Comment by Cynerva** [comment]
The workaround for now is to manually create the pools as described here: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/CDK-storage#relating-to-cdk

**Comment by Cynerva** [comment]
> To extend this even further.

Thanks. That looks like a separate issue, so I've opened a new one: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/710

**Comment by joedborg** [comment]
Released.  This will be in the release after 577.
