### ISSUE TITLE
kubernetes nodes "NotReady" 

### ISSUE THREAD

**Issue by kiroalbatrosa** [juju-solutions/bundle-canonical-kubernetes#633]
Hello all,

I have a problem with a kubernetes deployment on a bare-metal server. The deployment is on a ubuntu 16.06 server, using btrfs for lxd storage(same situation with zfs as well), using juju-2.0, kubernetes was deployed via "juju-2.3 bootstrap lxd lxd-test" and juju-2.3 deploy canonical-kubernetes.
The issue I have is that after the deployment, the workers and master are in a "waiting" status.  from "kubect get-nodes" it shows that they are all in "NotReady" status. 
I have tried creating the whole env. several times, but to no effect. After some debugging the nodes, i get the message that there is not enough disk space or there are no available nodes-at the same time, which I think might be the same issue as https://github.com/kubernetes/kubernetes/issues/28481. Also tried to deploy the kubernetes env via conjure-up, but i still get the same issue. I believe it might be something to do with the LXD configuration, though it should be correct, as I have set up the storage and the bridge adapter during the "lxd init" Attaching the required information from the CDK Field Agent.
I would really appreciate some assistance with this as I have gone through pretty much all the described issues out there that resemble the current one.
[results-2018-08-22-16-31-52.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2310700/results-2018-08-22-16-31-52.tar.gz)

**Comment by Cynerva** [comment]
> using btrfs for lxd storage(same situation with zfs as well)

**Comment by Cynerva** [comment]
> using btrfs for lxd storage(same situation with zfs as well)

This is a known issue with CDK on LXD - kubelet does not work on LXD when using either the `zfs` or `btrfs` storage backends. You have to use the `dir` storage backend instead.

**Comment by kiroalbatrosa** [comment]
Thank you ever so much :), no matter how much I looked around I did not come across this.

**Comment by kiroalbatrosa** [comment]
I weil rebuild the environment and let you know of the results.

**Comment by kiroalbatrosa** [comment]
Hi @Cynerva ,

I am still experiencing the same issue it seems on a fresh environment with "dir" as the storage backend, also additional details on the env that might not be relevant, i have mounted a RAID1 device in /var/lib/lxd for storage.
Nodes:
`NAME            STATUS     ROLES     AGE       VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
juju-b88e67-7   NotReady   <none>    5m        v1.11.2   10.76.73.216   <none>        Ubuntu 16.04.5 LTS   4.4.0-131-generic   docker://17.3.2
juju-b88e67-8   NotReady   <none>    1m        v1.11.2   10.76.73.119   <none>        Ubuntu 16.04.5 LTS   4.4.0-131-generic   docker://17.3.2`

Pods:
`NAME                                               READY     STATUS    RESTARTS   AGE       IP        NODE            NOMINATED NODE
default-http-backend-n5nlj                         0/1       Pending   0          5m        <none>    <none>          <none>
nginx-ingress-kubernetes-worker-controller-mt4qh   0/1       Pending   0          55s       <none>    juju-b88e67-8   <none>
nginx-ingress-kubernetes-worker-controller-pr8zl   0/1       Pending   0          5m        <none>    juju-b88e67-7   <none>`

Attaching the the CDK output from the current env.
[results-2018-08-23-15-30-16.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2314434/results-2018-08-23-15-30-16.tar.gz)

**Comment by Cynerva** [comment]
@kiroalbatrosa Ahh sorry. I think you need to apply the LXD profile here prior to deploying: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD#the-profile

**Comment by kiroalbatrosa** [comment]
@Cynerva , thank you for the info, I will try it and let you know of the results, just to make sure as far as I understastand, you are saying that I need to amend the profile after bootstraping before the juju deploy?

**Comment by kwmonroe** [comment]
@kiroalbatrosa your steps are correct:
```
juju bootstrap
juju add-model my-k8s-model
sed "s/##MODEL##/my-k8s-model/" </path/to/lxd-profile.yaml"> | \
    lxc profile edit juju-my-k8s-model
juju deploy canonical-kubernetes
```

That's probably the best method... However, just today, I forgot to edit my lxc profile prior to deployment and decided to try doing it afterwards (basically swapping the last 2 steps above).  After running `lxc profile edit`, i restarted my containers:
```
juju run --all 'sudo reboot'
```

And it worked!!  So, you can definitely modify the profile before deployment, but you might also have success with `lxc profile edit` and restarting containers post-deployment.

**Comment by kiroalbatrosa** [comment]
Thank you all for your assistance, it is much appreciated

**Comment by babarzahoor** [comment]
after using dir storage on lxd worked for me.

**Comment by rstribrn** [comment]
For those who face similar problem (nodes are NotReady), so kubelet isn't starting correctly.
I've spent several hours finding out that the kubelet isn't starting because of another reason.
Host server has to have this kernel parameter set:
```
vm.overcommit_memory=1
```

Relates to:
#https://github.com/kubernetes/kubernetes/issues/66241

More importantly, if you need to find the reason, try searching directly in kubelet's log:
```
juju ssh kubernetes-worker/0 "sudo snap logs kubelet -n 20000" | grep -A10 ": F"
```

My current setup:
1.) LXD cluster (lxd 4.9, juju 2.8.7) on VMWare, Ubuntu 20.04.1
2.) vagrant's "bento/ubuntu-20.04" image (on VirtualBox 6.1.16) + snap lxd 4.0.4 + snap juju 2.8.7 + charmed-kubernetes-559

**Comment by Cynerva** [comment]
@rstribrn it looks like you're hitting a known issue on LXD: https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1903566

A workaround is provided in the issue:
```
juju config kubernetes-worker kubelet-extra-config='{protectKernelDefaults: false}'
```

I recommend taking further discussion into the launchpad bug. We don't track github issues anymore.
