### ISSUE TITLE
New kubernetes-workers fails to register

### ISSUE THREAD

**Issue by tomerleib** [juju-solutions/bundle-canonical-kubernetes#634]
Hi,

I'm running CDK on AWS with the default setup (easyrsa, ectd, api-server, 1 master and 2 workers) plus the aws-integrator charm.
Scaling the cluster using add-unit works as expected, a new instance is launched and later being added to the kubernetes cluster.
However, if I'm doing a manual setup: launch a new instance manually, add it to juju cluster with juju add-machine and eventually run 
`juju add-unit kubernetes-worker --to $machine_id `

I can see that from Juju perspective (juju status) everything is fine, the relationships and installations completed successfully and the status is active and ready.
Checking it from Kubernetes side:
`kubectl get nodes`
Nothing new. I don't see the new machine listed.
Checking the kubelet logs on the new machine reveals that at first the node gets registered and later being deleted:
`kubelet_node_status.go:79] Attempting to register node ip-10-2-5-186.eu-west-1.compute.internal`
`kubelet_node_status.go:82] Successfully registered node ip-10-2-5-186.eu-west-1.compute.internal`
`apparmor="DENIED" operation="signal" profile="docker-default" pid=13480 comm="kubelet" requested_mask="receive" den
ied_mask="receive" signal=kill peer="snap.kubelet.daemon"`
`kubelet.daemon[13283]: 2018-08-27 14:58:11.094 [INFO][13729] client.go 202: Loading config from environment`
`kubelet.daemon[13283]: Calico CNI releasing IP address`
`kubelet.daemon[13283]: Calico CNI deleting device in netns /proc/10456/ns/net`
`kubelet.daemon[13283]: 2018-08-27 14:58:11.140 [INFO][13729] k8s.go 379: Teardown processing complete. Workload="kube-system.filebeat-28wp4"`
`dockerd[32292]: time="2018-08-27T14:58:11.216141637Z" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/7b44f4bbbd2e21df52b3b53b43fc79d58a4ee9816d63808
ae9b0e4d2a828f265: exec: \"auplink\": executable file not found in $PATH"`
`kubelet.daemon[13283]: I0827 14:58:11.457378   13283 watch.go:113] kubelet config controller: Node was deleted`
`kubelet.daemon[13283]: W0827 14:58:12.013368   13283 pod_container_deletor.go:75] Container "75a205979923560449aeb7c1e27947218c64ead53054c377aaad7fe952537f2f" not found in pod's con
tainers`
`kubelet.daemon[13283]: W0827 14:58:12.015280   13283 pod_container_deletor.go:75] Container "747ed41bb065a61a8ca96eaa3996515edd76edca10ce046103c1d4ad6dcd0742" not found in pod's con
tainers`
`kubelet.daemon[13283]: W0827 14:58:12.990533   13283 kubelet_getters.go:264] Path "/var/lib/kubelet/pods/962d9307-aa09-11e8-a46f-0a34a3b41e3c/volumes" does not exist`
`kubelet.daemon[13283]: E0827 14:58:19.162486   13283 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "ip-10-2-5-186.eu-west-1.compute.internal
": nodes "ip-10-2-5-186.eu-west-1.compute.internal" not found`
`kubelet.daemon[13283]: E0827 14:58:19.182710   13283 configsync.go:217] kubelet config controller: Node "ip-10-2-5-186.eu-west-1.compute.internal" does not exist in the informer's s
tore, can't sync config source`

This is where it enters a loop with the same last two messages: error getting node - node does not exists.
I've was able to reproduce it with several other machines, all using the same image of Ubuntu 16.04.5 and different instance-types.

**Comment by hyperbolic2346** [comment]
@tomerleib I'm not sure if you found documentation to fix this, but for future hunters, the way to fix this now is to use the aws-integrator charm or other integrator charms. Adding units will work properly once that is done.

The problem was that the charm didn't know how to properly set up the aws bits and wasn't able to do so without the credentials from juju. The integrator charms know how to do this and once you `juju trust` them they have the credentials necessary to do the work. The idea is that it is much easier to audit the integrator charms for security issues than having each charm get trusted with credentials.
