### ISSUE TITLE
RBAC breaks prometheus/grafana metric collection

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#635]
Hi all,

I am running my usual CDK bundle and I've recently started getting no metrics in Grafana for CDK on AWS. The node metrics are reporting in, but nothing k8s-specific is working, the dashboard is empty: [blob:https://imgur.com/69659eb7-339e-4d04-941e-f5657023ef70](https://imgur.com/69659eb7-339e-4d04-941e-f5657023ef70)

Here is the bundle: [https://gist.githubusercontent.com/CalvinHartwell/0345c416b2fc9e7aac3bae19cc6f04b1/raw/c4d8b2aa30a584a0e91f717570f88e9f6bfbde2e/prometheus-unhappy.yaml](https://gist.githubusercontent.com/CalvinHartwell/0345c416b2fc9e7aac3bae19cc6f04b1/raw/c4d8b2aa30a584a0e91f717570f88e9f6bfbde2e/prometheus-unhappy.yaml)

Here is the usual code for setting up the dashboards: [https://github.com/CanonicalLtd/canonical-kubernetes-demos/tree/master/cdk-monitoring-and-logging](https://github.com/CanonicalLtd/canonical-kubernetes-demos/tree/master/cdk-monitoring-and-logging)

I can do a cdk debug run if you want/need the tar, let me know.

**Comment by kwmonroe** [comment]
Looks ok on this end:

![screen shot 2018-08-28 at 4 56 03 pm](https://user-images.githubusercontent.com/4576822/44753494-e4ef8280-aae3-11e8-8fc1-d404336de43d.png)

Do your charm revisions match those?  Also note, that's plain 'ol prometheus.  I haven't tried prometheus2.

That said, if I had to guess, I would bet that you're being bitten by a recent update to grafana:

https://code.launchpad.net/~chris.sanders/grafana-charm/+git/grafana-charm/+merge/348122/comments/911924

The gist is that if your dashboard uses a metric that can't be found, the dashboard won't load at all.  I'd recommend looking in your debug-log for something like this:
```bash
$ juju debug-log --replay -i grafana/0 | grep Skipping
unit-grafana-0: 16:38:11 INFO unit.grafana/0.juju-log grafana-source:13: Skipping Dashboard Template: Swift.json.j2 no metric swift_replication_duration_seconds
unit-grafana-0: 16:38:11 INFO unit.grafana/0.juju-log grafana-source:13: Skipping Dashboard Template: CephOSD.json.j2 no metric ceph_osd_up
unit-grafana-0: 16:38:11 INFO unit.grafana/0.juju-log grafana-source:13: Skipping Dashboard Template: CephPools.json.j2 no metric ceph_pool_available_bytes
unit-grafana-0: 16:38:12 INFO unit.grafana/0.juju-log grafana-source:13: Skipping Dashboard Template: Telegraf.json.j2 no metric system_load1
...
```
I bet you'll find that your prometheus dashboard is getting skipped because it wants to use a metric that doesn't exist.  If that's the case, lock your script to an older grafana revision, or update your dashboard to omit the offending metric.

Let me know if that fixes you up.

**Comment by kwmonroe** [comment]
Closing out stale issues.  Feel free to reopen if this issue is still valid.

**Comment by CalvinHartwell** [comment]
OK, done a quick test, disabling RBAC: 

```
juju config kubernetes-master authorization-mode=""
```

Now disabled, configure the monitoring/logging stack. 

...and then re-enabling RBAC with the correct flags seems to work:

```
juju config kubernetes-master authorization-mode="RBAC,Node"
```

**Comment by CalvinHartwell** [comment]
@kwmonroe sorry I need to bump this up to high, because it is going to affect two customer deployments which are about to kick off this week/next week. 

I can't get the kubernetes-metrics dashboard in Prometheus to do anything now. Also when I deploy identical bundles on AWS/GCP, the deployment on AWS hangs, but the deployment on GCP continues. 

Here are the bundles: 
[GCP](https://gist.githubusercontent.com/CalvinHartwell/6be9654b025a3e6a9c34bb99503b60d0/raw/36f27e5195a27d9dd2901f549a5631bdc436c917/cdk-gcp-logging-monitoring-no-rbac.yamll)
[AWS](https://gist.githubusercontent.com/CalvinHartwell/2aeeb83ee653fea3f42757cc785bfb16/raw/69caf50f3c86774e7a0ff2fc33d90348c289bb53/cdk-aws-logging-monitoring-no-rbac.yaml)

Here is the juju status on GCP cluster:
[https://gist.githubusercontent.com/CalvinHartwell/a5afbebe592a08832de3a63c1b89ad4b/raw/54d85d57e4297518564ab4a06df7218064226991/gcp-cluster-juju-status](https://gist.githubusercontent.com/CalvinHartwell/a5afbebe592a08832de3a63c1b89ad4b/raw/54d85d57e4297518564ab4a06df7218064226991/gcp-cluster-juju-status)

Here is the juju status on AWS cluster (as you can see, eventually the graylog machine ends up with a status of 'DOWN' for some reason). 
[https://gist.githubusercontent.com/CalvinHartwell/e99c0a9fdfc37a2ae581623716208a9d/raw/db8ac1028d7e7b942eae7e689d7152eb8e243838/aws-monitoring-juju-status](https://gist.githubusercontent.com/CalvinHartwell/e99c0a9fdfc37a2ae581623716208a9d/raw/db8ac1028d7e7b942eae7e689d7152eb8e243838/aws-monitoring-juju-status)

The debug logs are attached:
[cdk-results-2018-10-19-00-41-56.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2493923/cdk-results-2018-10-19-00-41-56.tar.gz)
[gcp-results-2018-10-19-00-34-11.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2493908/gcp-results-2018-10-19-00-34-11.tar.gz)

**Comment by kwmonroe** [comment]
@CalvinHartwell graylog is almost assuredly failing on aws because there is no memory constraint in your bundle. Give graylog at least 3g ram. Aws gives you a tiny machine by default, gce does not.

This looks unrelated to the rbac issue here.

**Comment by CalvinHartwell** [comment]
Hi @kwmonroe 

> @CalvinHartwell graylog is almost assuredly failing on aws because there is no memory constraint in your bundle. Give graylog at least 3g ram. Aws gives you a tiny machine by default, gce does not.
> 
> This looks unrelated to the rbac issue here.
> 
> Edit: @CalvinHartwell, i confirmed mem constraints will fix your bundle on AWS. FYI, unconstrained units default to t3.micro instances (1GB RAM) in juju-2.4.4. Prior to that, you'd get an m3.medium (4GB RAM). Details on the change:
> 
> https://discourse.jujucharms.com/t/default-aws-instance-type-t3-micro-too-small/319/7
> 

Thanks for looking at this in short notice, the lack of memory thing makes sense. I did wonder why it was working before and then recently stopped working, thanks! 

> I'm still going to hold this open for RBAC. If you have additional problems with bundles that have rbac disabled, please open a new issue.

The reason I think its related is because I'm still getting the empty Kubernetes metrics dashboard in Grafana, just like when RBAC is enabled.

**Comment by kwmonroe** [comment]
In an rbac scenario, we may need to add a specific prometheus role -- @CalvinHartwell provided a good place to start with https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/prometheus/prometheus-rbac.yaml

**Comment by lolwww** [comment]
Kubectl apply -f wih yaml provided by @kwmonroe fixed the issue for me.
Thank you Kevin

**Comment by CalvinHartwell** [comment]
> The issue is that prometheus is (obviously) outside the k8s cluster, and scrapes node metrics from the api server by proxy. When the api server talks to nodes to be able to proxy their metrics, it authenticates with a `client.crt`. The common name of that cert (which is `client`) is the user that attempts to access metric URLs.

@Cynerva @kwmonroe this is really great work, thanks a lot for solving the issue. Regarding the 'client.crt' is that documented in the manual anywhere? I am quite surprised it ties the common name to a user within k8s itself. 

Thanks!

**Comment by kwmonroe** [comment]
> Regarding the 'client.crt' is that documented in the manual anywhere? I am quite surprised it ties the common name to a user within k8s itself.

@CalvinHartwell this was news to me as well.  However, it is mentioned in the k8s cert docs:

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs

_...the common name of the subject is used as the user name for the request..._

Luckily @Cynerva spotted the `client` string on my failing curl and pretty much instantly knew what was happening:
```bash
$ curl -k -H "Authorization: Bearer $TOK" https://172.31.1.69:443/api/v1/nodes/ip-172-31-25-18.us-west-1.compute.internal/proxy/metrics
Forbidden (user=client, verb=get, resource=nodes, subresource=metrics)
```

> I think me and Kevin had the same idea, that we could just create a service account with the correct permissions and it should work, but clearly not!

Yeah, the piece we were missing is that regardless of how we authenticated with the metric endpoint (password, service account, etc), the proxy was always going to get the metrics as the CN of the cert used to authenticate the request.

**Comment by kwmonroe** [comment]
This fix is available in `cs:~containers/kubernetes-master-511` or greater.  Closing out (finally!)

**Comment by CalvinHartwell** [comment]
@kwmonroe @Cynerva don't want to annoy you guys but I'm hitting the issue again both with the previous fix and the latest revision of the charms which is supposed to fix the issue (both with RBAC enabled and disabled, set to AlwaysAllow). 

I'm going to rebuild the environment tomorrow to be sure, I'm seeing: **_server returned HTTP status 503 Service Unavailable_** in prometheus for advisor metrics. I'll loop back tomorrow.

**Comment by CalvinHartwell** [comment]
@kwmonroe @Cynerva figured out my issue. Even though the prometheus targets are set by IP:

http://localhost:8001/api/v1/nodes/juju-a8a92d-5/proxy/metrics/cadvisor

The master servers try to resolve the cadvisor by hostname and if they cannot be resolved, they return the 503 error. To temporarily fix it, you can use /etc/hosts on each master node by putting in entries for each worker node. For a better fix, put static records for each kubernetes-worker in the local DNS server which is used by each node in the cluster. 

This works with both RBAC enabled/disabled, all good!
