### ISSUE TITLE
Docker IPTABLES Causing no networking for pods running on new nodes deployments 

### ISSUE THREAD

**Issue by AssafShaikevich** [juju-solutions/bundle-canonical-kubernetes#636]
*If your deployment is broken and you'd like help debugging it, please run our [CDK Field Agent](https://github.com/juju-solutions/cdk-field-agent) tool and attach the resulting tarball to this issue.*
The Story
Infra :
Juju version 2.3.7-xenial-amd64
ubuntu LTS 16.0.4.3 or 16.0.4.5 
Full HA Cluster of canonical kubernetes (2 masters ) (4 Nodes ) (3 ETCD servers )
All Servers on the same subnet
Docker version installed by the charm for new nodes - 17.03.2-ce
Docker version of the older nodes - 1.12.3
I have a cluster working for few months.
I add a new node to the cluster but the pods doesnt have network connectivity to other pods or outside the cluster.
I've verified the issue to be related to new versions of docker installed by apt-get install docker.io (during setup)
Turns our the default configuration for docker is to configure Chain Forward (Drop)
When manually configuring IPTABLES
iptables -P FORWARD ACCEPT 
All works ok but the chages Are reverting after restart.
Finally I was able to resolve this following this article : 
https://fralef.me/docker-and-iptables.html

seems like the script to exclude the docker controll of iptables needs to be included in the charm deployment or some other trick.

**Comment by AssafShaikevich** [comment]
yes im using worker version 59 , 
Thx ! , I will update the release.

**Comment by Cynerva** [comment]
Thanks for the update. Closing.
