### ISSUE TITLE
location of 

### ISSUE THREAD

**Issue by kiroalbatrosa** [juju-solutions/bundle-canonical-kubernetes#639]
Hi,
I have a kubernetes cluster(localhost) set up build with "juju bootsrtap" and "juju deploy canonical-kubernetes", all seems good after some initial troubleshooting and fixes. Now I want to set up authentication by using google OpenID using the documentation provided by google- https://cloud.google.com/community/tutorials/kubernetes-auth-openid-rbac. My question/issue is where is the kube-apiserver.yaml located at on the juju deploy? I have not been able to find it on the server or in the master/0 and master/1 machines as well. I apologize if this is covered somewhere else, but i was not able to come across that info.

**Comment by Cynerva** [comment]
There is no `kube-apiserver.yaml` in our distribution of Kubernetes, but you can do what you need here using `juju config`.

So where they tell you to edit `kube-apiserver.yaml` here:
```
sed -i "/- kube-apiserver/a\    - --oidc-issuer-url=https://accounts.google.com\n    - --oidc-username-claim=email\n    - --oidc-client-id=" /etc/kubernetes/manifests/kube-apiserver.yaml
```

you can instead accomplish this with:
```
juju config kubernetes-master api-extra-args="oidc-issuer-url=https://accounts.google.com oidc-username-claim=email oidc-client-id="
```

You can also view a full list of config options on kubernetes-master, with descriptions, by running:
```
juju config kubernetes-master
```
