### ISSUE TITLE
How to specify zone (cluster) for vSphere cloud

### ISSUE THREAD

**Issue by vasicvuk** [juju-solutions/bundle-canonical-kubernetes#641]
I could not find in documentation how to specify Zone (cluster) inside Bundle.yaml for Kubernetes. Is there some sample of specifying zone:
```
juju deploy ./bundle.yaml --to zone=Development
```
does not work because deploying a bundle does not allow to zone argument.

**Comment by ktsakalozos** [comment]
Hi @vasicvuk ,

Indeed you have to set the availability zone to each charm unit you are deploying. I am sure you have already seen the Juju docs at https://docs.jujucharms.com/2.4/en/charms-ha. Normally juju spread units across zones. AFAIK if you want to get the entire deployment in a single zone you should edit the `bundle.yaml` and introduce placement directives `--to zone=AZ`. I am not sure if there is a bootstrap parameter to express this kind of constraints. Which cloud are you on? There might be other options to get you the desired deployment.

**Comment by vasicvuk** [comment]
I am using Vmware vSphare provider. I have two clusters (zones) and i need to put charms on second called Development. If there is a possibility of adding --to zone in bundle can you give me an example?

**Comment by vasicvuk** [comment]
@ktsakalozos 
Since zone is cluster in vSphere cloud provider i guess cluster should be as an option inside of cloud provider configuration.

**Comment by ktsakalozos** [comment]
I do not know what to tell you about this @vasicvuk. I am not familiar with the vSphere provider. @kwmonroe might have a better view on this.

**Comment by tvansteenburgh** [comment]
More info on bootstrapping/deploying to a vsphere zone here: https://docs.jujucharms.com/2.5/en/clouds-vsphere

**Comment by vasicvuk** [comment]
@tvansteenburgh I dont know why you closed the issue since still there is no option to deploy a bundle inside specific Zone

**Comment by tvansteenburgh** [comment]
@vasicvuk Because you already opened a bug against Juju (https://bugs.launchpad.net/juju/+bug/1790185), which is where this problem must be fixed, not here.
