### ISSUE TITLE
calico/node fails to start with "Failed to reset devices.list"

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/bundle-canonical-kubernetes#643]
On arm64, I deployed calico along with our calico/node image:

https://hub.docker.com/r/cdkbot/node-arm64/

I used the lxc profile instructions from here:

https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD

The container failed to start (attempting to start it like `calico-node.service`):
```bash
docker run -ti --net=host --privileged \
  -e ETCD_ENDPOINTS=https://10.97.166.47:2379 \
  -e ETCD_CA_CERT_FILE=/opt/calicoctl/etcd-ca \
  -e ETCD_CERT_FILE=/opt/calicoctl/etcd-cert \
  -e ETCD_KEY_FILE=/opt/calicoctl/etcd-key \
  -e NODENAME=juju-b79169-0 \
  -e IP=10.97.166.223 \
  -e NO_DEFAULT_POOLS= \
  -e CALICO_LIBNETWORK_ENABLED=true \
  -e CALICO_NETWORKING_BACKEND=bird \
  -e FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT \
  -v /var/run/calico:/var/run/calico \
  -v /lib/modules:/lib/modules \
  -v /run/docker/plugins:/run/docker/plugins \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/log/calico:/var/log/calico \
  -v /opt/calicoctl:/opt/calicoctl \
  cdkbot/node-arm64:v2.6.10

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/1aaa827bab71064d319b45b694983c8971053ff2c004973f934c4cc1cef76912/devices.allow: operation not permitted\\\"\"": unknown.
```

I came across [an issue](https://github.com/lxc/lxd/issues/2004) that seemed related, and the resolution was to adjust the profile like this:
```diff
--- juju-default-model-profile.yaml     2018-08-28 15:25:08.662673873 +0000
+++ juju-calico-model-profile.yaml      2018-09-05 16:14:38.280526666 +0000
@@ -1,10 +1,10 @@
 config:
   boot.autostart: "true"
   linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
   raw.lxc: |
     lxc.apparmor.profile=unconfined
-    lxc.mount.auto=proc:rw sys:rw
+    lxc.mount.auto=proc:rw sys:rw cgroup:rw
+    lxc.cgroup.devices.allow=a
     lxc.cap.drop=
   security.nesting: "true"
   security.privileged: "true"
@@ -18,3 +18,4 @@
     path: /sys/module/apparmor/parameters/enabled
     source: /dev/null
     type: disk
```

This worked for me, but I'm not sure about the ramifications of changing our recommended lxc profile.  Here are my docker details on k8s-worker:
```bash
ubuntu@juju-b79169-0:~$ docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.10.1
 Git commit:    7390fc6
 Built: Wed Apr 18 01:26:37 2018
 OS/Arch:       linux/arm64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   7390fc6
  Built:        Wed Feb 28 17:46:05 2018
  OS/Arch:      linux/arm64
  Experimental: false
```

And lxd info on my host:
```bash
ubuntu@neander:~/arm-calico$ snap list | grep lxd
lxd   3.4      8418  stable    canonical✓      -
```

**Comment by Cynerva** [comment]
Whoa, this is the first I've heard of anyone successfully running a privileged docker container on LXD. Grats!

We generally have not been running calico or canal on LXD because of the privileged docker container, but it sounds like with the docker 17.12.1-ce you're running and the profile changes you've made, that limitation no longer applies.

I thought we were using a much earlier release of docker, though - like 17.03 or so.

**Comment by kwmonroe** [comment]
> Whoa, this is the first I've heard of anyone successfully running a privileged docker container on LXD

Yeah, i boosted an example from stackoverflow to make sure the profile changes were indeed responsible for letting me do privileged things:

Without the above profile changes:
```bash
ubuntu@neander:~$ juju ssh kubernetes-worker/0

## unprivileged
ubuntu@juju-b79169-0:~$ docker run -ti --rm ubuntu:latest bash
root@a50f8aba40e4:/# cat /proc/sys/vm/swappiness
60
root@a50f8aba40e4:/# echo "61" > /proc/sys/vm/swappiness
bash: /proc/sys/vm/swappiness: Read-only file system
root@a50f8aba40e4:/# exit

## privileged
ubuntu@juju-b79169-0:~$ docker run --privileged -ti --rm ubuntu:latest bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/9c8dd73492bbf4f444a28db8732e2d92c0bb4a9791c354361f68bc3af0a88b35/devices.allow: operation not permitted\\\"\"": unknown.
ubuntu@juju-b79169-0:~$
```

With the profile changes (and a k8s-worker reboot):
```bash
ubuntu@neander:~$ juju ssh kubernetes-worker/0

## unprivileged
ubuntu@juju-b79169-0:~$ docker run -ti --rm ubuntu:latest bash
root@3c6444cd2291:/# cat /proc/sys/vm/swappiness
60
root@3c6444cd2291:/# echo "61" > /proc/sys/vm/swappiness
bash: /proc/sys/vm/swappiness: Read-only file system
root@3c6444cd2291:/# exit

## privileged
ubuntu@juju-b79169-0:~$ docker run --privileged -ti --rm ubuntu:latest bash
root@bacde88f38a8:/# cat /proc/sys/vm/swappiness
60
root@bacde88f38a8:/# echo "61" > /proc/sys/vm/swappiness
root@bacde88f38a8:/# cat /proc/sys/vm/swappiness
61
root@bacde88f38a8:/# exit

## we modified the lxc container
ubuntu@juju-b79169-0:~$ cat /proc/sys/vm/swappiness
61
ubuntu@juju-b79169-0:~$ exit

## and the lxd host, ready for production ;)
ubuntu@neander:~$ cat /proc/sys/vm/swappiness
61
```

> I thought we were using a much earlier release of docker, though - like 17.03 or so.

I didn't do anything special to get 17.12.1 -- it came from [layer-docker](https://github.com/juju-solutions/layer-docker/blob/master/config.yaml#L46).

@Cynerva, does the new `cgroup:rw` and `lxc.cgroup.devices.allow=a` make you nervous?  We already say [Hands down, this is not a secure setup](https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD#conclusions), so I feel like we've given fair warning.  If you're cool, i'll use this issue to enumerate the places we reference cdk lxc profiles to add those couple lines.

**Comment by Cynerva** [comment]
> @Cynerva, does the new cgroup:rw and lxc.cgroup.devices.allow=a make you nervous? We already say Hands down, this is not a secure setup, so I feel like we've given fair warning.

Yeah, no concerns here. LXD profile is a mess already and I don't think this change makes it any worse. :+1:

**Comment by Cynerva** [comment]
I got docker 17.03.2-ce deploying kubernetes-core on AWS (xenial, amd64) so I dunno what that's about. For what it's worth, upstream has not validated Kubernetes 1.11 against docker 17.12.1 ([source](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md)):

> The validated docker versions are the same as for v1.10: 1.11.2 to 1.13.1 and 17.03.x

So you might see some weird issues or something. I dunno.

**Comment by kwmonroe** [comment]
> I got docker 17.03.2-ce when I deployed kubernetes-core on AWS (xenial, amd64)

Ahhhh, yup.  I'm using bionic:
```bash
$ apt-cache madison docker.io
 docker.io | 17.12.1-0ubuntu1 | http://ports.ubuntu.com/ubuntu-ports bionic/universe arm64 Packages
```

**Comment by kwmonroe** [comment]
Places that need the business:

- ~~[Kubernetes on ARM64 with CDK](https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Kubernetes-on-ARM64-with-CDK#modify-the-lxc-profile)~~
- [Deploying on LXD](https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD#the-profile)
- [conjure-up spell](https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/steps/00_process-providertype/lxd-profile.yaml)

**Comment by Cynerva** [comment]
Integration tests need it also: https://github.com/juju-solutions/kubernetes-jenkins/blob/master/integration-tests/templates/lxd-profile.yaml

**Comment by kwmonroe** [comment]
I think we got 'em all.  Closing out.
