### ISSUE TITLE
Current ETCD version we ship is not recommended for production cluster usage

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#647]
Hi all,

Can we please upgrade the version of etcd currently being shipped as it is not currently recommended for production use due to a number of bugs: 

[https://discuss.kubernetes.io/t/recommended-etcd-minimum-versions-3-1-11-3-2-10-3-3-0/2637/2](https://discuss.kubernetes.io/t/recommended-etcd-minimum-versions-3-1-11-3-2-10-3-3-0/2637/2)

We are currently shipping: 
`etcd                   3.2.9    active      3  etcd                   jujucharms  126  ubuntu  
`

Can we please get 3.2.10+ or 3.3.X instead? 

Cheers

**Comment by tvansteenburgh** [comment]
3.2.10 is now available in the `3.2/candidate` track for the etcd snap. Feel free to try this out with:

`juju config etcd channel=3.2/candidate`

Once 3.2.10 has passed our testing we'll push it to stable and update this issue.

**Comment by CalvinHartwell** [comment]
Thanks so much @tvansteenburgh !

**Comment by tvansteenburgh** [comment]
3.2.10 has been promoted to stable and 3.2/stable.
