### ISSUE TITLE
kubeapi-load-balancer default timeout might be too low

### ISSUE THREAD

**Issue by hloeung** [juju-solutions/bundle-canonical-kubernetes#650]
We have reported issues of what looks to be due to configured timeouts
with Nginx logging 'upstream timed out (110: Connection timed out)
while reading upstream'. See:

https://pastebin.canonical.com/p/c6QMpRw5HR/

The default kubeapi-load-balancer timeout is 90secs (proxy_read_timeout). Requests seems to be taking longer than this:

https://pastebin.canonical.com/p/GZY5xHrhkZ/

Also:

https://pastebin.canonical.com/p/sD9NbC67F5/

Obviously the logs above don't tell the full story. Feel free to reach out to one of us for more.

We've increased this to 10mins and it seems to have helped so far. Kubernetes has it's own application timeouts (&timeoutSeconds=XXX) and that seems to be 10mins per links below:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L76
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L234

Should the default proxy_read_timeout be increased to 10mins?

**Comment by Cynerva** [comment]
Fix merged, should be available in the charm's edge channel within the next 24 hours, and should go out with the next stable release in 2-3 weeks or so.

**Comment by tvansteenburgh** [comment]
Released in cs:~containers/kubeapi-load-balancer-161
