### ISSUE TITLE
EasyRSA does not run as an LXD container on 18.04

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#654]
Hey all,

When attempting to deploy the EasyRSA unit as an LXD container on 18.04 it doesn't work, looks like an easy fix though:

> unit-easyrsa-0: 13:39:08 DEBUG unit.easyrsa/0.install Building dependency tree...
> unit-easyrsa-0: 13:39:08 DEBUG unit.easyrsa/0.install Reading state information...
> unit-easyrsa-0: 13:39:08 DEBUG unit.easyrsa/0.install E: Unable to locate package python3-pip
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install Reading package lists...
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install Building dependency tree...
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install Reading state information...
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install E: Unable to locate package python3-pip
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install Traceback (most recent call last):
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install   File "/var/lib/juju/agents/unit-easyrsa-0/charm/hooks/install", line 8, in <module>
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install     basic.bootstrap_charm_deps()
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install   File "lib/charms/layer/basic.py", line 56, in bootstrap_charm_deps
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install     'python3-dev',
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install   File "lib/charms/layer/basic.py", line 187, in apt_install
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install     check_call(cmd + packages, env=env)
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install     raise CalledProcessError(retcode, cmd)
> unit-easyrsa-0: 13:39:18 DEBUG unit.easyrsa/0.install subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'python3-pip', 'python3-setuptools', 'python3-yaml', 'python3-dev']' returned non-zero exit status 100.
> unit-easyrsa-0: 13:39:18 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
> unit-easyrsa-0: 13:39:23 DEBUG unit.easyrsa/0.install Reading package lists...
> unit-easyrsa-0: 13:39:23 DEBUG unit.easyrsa/0.install Building dependency tree...
> unit-easyrsa-0: 13:39:23 DEBUG unit.easyrsa/0.install Reading state information...
> unit-easyrsa-0: 13:39:23 DEBUG unit.easyrsa/0.install E: Unable to locate package python3-pip
> unit-easyrsa-0: 13:39:28 DEBUG unit.easyrsa/0.install Reading package lists...
> unit-easyrsa-0: 13:39:28 DEBUG unit.easyrsa/0.install Building dependency tree...
> unit-easyrsa-0: 13:39:28 DEBUG unit.easyrsa/0.install Reading state information...
> unit-easyrsa-0: 13:39:28 DEBUG unit.easyrsa/0.install E: Unable to locate package python3-pip
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install Reading package lists...
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install Building dependency tree...
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install Reading state information...
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install E: Unable to locate package python3-pip
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install Traceback (most recent call last):
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install   File "/var/lib/juju/agents/unit-easyrsa-0/charm/hooks/install", line 8, in <module>
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install     basic.bootstrap_charm_deps()
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install   File "lib/charms/layer/basic.py", line 56, in bootstrap_charm_deps
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install     'python3-dev',
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install   File "lib/charms/layer/basic.py", line 187, in apt_install
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install     check_call(cmd + packages, env=env)
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install     raise CalledProcessError(retcode, cmd)
> unit-easyrsa-0: 13:39:34 DEBUG unit.easyrsa/0.install subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'python3-pip', 'python3-setuptools', 'python3-yaml', 'python3-dev']' returned non-zero exit status 100.
> unit-easyrsa-0: 13:39:34 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
> unit-easyrsa-0: 13:39:44 DEBUG unit.easyrsa/0.install Reading package lists...
> unit-easyrsa-0: 13:39:44 DEBUG unit.easyrsa/0.install Building dependency tree...
> unit-easyrsa-0: 13:39:44 DEBUG unit.easyrsa/0.install Reading state information...
> unit-easyrsa-0: 13:39:44 DEBUG unit.easyrsa/0.install E: Unable to locate package python3-pip
>

**Comment by tvansteenburgh** [comment]
@CalvinHartwell says easyrsa works fine on 18.04 if he doesn't put it in a lxd container.

**Comment by CalvinHartwell** [comment]
> @CalvinHartwell says easyrsa works fine on 18.04 if he doesn't put it in a lxd container.

Yup, ignoring the Ceph errors (no disks present), here is the issue juju status with easyRSA as an LXD container:

> odel   Controller     Cloud/Region   Version  SLA          Timestamp
> bionic  aws-eu-west-2  aws/eu-west-2  2.4.3    unsupported  15:03:44+01:00
> 
> App                    Version        Status   Scale  Charm                  Store       Rev  OS      Notes
> apache2                               unknown      1  apache2                jujucharms   26  ubuntu  exposed
> aws-integrator         1.15.71        active       1  aws-integrator         jujucharms    5  ubuntu
> canal                  0.10.0/2.6.10  blocked      5  canal                  jujucharms   67  ubuntu
> ceph-mon               12.2.4         active       3  ceph-mon               jujucharms   27  ubuntu
> ceph-osd               12.2.4         blocked      3  ceph-osd               jujucharms  270  ubuntu
> easyrsa                               error        1  easyrsa                jujucharms   68  ubuntu
> elasticsearch                         active       1  elasticsearch          jujucharms   30  ubuntu
> etcd                   3.2.10         blocked      3  etcd                   jujucharms  126  ubuntu
> filebeat               5.6.12         active       5  filebeat               jujucharms   19  ubuntu
> grafana                               active       1  grafana                jujucharms   20  ubuntu  exposed
> graylog                2.3.1-1        active       1  graylog                jujucharms   20  ubuntu
> kubeapi-load-balancer  1.14.0         active       1  kubeapi-load-balancer  jujucharms   88  ubuntu  exposed
> kubernetes-master      1.11.3         active       2  kubernetes-master      jujucharms  144  ubuntu
> kubernetes-worker      1.11.3         waiting      3  kubernetes-worker      jujucharms  163  ubuntu  exposed
> mongodb                3.6.3          active       1  mongodb                jujucharms   49  ubuntu
> prometheus                            active       1  prometheus2            jujucharms    8  ubuntu
> telegraf                              active       5  telegraf               jujucharms   19  ubuntu
> 
> Unit                      Workload  Agent      Machine  Public address  Ports                                    Message
> apache2/0*                unknown   idle       0        18.130.148.86
> aws-integrator/0*         active    idle       1        35.177.186.183                                           ready
> ceph-mon/0*               active    idle       11       18.130.185.134                                           Unit is ready and clustered
> ceph-mon/1                active    executing  12       18.130.130.5                                             Unit is ready and clustered
> ceph-mon/2                active    executing  13       18.130.102.6                                             Unit is ready and clustered
> ceph-osd/0*               blocked   idle       11       18.130.185.134                                           No block devices detected using current configuration
> ceph-osd/1                blocked   idle       12       18.130.130.5                                             No block devices detected using current configuration
> ceph-osd/2                blocked   executing  13       18.130.102.6                                             No block devices detected using current configuration
> easyrsa/0*                error     idle       9/lxd/0  252.14.165.162                                           hook failed: "install"
> elasticsearch/0*          active    idle       2        35.178.197.225  9200/tcp                                 Ready
> etcd/0                    blocked   idle       3        18.130.248.109                                           Missing relation to certificate authority.
> etcd/1                    blocked   idle       4        35.178.231.79                                            Missing relation to certificate authority.
> etcd/2*                   blocked   idle       5        18.130.89.107                                            Missing relation to certificate authority.
> grafana/0*                active    idle       6        18.130.237.90   3000/tcp                                 Started grafana-server
> graylog/0*                active    idle       7        35.178.202.19                                            Ready with: filebeat, elasticsearch, mongodb
> kubeapi-load-balancer/0*  active    idle       8        18.130.236.115                                           NGINX is ready
> kubernetes-master/0*      active    idle       9        35.178.212.197                                           Kubernetes master running.
>   canal/0*                blocked   idle                35.178.212.197                                           Waiting for relation to etcd
>   filebeat/0*             active    idle                35.178.212.197                                           Filebeat ready.
>   telegraf/0*             active    idle                35.178.212.197  9103/tcp                                 Monitoring kubernetes-master/0
> kubernetes-master/1       active    idle       10       18.130.254.52                                            Kubernetes master running.
>   canal/1                 blocked   idle                18.130.254.52                                            Waiting for relation to etcd
>   filebeat/1              active    idle                18.130.254.52                                            Filebeat ready.
>   telegraf/1              active    idle                18.130.254.52   9103/tcp                                 Monitoring kubernetes-master/1
> kubernetes-worker/0*      waiting   idle       11       18.130.185.134                                           Waiting for cluster DNS.
>   canal/2                 blocked   idle                18.130.185.134                                           Waiting for relation to etcd
>   filebeat/2              active    idle                18.130.185.134                                           Filebeat ready.
>   telegraf/2              active    idle                18.130.185.134  9103/tcp                                 Monitoring kubernetes-worker/0
> kubernetes-worker/1       waiting   executing  12       18.130.130.5                                             Waiting for cluster DNS.
>   canal/4                 blocked   executing           18.130.130.5                                             Waiting for relation to etcd
>   filebeat/4              active    idle                18.130.130.5                                             Filebeat ready.
>   telegraf/4              active    idle                18.130.130.5    9103/tcp                                 Monitoring kubernetes-worker/1
> kubernetes-worker/2       waiting   executing  13       18.130.102.6                                             Waiting for cluster DNS.
>   canal/3                 blocked   executing           18.130.102.6                                             Waiting for relation to etcd
>   filebeat/3              active    executing           18.130.102.6                                             Filebeat ready.
>   telegraf/3              active    idle                18.130.102.6    9103/tcp                                 Monitoring kubernetes-worker/2
> mongodb/0*                active    idle       14       18.130.93.116   27017/tcp,27019/tcp,27021/tcp,28017/tcp  Unit is ready
> prometheus/0*             active    idle       15       18.130.140.77   9090/tcp,12321/tcp                       Ready
> 
> Machine  State    DNS             Inst id              Series  AZ          Message
> 0        started  18.130.148.86   i-03dd2cb1f7379a9a1  bionic  eu-west-2a  running
> 1        started  35.177.186.183  i-0add9522cb9531d12  bionic  eu-west-2b  running
> 2        started  35.178.197.225  i-08189027bd8eba6d0  bionic  eu-west-2c  running
> 3        started  18.130.248.109  i-0fc4135b3bc540b9a  bionic  eu-west-2b  running
> 4        started  35.178.231.79   i-055b2840fcaf83d24  bionic  eu-west-2c  running
> 5        started  18.130.89.107   i-053e2fa4e7b1642f4  bionic  eu-west-2a  running
> 6        started  18.130.237.90   i-01984373948d6dc3a  bionic  eu-west-2a  running
> 7        started  35.178.202.19   i-02a0e6b7c2ea64814  bionic  eu-west-2b  running
> 8        started  18.130.236.115  i-020d3724e3e95d52b  bionic  eu-west-2b  running
> 9        started  35.178.212.197  i-035c06c9ede52f958  bionic  eu-west-2a  running
> 9/lxd/0  started  252.14.165.162  juju-19a844-9-lxd-0  bionic  eu-west-2a  Container started
> 10       started  18.130.254.52   i-04d34107ba213ac4e  bionic  eu-west-2b  running
> 11       started  18.130.185.134  i-055b5864e30416885  bionic  eu-west-2c  running

The status without the LXD container after 10-15 minutes:

> odel   Controller     Cloud/Region   Version  SLA          Timestamp
> bionic  aws-eu-west-2  aws/eu-west-2  2.4.3    unsupported  15:36:11+01:00
> 
> App                    Version        Status       Scale  Charm                  Store       Rev  OS      Notes
> apache2                               unknown          1  apache2                jujucharms   26  ubuntu  exposed
> aws-integrator         1.15.71        active           1  aws-integrator         jujucharms    5  ubuntu
> canal                  0.10.0/2.6.10  maintenance      5  canal                  jujucharms   67  ubuntu
> ceph-mon               12.2.4         active           3  ceph-mon               jujucharms   27  ubuntu
> ceph-osd               12.2.4         blocked          3  ceph-osd               jujucharms  270  ubuntu
> easyrsa                3.0.1          active           1  easyrsa                jujucharms   68  ubuntu
> elasticsearch                         active           1  elasticsearch          jujucharms   30  ubuntu
> etcd                   3.2.10         active           3  etcd                   jujucharms  126  ubuntu
> filebeat               5.6.12         active           5  filebeat               jujucharms   19  ubuntu
> grafana                               active           1  grafana                jujucharms   20  ubuntu  exposed
> graylog                2.3.1-1        active           1  graylog                jujucharms   20  ubuntu
> kubeapi-load-balancer  1.14.0         active           1  kubeapi-load-balancer  jujucharms   88  ubuntu  exposed
> kubernetes-master      1.11.3         waiting          2  kubernetes-master      jujucharms  144  ubuntu
> kubernetes-worker      1.11.3         active           3  kubernetes-worker      jujucharms  163  ubuntu  exposed
> mongodb                3.6.3          active           1  mongodb                jujucharms   49  ubuntu
> prometheus                            active           1  prometheus2            jujucharms    8  ubuntu
> telegraf                              active           5  telegraf               jujucharms   19  ubuntu
> 
> Unit                      Workload     Agent  Machine  Public address  Ports                                    Message
> apache2/0*                unknown      idle   0        35.177.146.4               
> aws-integrator/0*         active       idle   1        18.130.178.239                                           ready
> ceph-mon/0                active       idle   11       35.178.185.45                                            Unit is ready and clustered
> ceph-mon/1*               active       idle   12       35.178.231.34                                            Unit is ready and clustered
> ceph-mon/2                active       idle   13       35.177.7.219                                             Unit is ready and clustered
> ceph-osd/0*               blocked      idle   11       35.178.185.45                                            No block devices detected using current configuration
> ceph-osd/1                blocked      idle   12       35.178.231.34                                            No block devices detected using current configuration
> ceph-osd/2                blocked      idle   13       35.177.7.219                                             No block devices detected using current configuration
> easyrsa/0*                active       idle   9        18.130.196.166                                           Certificate Authority connected.
> elasticsearch/0*          active       idle   2        35.178.182.124  9200/tcp                                 Ready
> etcd/0                    active       idle   3        3.8.4.28        2379/tcp                                 Healthy with 3 known peers
> etcd/1                    active       idle   4        35.178.232.196  2379/tcp                                 Healthy with 3 known peers
> etcd/2*                   active       idle   5        18.130.242.139  2379/tcp                                 Healthy with 3 known peers
> grafana/0*                active       idle   6        3.8.6.13        3000/tcp                                 Started grafana-server
> graylog/0*                active       idle   7        18.130.229.92                                            Ready with: filebeat, elasticsearch, mongodb
> kubeapi-load-balancer/0*  active       idle   8        35.178.232.205  443/tcp                                  Loadbalancer ready.
> kubernetes-master/0       waiting      idle   9        18.130.196.166  6443/tcp                                 Waiting for kube-system pods to start
>   canal/1                 active       idle            18.130.196.166                                           Flannel subnet 10.1.6.1/24
>   filebeat/1              active       idle            18.130.196.166                                           Filebeat ready.
>   telegraf/1              active       idle            18.130.196.166  9103/tcp                                 Monitoring kubernetes-master/0
> kubernetes-master/1*      waiting      idle   10       18.130.196.161  6443/tcp                                 Waiting for kube-system pods to start
>   canal/0*                active       idle            18.130.196.161                                           Flannel subnet 10.1.38.1/24
>   filebeat/0*             active       idle            18.130.196.161                                           Filebeat ready.
>   telegraf/0*             active       idle            18.130.196.161  9103/tcp                                 Monitoring kubernetes-master/1
> kubernetes-worker/0*      active       idle   11       35.178.185.45   80/tcp,443/tcp                           Kubernetes worker running.
>   canal/4                 maintenance  idle            35.178.185.45                                            Deploying network policy controller.
>   filebeat/4              active       idle            35.178.185.45                                            Filebeat ready.
>   telegraf/4              active       idle            35.178.185.45   9103/tcp                                 Monitoring kubernetes-worker/0
> kubernetes-worker/1       active       idle   12       35.178.231.34   80/tcp,443/tcp                           Kubernetes worker running.
>   canal/2                 active       idle            35.178.231.34                                            Flannel subnet 10.1.67.1/24
>   filebeat/2              active       idle            35.178.231.34                                            Filebeat ready.
>   telegraf/2              active       idle            35.178.231.34   9103/tcp                                 Monitoring kubernetes-worker/1
> kubernetes-worker/2       active       idle   13       35.177.7.219    80/tcp,443/tcp                           Kubernetes worker running.
>   canal/3                 active       idle            35.177.7.219                                             Flannel subnet 10.1.83.1/24
>   filebeat/3              active       idle            35.177.7.219                                             Filebeat ready.
>   telegraf/3              active       idle            35.177.7.219    9103/tcp                                 Monitoring kubernetes-worker/2
> mongodb/0*                active       idle   14       3.8.1.147       27017/tcp,27019/tcp,27021/tcp,28017/tcp  Unit is ready
> prometheus/0*             active       idle   15       35.178.137.194  9090/tcp,12321/tcp                       Ready
> 
> Entity  Meter status  Message
> model   amber         user verification pending  
> 
> Machine  State    DNS             Inst id              Series  AZ          Message
> 0        started  35.177.146.4    i-0f0488bffdfb629a7  bionic  eu-west-2a  running
> 1        started  18.130.178.239  i-08fc6dcfe380bd640  bionic  eu-west-2b  running
> 2        started  35.178.182.124  i-048a5b4da5cc09fe1  bionic  eu-west-2c  running
> 3        started  3.8.4.28        i-00b121c045285168a  bionic  eu-west-2a  running
> 4        started  35.178.232.196  i-00d2c9b99f21c3b30  bionic  eu-west-2c  running
> 5        started  18.130.242.139  i-0f7ee3b31f57fe464  bionic  eu-west-2b  running
> 6        started  3.8.6.13        i-083cd871a0555e7e1  bionic  eu-west-2a  running
> 7        started  18.130.229.92   i-0cb4b0b52d9909c83  bionic  eu-west-2b  running
> 8        started  35.178.232.205  i-0d5af4e32ebe469c0  bionic  eu-west-2c  running
> 9        started  18.130.196.166  i-08471ca25ea7893dd  bionic  eu-west-2a  running

**Comment by Cynerva** [comment]
This looks to be a known issue in layer-basic: https://github.com/juju-solutions/layer-basic/issues/113

So far I haven't been able to reproduce it. I deployed on AWS, with bionic across the board, and easyrsa to lxd:0, but everything came up fine: https://gist.github.com/Cynerva/a9e3279ed2ac16262ae168de70a3fe05

Still looking into it.

**Comment by Cynerva** [comment]
@johnsca got a fix for this into layer-basic - thanks!

Fix is currently in edge channels of the charms, and will go out to stable hopefully within the next couple of weeks.

**Comment by CalvinHartwell** [comment]
Thanks for the update!

**Comment by tvansteenburgh** [comment]
Released in cs:~containers/easyrsa-114
