### ISSUE TITLE
kube-dns constantly restarting on 18.04

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundle-canonical-kubernetes#655]
We need to configure kubelet to use a different resolv.conf (see https://github.com/kubernetes/kubeadm/issues/273)

The proper way to do this is to check if /etc/resolv.conf on the worker is a symlink, and if it is, configure kubelet to use `--resolv-conf=/run/systemd/resolve/resolv.conf`

**Comment by kwmonroe** [comment]
Fixed in https://github.com/juju-solutions/kubernetes/pull/163

**Comment by tvansteenburgh** [comment]
Fixed in cs:~containers/kubernetes-worker-231
