### ISSUE TITLE
snapd_refresh charm option conflict

### ISSUE THREAD

**Issue by KellenRenshaw** [juju-solutions/bundle-canonical-kubernetes#657]
Issue: Setting the snapd_refresh option on a charm (or charms) doesn't work as expected. The deployment fails with (example):
```
unit-kubernetes-worker-1: 14:34:05 INFO unit.kubernetes-worker/1.juju-log kube-api-endpoint:1: Invoking reactive handler: reactive/kubernetes_worker.py:312:set_snapd_timer 
unit-kubernetes-worker-1: 14:34:05 INFO unit.kubernetes-worker/1.juju-log kube-api-endpoint:1: setting snapd_refresh timer to: None 
unit-kubernetes-worker-1: 14:34:05 INFO unit.kubernetes-worker/1.juju-log kube-api-endpoint:1: Set config refresh.timer=None for snap core 
unit-kubernetes-worker-1: 14:34:05 DEBUG unit.kubernetes-worker/1.kube-api-endpoint-relation-joined error: cannot perform the following tasks: 
unit-kubernetes-worker-1: 14:34:05 DEBUG unit.kubernetes-worker/1.kube-api-endpoint-relation-joined - Run configure hook of "core" snap (run hook "configure": cannot parse "None": "None" is not a valid weekday) 
unit-kubernetes-worker-1: 14:34:05 ERROR unit.kubernetes-worker/1.juju-log kube-api-endpoint:1: Hook error: 
Traceback (most recent call last): 
File "/var/lib/juju/agents/unit-kubernetes-worker-1/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main 
bus.dispatch(restricted=restricted_mode) 
File "/var/lib/juju/agents/unit-kubernetes-worker-1/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 382, in dispatch 
_invoke(other_handlers) 
File "/var/lib/juju/agents/unit-kubernetes-worker-1/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 358, in _invoke 
handler.invoke() 
File "/var/lib/juju/agents/unit-kubernetes-worker-1/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 180, in invoke 
self._action(*args) 
File "/var/lib/juju/agents/unit-kubernetes-worker-1/charm/reactive/kubernetes_worker.py", line 324, in set_snapd_timer 
snap.set_refresh_timer(timer) 
File "lib/charms/layer/snap.py", line 219, in set_refresh_timer 
set(snapname='core', key='refresh.timer', value=timer) 
File "lib/charms/layer/snap.py", line 185, in set 
['snap', 'set', snapname, '{}={}'.format(key, value)]) 
File "/usr/lib/python3.5/subprocess.py", line 581, in check_call 
raise CalledProcessError(retcode, cmd) 
subprocess.CalledProcessError: Command '['snap', 'set', 'core', 'refresh.timer=None']' returned non-zero exit status 1 
```
Workaround: Set the snapd_refresh option in every charm in the bundle that has that option.

**Comment by tvansteenburgh** [comment]
@KellenRenshaw Can you give details on how you set the `snapd_refresh` config please (either the command or the bundle used)?

**Comment by KellenRenshaw** [comment]
Bundle (tokens redacted):
```
description: A pre-production-grade Kubernetes cluster.
series: xenial
machines:
  '0':
    constraints: tags=k8s,master
    series: xenial
  '1':
    constraints: tags=k8s,worker
    series: xenial
  '2':
    constraints: tags=k8s,worker
    series: xenial
services:
  canal:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/canal-67
    bindings:
      "": provisioning-space
      cni: internal-space
    options:
      http_proxy: http://192.168.168.35:8000
      https_proxy: http://192.168.168.35:8000
      cidr: 10.1.0.0/16
  easyrsa:
    annotations:
      gui-x: '450'
      gui-y: '550'
    charm: cs:~containers/easyrsa-68
    bindings:
      "": provisioning-space
      client: internal-space
    num_units: 1
    to:
    - lxd:0
  etcd:
    annotations:
      gui-x: '800'
      gui-y: '550'
    charm: cs:~containers/etcd-126
    bindings:
      "": provisioning-space
      cluster: internal-space
      db: internal-space
    num_units: 1
    options:
      channel: 3.2/stable
      snap_proxy: http://192.168.168.35:8000
    to:
    - '0'
  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    charm: cs:~containers/kubernetes-master-144
    bindings:
      "": provisioning-space
      kube-api-endpoint: provisioning-space
      #kube-api-endpoint: internal-space
      kube-control: internal-space
    num_units: 1
    options:
      channel: 1.11/stable
      snap_proxy: http://192.168.168.35:8000
      snapd_refresh: 'fri5,23:00'
    to:
    - '0'
  kubernetes-worker:
    annotations:
      gui-x: '100'
      gui-y: '850'
    charm: cs:~containers/kubernetes-worker-163
    bindings:
      "": dmz-space
      kube-control: internal-space
    expose: true
    num_units: 2
    options:
      allow-privileged: 'false'
      channel: 1.11/stable
      snap_proxy: http://192.168.168.35:8000
      http_proxy: http://192.168.168.35:8000
      https_proxy: http://192.168.168.35:8000
      snapd_refresh: 'fri5,23:00'
      no_proxy: "127.0.0.1,172.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    to:
    - '1'
    - '2'
  canonical-livepatch:
    charm: cs:xenial/canonical-livepatch
    options:
      livepatch_proxy: http://192.168.168.35:8000
      snap_proxy: http://192.168.168.35:8000
      livepatch_key: XXXXX
relations:
- - kubernetes-master:kube-api-endpoint
  - kubernetes-worker:kube-api-endpoint
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - canal:etcd
  - etcd:db
- - canal:cni
  - kubernetes-master:cni
- - canal:cni
  - kubernetes-worker:cni
- [ canonical-livepatch, kubernetes-master ]
- [ canonical-livepatch, kubernetes-worker ]
```

**Comment by kwmonroe** [comment]
This is happening in `set_snapd_timer`, which runs on non-leader units:
https://github.com/juju-solutions/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L292

We must be getting `None` back from `leader_get`, which is... unexpected.  We're either:
1 - setting `None` on the leader in `process_snapd_timer`
2 - running `set_snapd_timer` before the leader has set anything

I don't think option 1 is possible -- I can't figure out how you'd make it back to k8s-worker/reactive with a `None` value from `snap get`.

My current guess is that `@when('leadership.changed.snapd_refresh')` is letting us in `set_snapd_timer` before `leader_set` has actually completed.  Maybe this is a misunderstanding of when `leadership.changed` is active, which is worth exploring.

We could always check that `leader_get` is not `None`, but then you might fall out of the handler without having done anything, and lose the leadership flag that got you in there in the first place.  If we can't figure out something wrong with the way we're using `leadership.changed`, we could drop that and do a `data_changed(foo, leader_get(snapd_refresh))` instead, but that means running this handler on every reactive loop.

**Comment by joedborg** [comment]
Hey @KellenRenshaw,

I've just had a go at reproducing the issue, could you please try with newer master and worker charms please?  I've tried with `cs:~containers/kubernetes-master-542` and `cs:~containers/kubernetes-worker-398` and I can't seem to reproduce the failure.

Thanks!

**Comment by KellenRenshaw** [comment]
@joedborg 

I was able to reproduce the issue with the newer charms. The key appears to be the canonical-livepatch charm.

I deployed this bundle successfully (kubernetes working)

`description: A pre-production-grade Kubernetes cluster.
series: bionic
services:
  canal:
    charm: cs:~containers/canal-524
    resources:
      calico: 16
      calico-arm64: 13
      flannel: 17
      flannel-arm64: 15
    options:
      cidr: 10.1.0.0/16
  easyrsa:
    charm: cs:~containers/easyrsa-195
    constraints: root-disk=8G
    resources:
      easyrsa: 5
    num_units: 1
  etcd:
    charm: cs:~containers/etcd-378
    constraints: root-disk=8G
    resources:
      etcd: 3
      snapshot: 0
    options:
      channel: 3.2/stable
    num_units: 1
    to:
     - "kubernetes-master"
  kubeapi-load-balancer:
    charm: cs:~containers/kubeapi-load-balancer-525
    constraints: root-disk=8G
    resources: {}
    expose: true
    num_units: 1
    to:
     - "kubernetes-master"
  kubernetes-master:
    charm: cs:~containers/kubernetes-master-542
    constraints: cores=2 mem=4G root-disk=16G
    resources:
      cdk-addons: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
    num_units: 1
    options:
      channel: 1.13/stable
      snapd_refresh: 'sun,11:25'
      authorization-mode: "AlwaysAllow"
      allow-privileged: 'true'
      enable-dashboard-addons: true
  kubernetes-worker:
    charm: cs:~containers/kubernetes-worker-398
    constraints: cores=4 mem=4G root-disk=16G
    resources:
      cni-amd64: 12
      cni-arm64: 10
      cni-s390x: 11
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
    num_units: 2
    expose: true
    options:
      allow-privileged: 'true'
      channel: 1.13/stable
      snapd_refresh: 'sun,11:25'
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - canal:etcd
  - etcd:db
- - canal:cni
  - kubernetes-master:cni
- - canal:cni
  - kubernetes-worker:cni
`

Then I added the canonical-livepatch charm (as a bundle):
`services:
  canonical-livepatch:
    charm: cs:xenial/canonical-livepatch
    options:
      livepatch_key: <valid_key_here>`

It explodes when I establish the relationship between canonical-livepatch and kubernetes-worker:
[before_lp_relationship.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2857821/before_lp_relationship.txt)
[after_lp_relationship.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2857822/after_lp_relationship.txt)

Note, adding a snapd_refresh config to canonical-livepatch after the fact doesn't fix the issue. Removing the canonical-livepatch application allows the error state to clear.

Adding canonical-livepatch with the snapd_refresh option set (validly) works fine.

**Comment by joedborg** [comment]
Thanks @KellenRenshaw, that's useful information we think we can see the issue now and we're looking into it.

**Comment by dshcherb** [comment]
This affects etcd charm as well.
