### ISSUE TITLE
Canal is broken in latest bundles

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#660]
Hi all, 

Canal appears to be broken in the latest bundles, it causes the worker nodes to constantly hang, here is an example of such a bundle: [https://raw.githubusercontent.com/CanonicalLtd/canonical-kubernetes-demos/master/cdk-monitoring-and-logging/cdk-logging-monitoring.yamll](https://raw.githubusercontent.com/CanonicalLtd/canonical-kubernetes-demos/master/cdk-monitoring-and-logging/cdk-logging-monitoring.yaml)*. 

When I deploy this, my kubernetes worker nodes constantly hang with the filebeat and kubernetes-worker nodes stuck in a loop which never ends. To fix this, I had to replace Canal with Flannel and it started to work again: 

[https://gist.githubusercontent.com/CalvinHartwell/247214dca037eeb3f3fa69d99a2a352f/raw/744544baff2b8eadbd8b931ffb900a2112526f86/cdk-logging-monitoring-flannel.yaml](https://gist.githubusercontent.com/CalvinHartwell/247214dca037eeb3f3fa69d99a2a352f/raw/744544baff2b8eadbd8b931ffb900a2112526f86/cdk-logging-monitoring-flannel.yaml)

FYI this just blocked me a good hour. This will also block customer deployments and demos. 

*Updated the link, my fault.

**Comment by ktsakalozos** [comment]
Hi @CalvinHartwell ,

> Canal appears to be broken in the latest bundles, it causes the worker nodes to constantly hang, here is an example of such a bundle: https://raw.githubusercontent.com/CalvinHartwell/canonical-kubernetes-demos/master/cdk-logging-and-monitoring/cdk-logging-monitoring.yaml.

Where did you find this yaml? Looking at the revisions of core cdk charms they seem really old. For example in the bundle you provide alink to I see cs:~containers/easyrsa-39, cs:~containers/kubernetes-master-102, cs:~containers/kubernetes-worker-114 (and using 1.9/stable kubernetes) whereas in the released bundle at https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml we have cs:~containers/easyrsa-114, cs:~containers/kubernetes-master-210, cs:~containers/kubernetes-worker-231. Could that be the source of the issue? The second bundle you linked to does not have any revisions for kubernetes charms (defaulting to the latest revisions) and it uses the latest 1.12/stable k8s channel.

Regardless what the issue may end up being, if we have links to outdated bundle.yamls we should spot them and update them.

**Comment by ktsakalozos** [comment]
@CalvinHartwell something is not right. The https://raw.githubusercontent.com/CalvinHartwell/canonical-kubernetes-demos/master/cdk-logging-and-monitoring/cdk-logging-monitoring.yaml does not have canal in it.

**Comment by ktsakalozos** [comment]
Here is the field agent report  
[results-2018-10-09-13-33-54.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2459995/results-2018-10-09-13-33-54.tar.gz)

**Comment by CalvinHartwell** [comment]
Thanks - I will try some more testing with a simpler bundle to see if I can get it to deploy Canal at all.

**Comment by CalvinHartwell** [comment]
@hyperbolic2346 @ktsakalozos any chance you could also test with Calico?

**Comment by ktsakalozos** [comment]
@CalvinHartwell the fix will be applied in both canal and calico

**Comment by drewboswell** [comment]
Very cool, I tried the canal release [146](https://jujucharms.com/u/containers/canal/146) and it eliminated the canal/kube-api problems I was having after upgrading all the charms to "stable".

Tahnks @CalvinHartwell @hyperbolic2346

**Comment by drewboswell** [comment]
> > @CalvinHartwell the fix will be applied in both canal and calico
> 
> Thanks @ktsakalozos, FYI we have a deployment about to start this week which needs this fix if the customer asks for Canal so I've bumped up the priority. The alternative is to deploy 1.11.

I have the same trouble with the cdk 1.11 release and the canal/141. What version of the canal charm to you recommend to run alongside 1.11?

**Comment by KellenRenshaw** [comment]
I ran into an issue with the Canal charm using canal-149 (and 141). It appears that under certain conditions (heavy contention in my case) the charm sometimes doesn't populate the kubeconfig option in 10-canal.conflist

ubuntu@pro-gecko:~$ cat /etc/cni/net.d/10-canal.conflist 
{
  "name": "cdk-canal",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "type": "calico",
        "etcd_endpoints": "https://192.168.221.175:2379",
        "etcd_key_file": "/opt/calicoctl/etcd-key",
        "etcd_cert_file": "/opt/calicoctl/etcd-cert",
        "etcd_ca_cert_file": "/opt/calicoctl/etcd-ca",
        "log_level": "info",
        "policy": {
          "type": "k8s"
        },
        "kubernetes": {
          "kubeconfig": "None"
        }
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": true
    }
  ]
}

The deployment is then stuck on "Waiting for kube-system pods to start" on the kubernetes-master.

I can manually correct the error by changing "kubeconfig": "None" to "kubeconfig": "/root/cdk/kubeconfig" in 10-canal.conflist and after a few minutes the pods get IPs and the deployment completes.

I am attaching logs from my test environment where juju machine 1 is enough-sheep (worked correctly) and juju machine 2 is pro-gecko (which shows the issue). The after-fix files show the output after correcting pro-gecko's 10-canal.conflist

[juju_complete_debug-log.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484120/juju_complete_debug-log.log)
[juju_status.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484121/juju_status.txt)
[juju_status-after-fix.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484122/juju_status-after-fix.txt)
[kubectl_get_pods.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484123/kubectl_get_pods.txt)
[kubectl_get_pods-after-fix.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484124/kubectl_get_pods-after-fix.txt)
[1-enough-sheep_10-canal.conflist.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484129/1-enough-sheep_10-canal.conflist.txt)
[1-enough-sheep_unit-canal-2.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484127/1-enough-sheep_unit-canal-2.log)
[2-pro-gecko_10-canal.conflist.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484134/2-pro-gecko_10-canal.conflist.txt)
[2-pro-gecko_unit-canal-1.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484135/2-pro-gecko_unit-canal-1.log)

**Comment by hyperbolic2346** [comment]
@KellenRenshaw did you happen to let this sit long enough for another set of hooks to run? That would take about 5 minutes or so. My assumption is that since we [set the connected state](https://github.com/juju-solutions/interface-kubernetes-cni/blob/60df63f1fca5096278e4aa7f4f10b54716cefde0/requires.py#L15) potentially before the config exists, that could mean that we run [configure_cni](https://github.com/juju-solutions/layer-canal/blob/1a7f754e7608933bdf350048dcdf20932380bc93/reactive/canal.py#L32) before the config exists and write out a bad config file.

The next set of hooks should clear that up, but it is a wait that isn't necessary. Does that sound sane?

If so, the fix here could be one of two things. Add a state to the interface to indicate that we have config or just use the is-master and is-worker states to indicate this to us with a `@when_any('cni.is-master', 'cni.is-worker')`.

**Comment by KellenRenshaw** [comment]
@hyperbolic2346 I let it sit for ~12h before I went in and pulled the debug info and manually fixed it. It was in the broken state for at least 11h. I deliberately stressed the system it was deploying to, since it seems to work better (not completely) when things deploy quickly.

**Comment by CalvinHartwell** [comment]
@hyperbolic2346 @tvansteenburgh I might need to bump the priority of this up as it will affect some customer deployments if it is not fixed in the next week or so.

**Comment by CalvinHartwell** [comment]
> > > @CalvinHartwell the fix will be applied in both canal and calico
> > 
> > 
> > Thanks @ktsakalozos, FYI we have a deployment about to start this week which needs this fix if the customer asks for Canal so I've bumped up the priority. The alternative is to deploy 1.11.
> 
> I have the same trouble with the cdk 1.11 release and the canal/141. What version of the canal charm to you recommend to run alongside 1.11?

It might be better to role with 1.10 for a awhile until this is addressed, but I never had this issue on 1.11. I can do some testing for you early next week to see if I can work out which charm version is working. Can you please share your bundle? 

Cheers

**Comment by hyperbolic2346** [comment]
This was fixed with version 142 of the canal charm, which is now stable. Note that https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/671 is still open, but I'm working on that now.

**Comment by CalvinHartwell** [comment]
@hyperbolic2346 is calico still broken as well?

**Comment by battlemidget** [comment]
@CalvinHartwell, no calico passes. Running canal tests now

**Comment by battlemidget** [comment]
canal passed as well, with edge charms/bundles

**Comment by hyperbolic2346** [comment]
Calico stable charms have the fix, canal doesn't yet, but we're pushing that today. Those fixes should solve this. For clarity, they were fixed with the following PRs: https://github.com/juju-solutions/interface-kubernetes-cni/pull/4  https://github.com/juju-solutions/layer-canal/pull/22 https://github.com/juju-solutions/layer-calico/pull/26

Further, we are improving our CI around this to prevent this from happening in the future.

**Comment by hyperbolic2346** [comment]
These fixes are now pushed to stable and released. Charm revisions with the fix: cs:~containers/canal-483 and cs:~containers/calico-494.

Note that these are also updated in the respective bundles now.
