### ISSUE TITLE
Metrics for pods failing readiness checks

### ISSUE THREAD

**Issue by mthaddon** [juju-solutions/bundle-canonical-kubernetes#667]
It would be very useful to have metrics for pods failing readiness checks, but still running. From everything we can see this isn't currently exposed in Kubernetes native metrics (at least on Kubernetes 1.11).

**Comment by mthaddon** [comment]
This is potentially a duplicate of https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/717 - if kube-state-metrics is the way to go this issue could be closed in favour of that one.

**Comment by tvansteenburgh** [comment]
Yep, closing in favor of #717.
