### ISSUE TITLE
Issue with canal charm not populating the kubeconfig option in 10-canal.conflist

### ISSUE THREAD

**Issue by KellenRenshaw** [juju-solutions/bundle-canonical-kubernetes#671]
Issue with the Canal charm using canal-149 (and 141). It appears that under certain conditions (heavy contention in my case) the charm sometimes doesn't populate the kubeconfig option in 10-canal.conflist

ubuntu@pro-gecko:~$ cat /etc/cni/net.d/10-canal.conflist 
{
  "name": "cdk-canal",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "type": "calico",
        "etcd_endpoints": "https://192.168.221.175:2379",
        "etcd_key_file": "/opt/calicoctl/etcd-key",
        "etcd_cert_file": "/opt/calicoctl/etcd-cert",
        "etcd_ca_cert_file": "/opt/calicoctl/etcd-ca",
        "log_level": "info",
        "policy": {
          "type": "k8s"
        },
        "kubernetes": {
          "kubeconfig": "None"
        }
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": true
    }
  ]
}

The deployment is then stuck on "Waiting for kube-system pods to start" on the kubernetes-master.

I can manually correct the error by changing "kubeconfig": "None" to "kubeconfig": "/root/cdk/kubeconfig" in 10-canal.conflist and after a few minutes the pods get IPs and the deployment completes.

I am attaching logs from my test environment where juju machine 1 is enough-sheep (worked correctly) and juju machine 2 is pro-gecko (which shows the issue). The after-fix files show the output after correcting pro-gecko's 10-canal.conflist

[juju_complete_debug-log.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484120/juju_complete_debug-log.log)
[juju_status.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484121/juju_status.txt)
[juju_status-after-fix.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484122/juju_status-after-fix.txt)
[kubectl_get_pods.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484123/kubectl_get_pods.txt)
[kubectl_get_pods-after-fix.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484124/kubectl_get_pods-after-fix.txt)
[1-enough-sheep_10-canal.conflist.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484129/1-enough-sheep_10-canal.conflist.txt)
[1-enough-sheep_unit-canal-2.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484127/1-enough-sheep_unit-canal-2.log)
[2-pro-gecko_10-canal.conflist.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484134/2-pro-gecko_10-canal.conflist.txt)
[2-pro-gecko_unit-canal-1.log](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484135/2-pro-gecko_unit-canal-1.log)

Edit: adding my bundle used to deploy with "juju deploy bundle.yaml"

[k8s_fixed.yaml.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484167/k8s_fixed.yaml.txt)

_Originally posted by @KellenRenshaw in https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/660#issuecomment-430314835_

**Comment by KellenRenshaw** [comment]
Adding cdk-field-agent output.
This one is from the environment I fixed manually
[test1-results-2018-10-16-10-43-29.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484290/test1-results-2018-10-16-10-43-29.tar.gz)

This one is from test2 environment, with both workers showing the issue.
[test2-results-2018-10-16-10-49-14.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2484307/test2-results-2018-10-16-10-49-14.tar.gz)

**Comment by drewboswell** [comment]
Beautiful! You saved me, thanks for the investigation @KellenRenshaw.

I confirm the workaround works, for the moment I am executing the following command post-juju install.

```
# what I execute post install
juju run "sed -ri 's/^(.*kubeconfig.*)None(.*)/\1\/root\/cdk\/kubeconfig\2/' /etc/cni/net.d/10-canal.conflist" --application=kubernetes-worker
```

**Comment by drewboswell** [comment]
This problem applies to the flannel deployment as well. It happens often to use that the entire kubeconfig block is not even inserted into that file net.d/*-flannel.conflist

**Comment by Cynerva** [comment]
> This problem applies to the flannel deployment as well. It happens often to use that the entire kubeconfig block is not even inserted into that file net.d/*-flannel.conflist

Nah, this is normal for flannel. The kubeconfig option is specific to the calico CNI plugin, which the flannel charm doesn't use.

**Comment by drewboswell** [comment]
@Cynerva thanks for the info. This is weird, in that case there is contention coming from somewhere in the same style as the canal problem (only works/installs half the time). We'll create a separate issue for it and attach further info once we have it.

**Comment by hyperbolic2346** [comment]
The fix for this is now pushed to stable and released. Update to revision 483 of the canal charm to pick up the fix. Also note that the bundle for canal has been updated to this revision as well.
