### ISSUE TITLE
make fails with IndexError: list index out of range

### ISSUE THREAD

**Issue by sfabel** [juju-solutions/bundle-canonical-kubernetes#673]
```
$ make
rm -rf ./bundles
./bundle k8s/cdk cni/flannel -o ./bundles/cdk-flannel
Processing fragment k8s/cdk...
Processing fragment cni/flannel...
Done. Your bundle can be found in /home/stephan/bundle-canonical-kubernetes/bundles/cdk-flannel
./bundle k8s/cdk cni/flannel legacy-storage/ceph -o ./bundles/cdk-flannel-ceph
Processing fragment k8s/cdk...
Processing fragment cni/flannel...
Processing fragment legacy-storage/ceph...
Done. Your bundle can be found in /home/stephan/bundle-canonical-kubernetes/bundles/cdk-flannel-ceph
./bundle k8s/cdk cni/flannel monitor/elastic -o ./bundles/cdk-flannel-elastic
Processing fragment k8s/cdk...
Processing fragment cni/flannel...
Processing fragment monitor/elastic...
Traceback (most recent call last):
  File "./bundle", line 226, in <module>
    main()
  File "./bundle", line 191, in main
    bundle = version_bundle(bundle, args.channel, args.overrides)
  File "./bundle", line 134, in version_bundle
    meta = [meta[k] for k in meta][0]
IndexError: list index out of range
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1

```

**Comment by ktsakalozos** [comment]
Hi @sfabel ,

This project is used in the late stages of our CI to produce the bundles we will test and release. This means it may produce untested broken bundles https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/599#issuecomment-405478372 . The released bundles are available from the store only.

This error is because kibana is not yet available on bionic.

**Comment by CalvinHartwell** [comment]
@ktsakalozos we should remove Kibana from this, we don't even use it anymore, anywhere?

**Comment by tvansteenburgh** [comment]
Kibana is used in this bundle: https://jujucharms.com/canonical-kubernetes-elastic/

**Comment by CalvinHartwell** [comment]
^ this bundle does not align with conjure-up, why is that still advertised?

**Comment by tvansteenburgh** [comment]
Yeah, the elastic bundle predates our current recommended LMA stack for CDK. We want to make a few doc updates to which we can point users migrating from the elastic bundle, and then we'll be removing it from the store.
