### ISSUE TITLE
Ceph volumes fail to attach with "node has no NodeID annotation"

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#675]
Only occurs with Kubernetes 1.10 and 1.11.

```
$ kubectl describe po busybox
...
Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Normal   Scheduled           38s               default-scheduler        Successfully assigned default/busybox to ip-172-31-7-52
  Warning  FailedAttachVolume  7s (x7 over 38s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7c397ca9d25a11e8" : node "ip-172-31-7-52" has no NodeID annotation
```

**Comment by Cynerva** [comment]
This requires the `KubeletPluginsWatcher` feature, which is not in kubelet 1.10, and is ALPHA / disabled by default in 1.11.

For 1.10, the solution is clear: we do not ship ceph-csi, and instead continue to ship the classic ceph integration.

For 1.11, we can either ship ceph-csi by enabling the `KubeletPluginsWatcher` feature, or ship the classic ceph integration instead. I prefer to avoid relying on alpha features so I'm going with the latter unless someone objects.

**Comment by hyperbolic2346** [comment]
I agree that we should push the CSI to 1.12.
