### ISSUE TITLE
Proxy documentation should use snap-http-proxy, snap-https-proxy model configs

### ISSUE THREAD

**Issue by paulgear** [juju-solutions/bundle-canonical-kubernetes#676]
See https://pastebin.ubuntu.com/p/DYFnZ86SsQ/ for log.  It appears the root cause is that there's nothing in its AppArmor profile which allows it to create /run/kubernetes/.  I couldn't find any evidence that any apparmor files shipped with the system or the snap allow this.

Adding this to /var/lib/snapd/apparmor/profiles/snap.kube-controller-manager.daemon allows the service to start:
```
/run/kubernetes/ rw,
/run/kubernetes/** rw,
```

**Comment by ktsakalozos** [comment]
Can you please attach the field agent report? https://github.com/juju-solutions/cdk-field-agent

**Comment by mthaddon** [comment]
I'm providing the field agent report outside of this issue in case any secrets are included.

**Comment by ktsakalozos** [comment]
Can you make sure there is a relation between etcd and flannel? I do not see flannel reported under etcd as a subordinate. Etcd reports "Errored with 0 known peers". `ifconfig` does not report the flannel interface etcd logs a network problem.

**Comment by Cynerva** [comment]
Please confirm that you're running kubernetes-master charm revision 210 or later. This was an issue we found while testing 1.12 (https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/645) and should have been resolved with https://github.com/juju-solutions/kubernetes/pull/167.

**Comment by Cynerva** [comment]
> I do not see flannel reported under etcd as a subordinate. ... ifconfig does not report the flannel interface

This is normal, right? Flannel does relate to etcd, but not as a subordinate.

"Errored with 0 known peers" is definitely not normal though.

**Comment by paulgear** [comment]
> Please confirm that you're running kubernetes-master charm revision 210 or later. This was an issue we found while testing 1.12 (#645) and should have been resolved with [juju-solutions/kubernetes#167](https://github.com/juju-solutions/kubernetes/pull/167).

The charms were all refreshed from charm store at the beginning of each mojo run; e.g. 
```
2018-10-18 06:47:16 [INFO] kubernetes-master is up to date from url cs:~containers/kubernetes-master-219, skipping.
```

Also, for the record, the etcd 2.3 to 3.0 upgrade was done after upgrading the etcd charm following https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Etcd-2.3-to-3.x-upgrade and the script from https://raw.githubusercontent.com/juju-solutions/cdk-etcd-2to3/master/migrate.

**Comment by paulgear** [comment]
Switching configuration from http-proxy to juju-http-proxy and setting juju-no-proxy appropriately fixed the status display on the etcd charm and enabled the etcdctl commands used in the flannel hook to complete successfully.

**Comment by paulgear** [comment]
So I think this probably needs to turn into a documentation change.

Currently https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Proxy-configuration recommends setting:
```
juju config etcd snap_proxy=https://squid.internal:3128
juju config kubernetes-master snap_proxy=https://squid.internal:3128
juju config kubernetes-worker snap_proxy=https://squid.internal:3128 http_proxy=http://squid.internal:3128 https_proxy=https://squid.internal:3128
```
Because it's now possible to set the snap proxy from juju (https://github.com/juju/juju/blob/2.4/environs/config/config.go#L145), I think this should be changed to read:
```
juju model-config snap-http-proxy=http://squid.internal:3128 snap-https-proxy=http://squid.internal:3128
juju config kubernetes-worker http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128
```
(Note in the above that http & https proxies are usually the same URL - https is still secure because it's handled as a CONNECT not a GET.)

**Comment by paulgear** [comment]
And in addition to the above, we need to make sure that a reference to the proxy configuration is present in the release notes.

**Comment by Cynerva** [comment]
The `snap-http-proxy` and `snap-https-proxy` model configs don't seem to work, since they use the `snap set core proxy.http` method of configuring snapd, which apparently does not work unless you have the core snap already installed. See https://bugs.launchpad.net/snapd/+bug/1791587

For now, we will continue to recommend using the `snap_proxy` charm configs instead.

> (Note in the above that http & https proxies are usually the same URL - https is still secure because it's handled as a CONNECT not a GET.)

Thanks, I think you're right. I've updated the proxy configuration document to use `http://squid.internal:3128` across the board.

**Comment by Cynerva** [comment]
I've added proxy configuration to the release notes as well. Closing this as I believe there is nothing further to do.
