### ISSUE TITLE
Docker version shipped with 18.04 is not tested/verified by upstream kubernetes 

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#683]
Hi all,

You may already be aware but the version of Docker currently being shipped by default on 18.04 is actually unverified/tested as part of the upstream Kubernetes distro: 

- [https://github.com/kubernetes/kubernetes/issues/65089](https://github.com/kubernetes/kubernetes/issues/65089)

I think we need an easy option to install/replace this with the older version or push to get the newer version verified by upstream. 

Cheers,

- Calvin

**Comment by tvansteenburgh** [comment]
Yeah, we're aware. We verify CDK with the version of Docker that's default for the Ubuntu release that's being used (for example, we just recently tested with Docker 18.06 from bionic-proposed, and that'll be hitting bionic-updates soon).

A cluster operator can switch the version of Docker on the workers manually if desired, at their own risk. We don't have any plans to make this a charm config option, beyond what we already have (via the docker_runtime config on kubernetes-worker).

**Comment by CalvinHartwell** [comment]
> @CalvinHartwell You used the word "this" three times without an antecedent to define what "this" is. So...

This == the version of docker we are shipping is not aligned to the upstream version
