### ISSUE TITLE
juju offline set up , repository has no Release file

### ISSUE THREAD

**Issue by dimthe** [juju-solutions/bundle-canonical-kubernetes#685]
hello 

i am following this page : 
https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Running-CDK-in-a-restricted-environment

i have completed everything with no errors up to the point where the next step is to bootstrap  juju 
and i get these errors 

this part starts ok

`dimtheo@juju:~$ juju clouds
Cloud        Regions  Default          Type        Description
aws               15  us-east-1        ec2         Amazon Web Services
aws-china          1  cn-north-1       ec2         Amazon China
aws-gov            1  us-gov-west-1    ec2         Amazon (USA Government)
azure             26  centralus        azure       Microsoft Azure
azure-china        2  chinaeast        azure       Microsoft Azure China
cloudsigma         5  hnl              cloudsigma  CloudSigma Cloud
google            13  us-east1         gce         Google Cloud Platform
joyent             6  eu-ams-1         joyent      Joyent Cloud
oracle             5  uscom-central-1  oracle      Oracle Cloud
rackspace          6  dfw              rackspace   Rackspace Cloud
localhost          1  localhost        lxd         LXD Container Hypervisor
k8s                0                   manual
testcloud          0                   manual

Try 'list-regions <cloud>' to see available regions.
'show-cloud <cloud>' or 'regions --format yaml <cloud>' can be used to see region endpoints.
Update the known public clouds with 'update-clouds'.
'add-cloud' can add private or custom clouds / infrastructure built for the following provider types:
  - maas, manual, openstack, oracle, vsphere

dimtheo@juju:~$ juju bootstrap testcloud
Creating Juju controller "testcloud" on testcloud
Looking for packaged Juju agent version 2.4.4 for amd64
Installing Juju agent on bootstrap instance
Fetching Juju GUI 2.14.0
Running machine configuration script...

`

but when i tail the logs i get these

`dimtheo@juju:~$ sudo tail -f /var/log/cloud-init-output.log
Err:4 http://192.168.1.88/ubuntu bionic Release
  404  Not Found [IP: 192.168.1.88 80]
Err:5 http://192.168.1.88/ubuntu bionic-security Release
  404  Not Found [IP: 192.168.1.88 80]
Err:6 http://192.168.1.88/ubuntu bionic-updates Release
  404  Not Found [IP: 192.168.1.88 80]
Reading package lists...
E: The repository 'http://192.168.1.88/ubuntu bionic Release' no longer has a Release file.
E: The repository 'http://192.168.1.88/ubuntu bionic-security Release' no longer has a Release file.
E: The repository 'http://192.168.1.88/ubuntu bionic-updates Release' no longer has a Release file.
Ign:1 http://192.168.1.88/ubuntu bionic InRelease`

what is wrong ? thanks

**Comment by CalvinHartwell** [comment]
@dimthe did you fix the issue?

**Comment by dimthe** [comment]
yes @CalvinHartwell  i had to resync my apt-mirror several times for this to work
