### ISSUE TITLE
Upgrading CDK to 1.11 or later breaks monitoring

### ISSUE THREAD

**Issue by paulgear** [juju-solutions/bundle-canonical-kubernetes#687]
We're in the process of upgrading our CDK installs to Kubernetes 1.12, and during our last upgrade we found that kubelet-extra-args='--cadvisor-port=4194' was no longer supported (because it is deprecated upstream).  We hacked around this manually, but as of 1.12, cAdvisor has been removed entirely.

This represents a feature regression, since cAdvisor metrics are what we use for monitoring & alerting of missing/broken pods and performance problems.  Upstream's recommendation is to run cAdvisor as a DaemonSet, so please take this as a request to commit CDK to providing this as part of the default install.

@tvansteenburgh, could we please have a canonical-is tag on this issue?  Internal ref. cRT#114215 if you need it.

**Comment by hyperbolic2346** [comment]
@paulgear Do you have a link to that recommendation from upstream?

**Comment by kwmonroe** [comment]
@paulgear it's true that cadvisor is no longer directly accessible, but you can still scrape the data from the k8s-master or kubeapi-load-balancer:
```
curl -k -u admin:password https://172.31.1.69:443/api/v1/nodes/ip-172-31-25-18.us-west-1.compute.internal/proxy/metrics/cadvisor
<lots of output>
```

I can confirm that prometheus scraping does work given the right scraper (that is, scrape the proxied metrics vs the cadavisor endpoints directly).  Here's our scrape job (see `job_name: 'kubernetes-cadvisor'` for details:

https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/addons/prometheus/steps/01_install-prometheus/prometheus-scrape-k8s.yaml

To confirm this, add that job to your `prometheus/0:/var/snap/prometheus/current/prometheus.yaml` and `sudo systemctl stop snap.prometheus.prometheus` followed by a `start`.

Caveat, we know this does not work when RBAC is enabled, but we're working on a fix for that now #635.

**Comment by paulgear** [comment]
I've upgraded two of our CDK installs with the above scrape job (and an extra relabel_configs entry to make the tags match), and it seems to work as expected.  I'm concerned about the complexity of the config and the need for pulling API credentials and adding them in clear text to the prometheus install - is this something for which you have a preferred solution?  e.g. juju cross-model relations? An in-CDK prometheus unit + federation?

**Comment by paulgear** [comment]
Also, the k8s-api-endpoints scrape job did not work in either of the CDK endpoints I tested; it seems to be because the API server juju unit does not expose TCP 6443, which is what the target gets added as when the scrape job finds it.  I'm not clear on why this port is used when the -nodes and -cadvisor scrape jobs use TCP 443 - presumably the kubernetes_sd_configs driver assumes a different port for the API endpoints?

**Comment by paulgear** [comment]
Turns out the k8s-api-endpoints job just needed a "juju expose kubernetes-master".  (Questions in https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/687#issuecomment-438197131 still relevant, though.)

**Comment by kwmonroe** [comment]
> Turns out the k8s-api-endpoints job just needed a "juju expose kubernetes-master".

@paulgear are you scraping the k8s-master public or private ip?  assuming prometheus and k8s are in the same model, prom should be able to hit the private ip without exposure.  fwiw, we typically scrape the `kubeapi-load-balancer`, which should keep metrics flowing in if/when a master goes down.

**Comment by kwmonroe** [comment]
@paulgear i'm poking around with prometheus scraping again, and while I know this (and the associated rt) is stale, I noticed you can get at the endpoints without exposing k8s-master port 6443. That info is scrapable from the kubeapi-load-balancer -- similar to the node metrics mentioned in https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/687#issuecomment-437037521:

```bash
$ export PASS=password
$ export KUBE_LB=172.3.2.1:443
$ curl -k -u admin:$PASS https://$KUBE_LB/api/v1/endpoints
```

In our conjure-up spell, prometheus scrapes endpoint service data from the default k8s namespace, but we don't really show that off in our default dashboards. You can see more info about prometheus endpoint config here if it's helpful in adjusting you scraper labels:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints

**Comment by kwmonroe** [comment]
Scraping metrics via the load-balancer proxy is an effective workaround, so prometheus monitoring remains functional.

@paulgear I don't want to lose the issues that came up from your comments, so let's track those over in CDK's launchpad:

https://bugs.launchpad.net/charm-kubeapi-load-balancer/+bug/1819573

Closing this out here.
