### ISSUE TITLE
juju status hangs indefinitely 

### ISSUE THREAD

**Issue by TarunKDas2k18** [juju-solutions/bundle-canonical-kubernetes#694]
*If your deployment is broken and you'd like help debugging it, please run our [CDK Field Agent](https://github.com/juju-solutions/cdk-field-agent) tool and attach the resulting tarball to this issue.*

**Comment by TarunKDas2k18** [comment]
installed cdk agent still juju status hanged 

![image](https://user-images.githubusercontent.com/44246599/48796933-c00b4580-ecb5-11e8-92ec-f1773cbaf29c.png)

**Comment by CalvinHartwell** [comment]
Hi @TarunKDas2k18,

Do you have any more information about your deployment or what you have tested?

**Comment by tvansteenburgh** [comment]
Not much we can do without more info.
