### ISSUE TITLE
vSphere integrator charm not updating cloud-config when setting new charm defaults 

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#695]
Hi all,

I am running in a VMware vSphere environment and I noticed that when I update values for the vSphere Integrator charm via juju config, I.E: 

juju config vsphere-integrator datastore='cats-are-superior-to-humans'

The config ends up in two places on the kubernetes master nodes, but note that datastore1 is still in there as a default: 

ubuntu@juju-a8a92d-3:/var/snap$ find . -name '*cloud-config.conf*'
./kube-controller-manager/common/cloud-config.conf
./kube-apiserver/common/cloud-config.conf

and the value assigned to 'default-datastore' does not update:

> [Global]
> insecure-flag = true
> datacenters = "IDC"
> vm-uuid = "VMware-42218D1B-E1CE-33D9-20C7-F25D55E53393"
> [VirtualCenter "172.00.00.00"]
> user = canonicaltemp@cute.kittens
> password = CATS-ARE-GODS
> [Workspace]
> server = 172.00.00.00
> datacenter = "IDC"
> default-datastore = "datastore1"
> folder = "kubernetes"
> resourcepool-path = ""
> [Disk]
> 

We also need the ability to update and set the following values in the vSphere cloud config via the juju charm: 

```
folder = ""
resourcepool-path = "CDK"
```

**Comment by CalvinHartwell** [comment]
Also noticed that the default config throws an error: 

```
[
if cfg.Workspace.VCenterIP == "" || cfg.Workspace.Folder == "" || cfg.Workspace.Datacenter == "" {
			msg := fmt.Sprintf("All fields in workspace are mandatory."+
				" vsphere.conf does not have the workspace specified correctly. cfg.Workspace: %+v", cfg.Workspace)
			klog.Error(msg)
			return nil, errors.New(msg)
}]
```

[https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L373](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L373)

**Comment by kwmonroe** [comment]
> The config ends up in two places on the kubernetes master nodes, but note that datastore1 is still in there as a default:

@CalvinHartwell this is for sure a bug in the vsphere interface.  We currently do not reflect config changes from the provider (vsphere-integrator charm) on the requirer (k8s-master).  We'll need to do something like openstack did to handle cloud config changes:

https://github.com/juju-solutions/kubernetes/blob/master/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1886

With similar changes to set `ready.changed` in `interface-vsphere-integration`.

The workaround for now is to set the right config at deploy-time and not rely on `juju config` post deployment.

> We also need the ability to update and set the following values in the vSphere cloud config via the juju charm

We can expose these in the integrator charm, but like you noticed, "folder" is required by the upstream k8s vsphere provider. Setting it to "" will fail, so we need to make sane defaults and ensure users don't empty this value.

**Comment by CalvinHartwell** [comment]
@kwmonroe I set the configs manually, restarted all the services but it is still failing - I.E even with the UUID fix on the VM(s) I am not getting errors regarding volume creation, I will update it soon.

**Comment by CalvinHartwell** [comment]
@kwmonroe one thing to do note, is that I have to migrate the machines around after they are built, because of my issue with the datastore space (I have to migrate them to other datastores), I wonder if this somehow affects the UUID. 

Me and Pedro will investigate tomorrow and come back to you as planned. 

Cheers

**Comment by kwmonroe** [comment]
Dag nab github closing all kinds of issues just because someone says "fixes" :)

I'm gonna reopen this until k8s charms make it out to -edge.  There were quite a few moving parts to get this going. To summarize:

- interface support for config.changed:
https://github.com/juju-solutions/interface-vsphere-integration/pull/1

- interface support for new folder/respool config:
https://github.com/juju-solutions/interface-vsphere-integration/pull/2

- integrator support for interface changes:
https://github.com/juju-solutions/charm-vsphere-integrator/pull/2

- k8s support for integrator changes:
https://github.com/juju-solutions/kubernetes/pull/200

The integrator charm has been released to candidate and is available for testing at:

https://jujucharms.com/u/containers/vsphere-integrator/2

The k8s charms are working their way through CI, so I'll post revisions that include these fixes once they are released.

Using locally built k8s charms, i was able to verify a PVC failed using an invalid datastore ("ham"), and then succeeded after `config-changed` fired with a valid datastore using `juju config vsphere-integrator datastore=datastore1`:

```bash
$ kubectl describe pvc
Name:          testclaim
Namespace:     default
StorageClass:  mystorage
Status:        Bound
Volume:        pvc-ea556ee3-ffbc-11e8-8f6e-00505636902a
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Mi
Access Modes:  RWO
Events:
  Type       Reason                 Age                 From                         Message
  ----       ------                 ----                ----                         -------
  Warning    ProvisioningFailed     66s (x5 over 2m6s)  persistentvolume-controller  Failed to provision volume with StorageClass "mystorage": The specified datastore ham is not a shared datastore across node VMs
  Normal     ProvisioningSucceeded  7s                  persistentvolume-controller  Successfully provisioned volume pvc-ea556ee3-ffbc-11e8-8f6e-00505636902a using kubernetes.io/vsphere-volume
Mounted By:  <none>
```

**Comment by kwmonroe** [comment]
vsphere-integrator-2 has been promoted to stable.  kubernetes-master-546 and above include this fix.
