### ISSUE TITLE
kubernetes-master  - Unable to install packages socat,vaultlocker on Xenial, 

### ISSUE THREAD

**Issue by kowalczykb** [juju-solutions/bundle-canonical-kubernetes#708]
Awaiting for CDK Field Agent to complete.

[juju-status.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2663762/juju-status.txt)
[cdk-bundle.yaml.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2663773/cdk-bundle.yaml.txt)

**Comment by kwmonroe** [comment]
The PPA we're using to install vaultlocker does not have the python-$reqs for xenial:

https://launchpad.net/~openstack-charmers/+archive/ubuntu/vaultlocker

The openstack-charmers team let us know that `cloud-archive:queens` is what they use, and I've confirmed deps are available for xenial.  Working on a fix for the k8s charms to use this.

**Comment by kowalczykb** [comment]
And CDK Agent for reference.
[results-2018-12-10-15-58-32.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2663965/results-2018-12-10-15-58-32.tar.gz)

**Comment by Cynerva** [comment]
A workaround is to deploy kubernetes-master with a modified `install_sources` charm config:

```
juju config kubernetes-master install_sources="- cloud:queens"
```

Or if you're deploying with a bundle, you can add it there instead:
```
services:
  kubernetes-master:
    options:
      install_sources: "- cloud:queens"
```

([Full example bundle](https://gist.github.com/Cynerva/8efef3fbba95bfa2b3666c8b0ef97b8c))

**Comment by kwmonroe** [comment]
New k8s master charm and bundles have been released to stable.  Confirmed rev 542 and higher fixes deployment on Xenial:

https://jujucharms.com/u/containers/kubernetes-master/
