### ISSUE TITLE
k8s-worker waiting for kubelet to start

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/bundle-canonical-kubernetes#71]
After a full deployment a couple of the k8s-workers get into a waiting state with the message 'waiting for kubelet to start'

unit log:
http://paste.ubuntu.com/23271448/

juju status:
http://paste.ubuntu.com/23271455/

juju status --format yaml:
http://paste.ubuntu.com/23271456/

Reproduce with:

```
apt-add-repository ppa:conjure-up/daily-git
conjure-up -d canonical-kubernetes
```

**Comment by mbruzek** [comment]
@battlemidget This looks like our messaging is stuck. We need to figure out why the messages are not converging to a ready state. Would it be possible to `juju run kubernetes-worker/0 "charms.reactive get_states"` and include that in the pastebin as well?

**Comment by chuckbutler** [comment]
This should be fixed by https://github.com/juju-solutions/kubernetes/pull/53

Please re-open if this behavior continues. (this is going out in today's publication, see the list archive later)

**Comment by wwwtyro** [comment]
Woot!
