### ISSUE TITLE
kubeconfig should contain the VIP when keepalived used with kubeapi-load-balancer

### ISSUE THREAD

**Issue by grebennikov** [juju-solutions/bundle-canonical-kubernetes#712]
Deploying CDK with 3 instances of kube-api-loadbalancer together with keepalived as a subordinate.
I specify the virtual IP address of the api-balancer (handled by the VIP), and it is deployed successfully.
I also specify an option for api-balancer to include the VIP to the certificate so that it can be used as the endpoint address.
However, when looking at the kubectl config, I still see a real address of one of the api-balancer instances.
The code here https://github.com/juju-solutions/kubernetes/blob/master/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L940
should be changed to use VIP of the api-balancer in case it is present, as well as the api-balancer charm should also automatically populate the VIP address into the certificate.

**Comment by joedborg** [comment]
This can be achieved by running `juju remove-relation kubernetes-master:loadbalancer kubeapi-load-balancer:loadbalancer` after deploying `keepalived`.  Have updated the docs to reflect this.
