### ISSUE TITLE
Update NGINX  Arguments?

### ISSUE THREAD

**Issue by robotica72** [juju-solutions/bundle-canonical-kubernetes#718]
Ive searched around for this answer and I cant find anything on the topic, so hoping someone can help out here....

Since JuJu keeps the cluster in a state, any changes I make to the deployment arguments are, as expected, overwritten after a few seconds.

I  dont see any options in juju config aside from the NGINX image and the SSL option - but I need to set an option to test TCP-Streams, so I need to add one (if not 2) arguments to the deployment.

How do I set those values if the juju config doesnt have an option to set them and juju keeps reverting any manual changes?

Thanks...

**Comment by Cynerva** [comment]
Looks like there's no way to accomplish this without modifications to the charm. This was supposed to be supported by setting the `ingress` config to false:
```
juju config kubernetes-worker ingress=false
```

Which would, in theory, disable the charm's management of nginx-ingress-controller, allowing the operator to deploy their own nginx-ingress-controller with modifications to suit their needs.

However, that isn't working as intended, for two reasons:
1. If the operator deploys the nginx-ingress-controller resources with the same names in the same namespaces, then the charm deletes them.
2. The charm repeatedly closes ports 80 and 443.

We will need to fix this.

**Comment by robotica72** [comment]
Hi - Thanks for the reply, I appreciate the answer and (potential) solution once fixed :)

**Comment by Cynerva** [comment]
A fix that makes this possible (with a bit of an awkward workflow) is now in the edge channel of kubernetes-worker, revision 436. It will probably be a couple weeks before it makes it to stable.

Deploy the cluster with kubernetes-worker revision 436 or greater, using whatever method you prefer. Example with `juju deploy`:
```
juju deploy kubernetes-core --channel edge
```

After the deployment settles, disable ingress:
```
juju config kubernetes-worker ingress=false
```

Wait for the ingress controller to be removed from Kubernetes.

At this point, you should now be free to deploy and edit your own ingress controller with the modifications you need. One way to do this is by fetching the existing templates from the kubernetes-worker charm.

Copy the templates to your local machine:

```
juju ssh kubernetes-worker/0 sudo cat /root/cdk/addons/ingress-daemon-set.yaml > ingress-daemon-set.yaml
juju ssh kubernetes-worker/0 sudo cat /root/cdk/addons/default-http-backend.yaml > default-http-backend.yaml
```

Edit the templates to add anything you want to add.

Apply the templates:

```
kubectl apply -f ingress-daemon-set.yaml
kubectl apply -f default-http-backend.yaml
```

Reopen ports 80 and 443 manually:

```
juju run --application kubernetes-worker open-port 80
juju run --application kubernetes-worker open-port 443
```

From here on out, you should be free to use `kubectl apply` or `kubectl edit` to make further tweaks. The charm will not override or remove what you have deployed.

**Comment by robotica72** [comment]
Thanks for the fix!  Sorry for the delayed thank you, been busy at work :)
