### ISSUE TITLE
Add nfs-common on all nodes by default

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#72]
This enables accessing any NFS from the cluster OOTB, which is very useful even if Ceph is coming quickly. 

Thanks :)

**Comment by mbruzek** [comment]
The PR https://github.com/juju-solutions/kubernetes/pull/57 resolves this issue. Once that gets reviewed the changes can land in the main repository and then we have to push new charms, and bump the revision number in the bundle.

**Comment by mbruzek** [comment]
We released a new version of the bundle that should have nfs included on the worker. Please check the latest bundle:  https://jujucharms.com/canonical-kubernetes/9

**Comment by chuckbutler** [comment]
This went out with the release yesterday.
