### ISSUE TITLE
CDK broken when using GPUs due to nvidia-docker2 dependency failure

### ISSUE THREAD

**Issue by joedborg** [juju-solutions/bundle-canonical-kubernetes#720]
```
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

 nvidia-docker2 : Depends: docker-ce (= 5:18.09.0~3-0~ubuntu-bionic) but 5:18.09.1~3-0~ubuntu-bionic is to be installed or
                           docker-ee (= 5:18.09.0~3-0~ubuntu-bionic) but it is not installable
```

This occurs when deploying onto workers with GPUs.

**Comment by joedborg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot deploy to GPUs due to dependency of nivida-docker2](https://trello.com/c/04PhtIcR/1105-cannot-deploy-to-gpus-due-to-dependency-of-nivida-docker2)

**Comment by joedborg** [comment]
https://github.com/juju-solutions/layer-docker/pull/130

**Comment by joedborg** [comment]
@jonoinnz this can be fixed with `juju config kubernetes-worker docker-ce-package="docker-ce=5:18.09.0~3-0~ubuntu-bionic"`

**Comment by kwmonroe** [comment]
This has been released as of kubernetes-worker revision 436:

https://jujucharms.com/u/containers/kubernetes-worker/436

It will be released to stable as it makes its way through testing, though the workaround from @joedborg above can be used immediately.

**Comment by jonoinnz** [comment]
Thanks @joedborg appreciate it, will give it a try, thanks in advance @kwmonroe for applying the fix.
