### ISSUE TITLE
registry action creating configmap in the wrong namespace 

### ISSUE THREAD

**Issue by alejdg** [juju-solutions/bundle-canonical-kubernetes#721]
The most recent version of nginx-ingress(0.21.0) puts the worker ingresses in its own namespace instead of the default one. And it expects a configmap to be in the same namespace as well.

The charm explicitly installs 0.21.0 but also still puts the registry configmap into the default namespace[1], which no longer hosts the ingress.

This causes the registry to keep the default value for client_max_body_size.

The new namespace is called "ingress-nginx-kubernetes-worker" and the configmap is "nginx-configuration".

I also believe the key name that should be used in the configmap has changed from "body-size" to "proxy-body-size"[2].

[1]https://github.com/juju-solutions/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/actions/registry
[2]https://github.com/kubernetes/ingress-nginx/blob/master/rootfs/etc/nginx/template/nginx.tmpl#L1015

**Comment by hyperbolic2346** [comment]
Fix in kubernetes-worker charm version 439
