### ISSUE TITLE
Ingress docs are incorrect

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/bundle-canonical-kubernetes#722]
The "using ingress" docs in the CDK readme are incorrect.

> An ingress controller is provided to you by default and deployed into
the default namespace of the
cluster.

This is incorrect. The nginx ingress controller is deployed in the "ingress-nginx" namespace, not in the default namespace.

As a result, the output of `kubectl get pods` is incorrect: ingress controller is not shown in this output because it only shows pods in the default namespace.

`kubectl get ingress` also gives me a slightly different output: the `address` part is not present in my output.

My output:

```
$ kubectl get ingress
NAME               HOSTS                           ADDRESS   PORTS   AGE
microbot-ingress   microbot.10.10.137.209.xip.io             80      11m
```

```
$ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
microbot-5b9864df4d-57zfr   1/1     Running   0          12m
microbot-5b9864df4d-lntt2   1/1     Running   0          12m
microbot-5b9864df4d-zlszj   1/1     Running   0          12m
```

**Comment by joedborg** [comment]
Fix merged.  Thanks for raising @galgalesh.
