### ISSUE TITLE
hook failed: "config-changed" for kubernetes-master

### ISSUE THREAD

**Issue by antigenius0910** [juju-solutions/bundle-canonical-kubernetes#731]
Kubenetes master entering error stage.

```
kubernetes-master/0*  error     idle       0        172.29.100.185  6443/tcp        hook failed: "config-changed"
```

I tried followed on this tutorial, but it couldn't really get the hook to run. 
https://docs.jujucharms.com/1.25/en/authors-hook-debug

Can anyone explain to me where the 'charms' module is and how to load it for python3?
```
root@kubernetesBM:~# /var/lib/juju/agents/unit-kubernetes-master-0/charm/hooks/config-changed
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/hooks/config-changed", line 7, in <module>
    from charms.layer import basic  # noqa
ModuleNotFoundError: No module named 'charms'
```

I also submit this bug on here
https://bugs.launchpad.net/charm-kubernetes-master/+bug/1816825

**Comment by tvansteenburgh** [comment]
Closing this in favor of the Launchpad bug.
