### ISSUE TITLE
Unable to find documentation for k8s bundle manifest

### ISSUE THREAD

**Issue by notjames** [juju-solutions/bundle-canonical-kubernetes#733]
I'm able to find documentation for non k8s bundle showing the value objects. I'm unable to locate such a document for the k8s bundle manifest leading me to believe it's either non existent or very difficult to find. Is this something you guys would provide /fix?

**Comment by tvansteenburgh** [comment]
Hi @notjames. All the docs for Charmed Kubernetes are at https://www.ubuntu.com/kubernetes/docs. To suggest improvements to the docs, please file a bug at https://github.com/charmed-kubernetes/kubernetes-docs. Thanks!
