### ISSUE TITLE
[Track] - Reverting a "fix" for glusterfs volumes

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#75]
There was a fix landed to the kubernetes kubelet systemd scripts for GlusterFS. We're not clear on what this fix provided or why its necessary. This bug is to track this issue if GlusterFS becomes a supported backend by the Kubernetes-Worker charm.

**Comment by Cynerva** [comment]
For context, here's the upstream PR that introduced `KillMode=process`:

https://github.com/kubernetes/kubernetes/pull/23491

Credit to @wwwtyro for finding it originally.

And the PR where we revert it: https://github.com/juju-solutions/kubernetes/issues/52

**Comment by wwwtyro** [comment]
Looks like they're gonna look for a better solution to the storage issues: https://github.com/kubernetes/kubernetes/issues/34965

**Comment by chuckbutler** [comment]
Vote to close, systemd unit files are not being generated/applied via the charms anymore. This is all handled by the snaps and they generate implicit systemd unit files, that do not contain the inotify blocks which we removed.
No additional movement on the bug in upstream, it was targeted for 1.7 but had no work applied.
