### ISSUE TITLE
Make an SOS action

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#76]
Make an action that prints out the system information such as
- inotify
- inotify watches
- systemctl status of the kubernetes services.
- charms.reactive get_states
- kubectl get pods,svc,ingress,secrets,pv,pvc,rc --all-namespaces
- kubectl get nodes (any of the above that are not namespaced)
- docker info
- docker ps -a (if on worker)

Tar up the following files:
- The unit log files for unit invoking the action.
- The /etc/defaults/ files for this service.
- The /lib/systemd/ file for this service.

**Comment by mbruzek** [comment]
Users would run this action.
Then follow up with a juju show-action-output to see the printed values and `juju scp` the tar file down to their local computer.

**Comment by Cynerva** [comment]
Could this go in a base layer?

- `layer-sos` provides the `sos` action, which runs every script in `sos-scripts/` and produces a .tar.gz file with their output
- by default, `sos-scripts/` has scripts for basic machine info, unit logs, etc
- `layer-kubernetes-worker` includes `layer-sos`, plus its own sos-scripts for kubernetes and docker info

This would make our work here both reusable and extensible. Thoughts?

**Comment by mbruzek** [comment]
Great idea @Cynerva ! I approve this and would like to help you implement this, because if there is one thing I love is getting logs out of systems. 

What about naming the layer "support" so we would include `layer:support` in our top most layers. It would install things like ntp and have an "sos" action or what ever we call it.

**Comment by wwwtyro** [comment]
I agree, excellent idea. I'd also like to help, and I think there's plenty of work to go around. To be clear, I think the layout would look something like (using k8s-worker as an example):

- layer:support/
  - support-scripts/
    - generic log/metric collection scripts, e.g. `top`, `dmesg`, etc. that we would want for every charm
- layer:docker
  - support-scripts/
    - docker specific collection scripts, e.g., `docker ps -a`, `journalctl -o cat -u docker`, etc.
- layer:kubernetes-worker/
  - support-scripts/
    - k8s-worker specific collection scripts, e.g., `kubectl get po`, `kubectl get rc`, etc. If there's overlap with kas-master, we might need a generic k8s-layer to normalize them.

When built, the support scripts folder in the k8s-worker charm would be a merge of all the layers' support-scripts folder, e.g.,

- charm:kubernetes-worker/
  - support-scripts/
    - top
    - dmesg
    - docker-ps
    - docker-logs
    - k8s-get-pods
    - k8s-get-rc

If we take that tack, we'll need to prefix all our scripts to prevent them from being overwritten during the merge.

I feel a little nervous about doing things that aren't read-only, like installing ntp. Seems like if we want to ensure ntp is everywhere, we'd put it in layer:base?

**Comment by marcoceppi** [comment]
I think this is a great idea, in general, I'd like to - once we flesh this out somemore, to announce this as an /idea/ to the Juju mailing list for further feedback.

I'd also like to propose the name "apport", support seems too broad a name IMO (though it entirely depends on the name of the action, SOS I think seems appropriate

**Comment by mbruzek** [comment]
> I feel a little nervous about doing things that aren't read-only, like installing ntp. Seems like if we want to ensure ntp is everywhere, we'd put it in layer:base?

@wwwtyro In general a layer should install everything it needs to perform its function. I would argue that the time/date are critical to have if we are going to capture time sensitive data like log files (with timestamps) they need to be in sync with logs on other machines so we can properly correlate and compare times/dates.

**Comment by marcoceppi** [comment]
However, not all deployments will have access to a public NTP / time
server. We can't just assume there wont' be additional configuration
requirements

**Comment by chuckbutler** [comment]
I think that makes a case for the NTP charm instead of including NTP as part of the SOS layer. 

That gives the deployment operator an opportunity to omit this, in which case, they're on their own for adjusting for clock skew. But at least they won't have a failure or be deploying an application doomed to fail-cycle. 

Perhaps we make this 'recommended', and bundle it as part of the bundle, but don't enforce its presence or assume it's available. Thoughts?

**Comment by Cynerva** [comment]
Going to rename this to avoid conflicts with other uses of "SOS" ...
* [sosreport](https://github.com/sosreport/sos) (bonus: [juju plugin](https://github.com/sosreport/sos/blob/master/sos/plugins/juju.py))
* [sosreport_charm](https://github.com/karibou/sosreport_charm)

(thanks @chuckbutler for pointing this out)

Unless someone opposes, I'm gonna rename the action to `collect-debug` and the layer to `layer-collect-debug`:

1. The purpose is clear
2. It sounds like "collecty bug" and that makes me happy

**Comment by marcoceppi** [comment]
I don't really like collect-debug, I think `debug` would be better. However, I'm cool with collecty bug, just my 2cents

**Comment by Cynerva** [comment]
Cool, works for me. Renamed sos -> debug. Repo is at https://github.com/cynerva/layer-debug

I'm ready to move the repo to https://github.com/charms whenevs

**Comment by Cynerva** [comment]
Closing this. The debug action has been added to kubernetes-master and kubernetes-worker, and I believe we've covered all the ideas in this issue.
