### ISSUE TITLE
[Track] *api.service ended with:  very short watch.

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#77]
On a new deployment the status of kube-proxy is:

```
pkg/proxy/config/api.go:30: watch of *api.Service ended with: very short watch
```

**Comment by chuckbutler** [comment]
there was some prior discussion around this topic in the kubernetes upstream repo. I'd like to link this against that, so we have a place to start

https://github.com/kubernetes/kubernetes/issues/5311

where as it appears this is not so much a problem, as its an indication of transient failure, such as the apiserver getting restarted during operation. The alternative indicator is that we have a "sick" deployment, and the services are not actually available even though they are indicated as running by systemd.

**Comment by chuckbutler** [comment]
This happened historically but has not been present in deployments that I'm aware of.

I think this is safe to close as well
