### ISSUE TITLE
[ppc64le] filebeat doesn't have a package 

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#79]
When trying to deploy to ppc64le, filebeat fails and says it can't find a package. See log attached. 

[unit-filebeat-4.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/515714/unit-filebeat-4.txt)

**Comment by mbruzek** [comment]
Welcome to the wonderful world of different architectures! It looks like Elastic does not create a deb for ppc64le.

**Comment by chuckbutler** [comment]
There's an ongoing conversation with Elastic on getting official ppc64 bins.

Until then, they will have to be compiled and provided via resource (beats don't currently support resources at this time. That will eventually land in the 16.11 cycle)

**Comment by chuckbutler** [comment]
PPC64 bins are released as beta, and have been out for ~ a month now.

**Comment by Pensu** [comment]
@chuckbutler Any idea where can I find the ppc64/ppc64le bins? Are they still building them?

**Comment by tvansteenburgh** [comment]
As far as I can tell, Elastic does not officially support ppc64:
https://www.elastic.co/support/matrix

Although they do build nightlies for it:
https://beats-nightlies.s3.amazonaws.com/

So, you'll have to build it yourself, or use a nightly build from their jenkins server. Latest here:
ppc64: https://beats-nightlies.s3.amazonaws.com/jenkins/filebeat/1588-747cfd936bc685cc965161c2447300a434bb586f/filebeat-linux-ppc64
ppc64le: https://beats-nightlies.s3.amazonaws.com/jenkins/filebeat/1588-747cfd936bc685cc965161c2447300a434bb586f/filebeat-linux-ppc64le

Also see https://github.com/elastic/beats/issues/4274
