### ISSUE TITLE
Evaluate python packages for kubectl or encapsulate the command better.

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#83]
Come up with a better way to encapsulate the uses of kubectl in our code.

Either evaluate the python package: https://pypi.python.org/pypi/pykube/
Or encapsulate the kubectl in a utility class that handles all uses of kubectl in our code.

Which ever way is less code and easy to understand is the winner in my book.

**Comment by chuckbutler** [comment]
If anything, this should probably be the official kubernetes python project: https://pypi.python.org/pypi/kubernetes/2.0.0

I'm not certain that this still applies in the given context as its a feature request, and the charms currently leverage a stable cli integration. This will continue to be true until a major milestone where commands may be deprecated.
