### ISSUE TITLE
Flag Manager has bad behavior when removing / adding flags

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#98]
The flag manager was in large part cargo-culted from `charms.docker.DockerOpts` module.  The module was found to have bugs where when removing values, the flags were left behind and it was treated as flag-only options being rendered when called `to_s()` method on the flag manager.

Additionally, the flag managers do not assume any kind of 'update in place' mechanism, which directly conflicts with the flag managers 'multi-opts' style of values incoming to the flag manager. this extra layer of complexity that we had to satisfy for adding things such as docker-daemon labels, are goign to cause real issues when things like CIDR, Certificate Paths and basically anything else stuffed in the Flag Manager, wants an 'upsert' style change. 

EG Expected Behavior:

```
opts.add('foo', 'bar')
opts.to_s()
> --foo=bar

opts.add('foo', 'baz')
opts.to_s()
> --foo=baz
```

Actual Behavior:

```
opts.add('foo', 'bar')
opts.to_s()
> --foo=bar
opts.add('foo', 'baz')
opts.to_s()
> --foo=bar --foo=baz
```

Actual Removal behavior:

```
opts.add('foo', 'bar')
opts.remove('foo', 'bar')
opts.to_s()
> --foo
```

**Comment by mbruzek** [comment]
We have identified a few places in the kubernetes-master and kubernetes-worker code where this is likely a problem and need to remove the key AND value from the flag manager before adding a new one.

**Comment by mbruzek** [comment]
There are 2 flag managers, when we fix this lets combine them to use the same library so we don't have to maintain duplicate code.

**Comment by tvansteenburgh** [comment]
No longer valid.
